### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by johalun** [swaywm/sway#1004]
A lof of memcpy going on... (Using HW rendering, WLC_SHM is not set)

weston-simple-egl on Weston (weston process dtrace'd)
<img width="1226" alt="weston-simple-egl-on-weston" src="https://cloud.githubusercontent.com/assets/6335180/21436619/55869bd0-c834-11e6-9b64-62a8cefc60c4.png">

weston-simple-egl on Sway (sway process dtrace'd)
<img width="1226" alt="weston-simple-egl-on-sway" src="https://cloud.githubusercontent.com/assets/6335180/21436620/55873ef0-c834-11e6-9d5f-82facd5c87fc.png">

**Comment by Timidger** [comment]
I had noticed this as well, I wonder if it has to do with [this line in the border code](https://github.com/SirCmpwn/sway/blob/master/sway/border.c#L39). It seems that every time the border needs to be rerendered (which is quite often) the buffer is reallocated.

**Comment by SirCmpwn** [comment]
Border only needs to be rerendered on window size change or title updates AFAIK. The former requires us to reallocate the buffer anyway.

**Comment by Timidger** [comment]
Ah, ok. Looking at the fire graph again it looks like the majority of the memcpy's are happening deep in the `wlc_pixels_write` call stack, would it be an issue in wlc? I noticed that when attempting to draw things with one of the pre/post render hooks with Way Cooler it seemed to consume a lot of resources, even when I was not reallocating the buffers.

Is there a way to get the post/pre rendering cost down or is it just one of the tradeoffs to using a library that controls the rendering so heavily @cloudef?

**Comment by SirCmpwn** [comment]
If we were able to upload the border to the GPU that would probably be quite a bit faster.

**Comment by SirCmpwn** [comment]
We can actually do that by just using GLES2 directly, but that is a little bit icky because wlc technically is supposed to abstract that API away from us. Would still merge a PR that reworked rendering to use GLES directly.

**Comment by Timidger** [comment]
Is it not using GLES2 directly? It's calling some kind of opengl functions [here](https://github.com/Cloudef/wlc/blob/f4ff049cc30242eec9f33af7129d2e2a2865fb5a/src/platform/render/gles2.c#L840).

**Comment by SirCmpwn** [comment]
I'm saying sway could use GLES2 directly, not wlc. Currently sway renders borders with wlc_write_pixels, which is the only API we have for doing it through wlc even though it's not ideal. We could instead take wlc out of the loop and call GLES2 ourselves.

**Comment by Timidger** [comment]
Ah, ok gotcha

**Comment by johalun** [comment]
That would surely get rid of one of the "towers".  The other issue is that wlc is uploading buffers to the GPU when it doesn't have to.

**Comment by Cloudef** [comment]
@Timidger It's possible to improve this by caching the different canvases (per view, per output) in wlc to textures and only flush them when expliciptly told, this would keep the API unchanged and simply just add new function to clean canvas (remove texture). The fastest way to draw however is always going to use directly whatever wlc uses behind the scenes (in this case GLES2). See remarks in https://github.com/Cloudef/wlc/blob/master/include/wlc/wlc-render.h#L12-19 however.

As for other performance problems. Since wlc was originally designed as immediate API by mistake, meaning any wayland, X11, device, etc event and API calls are processed immediatly, things such as mouse input and  resizing may cause wlc to do lots of unneccessary work and redraws. Rendering is not immediate however, but it would be better if all events and calls would just be queued.

**Comment by Cloudef** [comment]
@johalun This is indeed because of wlc_write_pixels and it not keeping the writes in GPU for longer than next render.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
