### ISSUE TITLE
Real time video capture with swaygrab

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1006]
1. Implement orbital's screenshooter protocol in sway and swaygrab (and drop the IPC strategy)
2. Use libavcodec directly instead of piping pixels into ffmpeg's stdin

**Comment by lofenyy** [comment]
I'd be happy to be assigned this issue.

**Comment by SirCmpwn** [comment]
No one gets assigned to issues. Just do it and send a patch.

But... this is something we need to do in wlroots now, not sway.

**Comment by ascent12** [comment]
@lofenyy If you're serious about trying to do this, you should join #sway-devel.
This task would require a serious amount of work, though.

**Comment by SirCmpwn** [comment]
This is implemented :tada:

**Comment by howdoicomputer** [comment]
@SirCmpwn With swaygrab deprecated is there anything that replaces it for video capture?

**Comment by SirCmpwn** [comment]
examples/dmabuf-capture in wlroots is the reference implementation. Also check out https://github.com/atomnuker/wlstream

**Comment by howdoicomputer** [comment]
That was beyond fast. Thank you @SirCmpwn!

**Comment by levimake** [comment]
> That was beyond fast. Thank you @SirCmpwn!

How to make screen capture from that ? Can you explain ?

**Comment by howdoicomputer** [comment]
@levimake Oh, sorry. I was more replying to how quickly he replied to the thread. At the time, he replied 30 seconds or so after I had posted my question. I was very appreciative.

Unfortunately, I never figured out how to get something together. I ended up dropping Sway because of it, actually. I needed to use screen sharing applications for work related reasons and so I moved back to i3.
