### ISSUE TITLE
Focus problem when clicking on a workspace on swaybar

### ISSUE THREAD

**Issue by spcmd** [swaywm/sway#1104]
When I click on a workspace with the mouse it looks like all the windows are focused and I have to click inside a window to get that one focused. If there is only one window on a workspace, for example a browser, it looks like it has the focus but the window (browser) doesn't get "activated", doesn't respond to any key. I have to switch to another desktop and back _with the keyboard_  to get a proper focus.

I thought it's something with my config, but I tried with the default config and I have the same problem with it. 

I'm using sway on Arch Linux, I tried with the stable version (0.11-2) and then upgraded to the git version (r2170.d4aa604-1), but I still have this problem.

**Comment by skyfoosooc** [comment]
Another way do get focus back to a window is to "focus child" 2 or 3 times.

I've noticed the behaviour your talking about when executing "scratchpad show" to hide the scratchpad as well. Though I have yet to find a consistent way of reproducing the behaviour.

sway version : 0.12-rc1-18-gd4aa604
wlc version : 0.0.8.r0.ge071b6c-1

[config.txt](https://github.com/SirCmpwn/sway/files/817761/config.txt)

**Comment by Raumzeitkeks** [comment]
I also see this behaviour on **sway version 0.14.0** under ArchLinux and created a [debug log](https://gist.github.com/Raumzeitkeks/d1a42e7cc92d676605ae206cd4fdf658). 

An detailled description of what happens during log creation:
(Note: I have set '''focus_follows_mouse no''')
* Open sway
* Use keybinding to open terminal emulator on workspace 1
* Start logging with '''sway -d 2> sway.log'''
* Use keybinding to create and switch to workspace 2
* Use keybinding to open two terminal emulator windows on workspace 2
* Click on first (un-focused) terminal emulator and type something -> text appears
* Switch to workspace 1 by clicking on swaybar
* Switch back to workspace 2 by clicking on swaybar; same (first) terminal window appears focused
* Type something -> nothing happens (!)
* Click on "focused" terminal window
* Type something -> still nothing happens (!)
* Click on unfocused terminal window -> focus changes window
* Type something -> text appears
* Use keybinding to quit sway

When '''focus_follows_mouse''' is unset or set to yes sway shows equivalent behaviour.

**Also you do not even need to switch workspaces to reproduce. It is sufficent to click on any area of swaybar!**
I guess swaybar receives and keeps the focus, but the status of the other windows doesn't reflect this. That's why the broken "focused" window is highlighted as focused and doesn't receive focus even after being clicked, but unfocused windows work once they get focus.
