### ISSUE TITLE
Numpad and caps lock doesn't work

### ISSUE THREAD

**Issue by heato** [swaywm/sway#1380]
Numpad only works as arrow keys, I can't input numbers with it even with Num lock enabled.
Also, caps lock works as shift - when I hold it, I print with upper case. How do I make it work as caps lock (when it's enabled you type in upper case)?

**Comment by SirCmpwn** [comment]
Try switching to another window and back again.

**Comment by heato** [comment]
They're don't work on every window, switching don't help. Also, I think I should attach my environmental variables
```
export XKB_DEFAULT_LAYOUT=us,ru
export XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle,sway
```

**Comment by heato** [comment]
UPD: I'm dumb, numpad is working now but I still don't know how to make caps lock works as in other systems like windows

**Comment by kon14** [comment]
The caps lock inconsistency is a known bug that's been around for a while now (see #1266 for more)
You could work around it by specifying caps:none or caps:shiftlock in your XKB_DEFAULT_OPTIONS environmental variable and exporting it in a startup file appropriate for your shell.

If you're using some script to switch between layouts through setxkbmap (instead of reloading sway) you could apply the same workaround. Example: I use setxkbmap -option caps:shiftlock with a script called by macro key userspace driver to switch between (dvorak,gr) and (us,gr) for stuff that hardcodes for qwerty etc.
