### ISSUE TITLE
EWMH support?

### ISSUE THREAD

**Issue by Kommynct** [swaywm/sway#1449]
One of gnome/waylands initiatives is support of this

https://wiki.gnome.org/Initiatives/Wayland/Gaps#ICCCM.2BAC8-EWMH

Would this enable access to window_role and such? Is it even worth adding?

If so, it should probably be on the roadmap for either this or wlroots.

This projects pretty great but its really annoying not to be able to have popup windows be non-tiling.

Thank you for your time.

**Comment by acrisci** [comment]
Actual EWMH support is not worth it. This issue is talking about an EWMH replacement which we are talking about right now.

window_role is different. It's a property of an X11 window which we don't keep track of right now in wlroots, but I guess the implementation wouldn't be too complicated. I would be wary of supporting the old properties because of possible future conflicts with new properties that might come about in the shell interfaces to replace this.

If you can work around it with another kind of criteria or a simple ipc script, you probably should because it might be awhile until this can be implemented.

**Comment by SirCmpwn** [comment]
I think we can support role for xwayland even if future properties with the same name come around for other shells. With the design I have in mind it will make sense to support both.
