### ISSUE TITLE
Feature request: Enable debug logging on the fly

### ISSUE THREAD

**Issue by codethief** [swaywm/sway#1474]
As mentioned in another thread, I'm trying out Sway for the first time. I've been running into half a dozen bugs so far – some minor, some major – and noticed that some of them appear pretty randomly and are thus hard to reproduce. This makes it pretty difficult to just restart Sway with logging enabled, reproduce the bug and then come back here with the debug logs. (Let alone that it'd rather not always stop everything I'm doing and close all applications every single time I encounter a bug.)

For this reason, it would be nice if it was possible to get one's hands on the debug logs on the fly (without having to restart Sway), just like it is possible with i3.

**Comment by 4e554c4c** [comment]
Stop complaining and send a patch if you want something changed.

**Comment by myfreeweb** [comment]
Why not keep debug logging enabled all the time?

**Comment by codethief** [comment]
@4e554c4c I apologize if I came across as demanding. However, please do try to understand my perspective as well: 

Right now, Sway is pretty much in an unusable state for me. I'm not saying this to complain; in fact I love what you guys are doing here and have been following the project for quite a long time and will keep on following it. The thing is just that with something as essential as a compositor / window manager it costs a hell of a lot of energy and time to debug issues while one is actually trying to do some other work. (I mean, who am I telling this… you probably know this better than I.) I'd either have to maintain a second compositor that I use to do actual work while I'm keeping the first one just for fun (and debugging) or I'd need to two machines or whatever. At the end of the day the reality is this: It's simply impossible for a user of open source software to fix every single bug he runs into or implement every single feature he'd love to see realized. I can't possibly dig into the code of every single software I'm using.(*) I have to focus on some projects and leave out others. Period.

(*) Yes, the actual implementation of the requested feature is probably simple. But first I'd have to set up the build environment and so on and so forth…

Now what I *could* have done would have been to try Sway, realize that it's not working properly and uninstall it again right away. But I figured I could at least report the bugs so that you as the developers are aware of the issues I'm experiencing. (I thought this was the whole purpose of providing a public bug tracker?) And yeah… while trying to debug other issues I realized that on-the-fly logging would be a good thing. In fact, I thought that this might potentially be a feature keeping other users from reporting bugs in the first place. You might call this "complaining" and maybe your general perception of bug reports and feature requests is that of "complains". In that case, I'd recommend creating a private repository (or, in this case, a fork) in which you can code just for yourself. Then you will only have to make sure that things are working for you and you won't have to worry about other users "complaining" that it's not working for them.

Differences of opinion and/or perception aside, thank you all again for the time and effort you're putting into making an i3-like WM for Wayland a reality.

**Comment by codethief** [comment]
@myfreeweb You're right, that'd probably do the trick as well. Though then I'm wondering why log messages are not being written to, say, `/var/log/sway` automatically and this has to be done manually instead through shell scripting. So maybe I should rename this request to "Enable logging by default"?

**Comment by 4e554c4c** [comment]
@codethief,
Yes, you're right, and I apologize for being rude.
However, I have spent lots of time trying to create features and fix bugs for sway users (not as much as some, but it is still a labor of love), and it is quite disheartening to hear that it is completely unusable.

The sad truth is that we don't have enough contributors to fix all the bug reports that come in. I am trying to dedicate all the time I can to my subsystem, which isn't much, and most other contributors are focused on new big-picture changes with wlroots. This is why "send a patch" was my reply, not because I don't care about users, but we have to ask for all the help we can get (though I understand that each user of foss can only dedicate time to so many projects).

I now understand your point, and am thankful for your report. It is just difficult to respond to bug reports that accuse sway of not being usable accurately.

Furthermore, I would like to say that I agree with this feature. I have been meaning to improve debug logging for awhile, and once the feature freeze is over I will make this a priority.

**Comment by SirCmpwn** [comment]
This is not something I would like to support. It's been requested before.
