### ISSUE TITLE
Updated instructions on installing sway + wlroots?

### ISSUE THREAD

**Issue by andrewwakeling** [swaywm/sway#1530]
I would love to try sway, especially with wlroots.

I'm aware that there is an installation guide for Debian, but is there a more up-to-date guide on installing Sway with wlroots?

**Comment by 4e554c4c** [comment]
It's not yet released.

**Comment by cawilliamson** [comment]
Whilst I do understand this isn't released - it is possible to compile it and there wouldn't be any harm in updating the README in the "wlroots" branch of this repo since it wouldn't be merged until that was merged to master anyway.

I'll get around to writing a PR with updated build instructions - it really was a pain in the arse when I did build it.

**Comment by SirCmpwn** [comment]
No. The sort of people who can't figure out how to build this and the sort of people who should be using this right now are mutually exclusive groups. It's not done, or even remotely close to it.
