### ISSUE TITLE
Support bar config update IPC event

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1651]
Both in sway and in swaybar

**Comment by ianyfan** [comment]
What does this still require?

**Comment by SirCmpwn** [comment]
swaybar should listen to it and reload its config when it occurs, then we don't have to restart the swaybar process on reload

**Comment by ianyfan** [comment]
So is this only on config reload? Not when the hidden state/mode is updated?

**Comment by SirCmpwn** [comment]
I think so, right?

**Comment by ianyfan** [comment]
Makes sense, but I don't think you can distinguish between the different cases from just the event. Though since the other cases aren't implemented yet, I guess it doesn't matter for now.

**Comment by ianyfan** [comment]
Started having a look at this, specifically at i3 behaviour, which does appear to only update upon receiving the event. The thing is, this means that if you add or remove bars in the config between reloads, then they do not register upon reload, i.e. added bars do not get added and removed bars do not get removed. Is this the behaviour we want to replicate? Just wondering because in i3, you can still add or remove bars by using the restart command, which is not supported by sway.

**Comment by SirCmpwn** [comment]
I'm not really too concerned about supporting bar config update to be honest. Right now we just kill the bar and spawn new ones, which is fine with me. Thanks for looking into it.
