### ISSUE TITLE
Reloading config should reset scale, mode, … if unspecified

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#1752]
At runtime, not specifying an output option means "don't change it". On reload, not specifying an output option should mean "reset it to the default".

**Comment by SirCmpwn** [comment]
We want to overhaul the parser, if @minus7 ever has the time :')

https://github.com/swaywm/sway/issues/1034

**Comment by aenda** [comment]
Additionally, right now reloading when an output command is specified in the config seems to mess up scaling on newly launched xwayland apps (at least dmenu and kitty for me, it looks zoomed so that fonts are about twice as large). Apps that had already been launched are fine. This occurs for me with `output eDP-1 resolution 1920x1080 position 1920,0` in my config and stops when I remove it.

**Comment by emersion** [comment]
Might be fixed with xorg-server-xwayland 1.20.
