### ISSUE TITLE
Detect HiDPI displays and automatically set scale=2

### ISSUE THREAD

**Issue by ddevault** [swaywm/sway#1800]
Unless the user specifies it manually, of course. What are the criteria for identifying a HiDPI display (e.g. a minimum ppi)?

**Comment by NilsBrause** [comment]
Since sway has fractional scaling, you could even make the scaling factor a function of the PPI, e.g. scale=ppi/100. That way, everything would have consistent physical dimensions on every display.

**Comment by SirCmpwn** [comment]
We're not going to set a non-integral scale factor by default.

**Comment by NilsBrause** [comment]
Okay. Does fractional scaling have any downsides in sway?

**Comment by SirCmpwn** [comment]
Yes, it has downsides in all situations. We have to either copy pixels or drop pixels, it's impossible to faithfully render clients at a fractional scale factor.

**Comment by NilsBrause** [comment]
I see. In that case, I'd say about 200 ppi. Also scale=3 for 300 ppi and so on.

**Comment by clarfon** [comment]
Perhaps it'd be helpful to show the "real" fractional scale factor in `swaymsg -t get_outputs` at least so people don't have to compute it themselves?

**Comment by emersion** [comment]
I don't see the point. If you don't want to compute it, don't specify it and (when this feature will be implemented) sway will automatically use it.

**Comment by clarfon** [comment]
@emersion I'm specifically talking about the case of fractional scaling; @ddevault already mentioned that fractional scaling will not be the default. So, for people who want to override their display to use fractional scales, rather than rounding to the nearest integer, they can easily figure it out rather than having to compute it.

**Comment by emersion** [comment]
I'd rather not promote fractional scaling.

**Comment by pat-s** [comment]
Coming from i3 since a few days, `sway` already does a perfect job on my mixed DPI setup. I got a 13' Full HD laptop besides a 4k 27' one. The 4k one looks good at around 160 DPI and the laptop at 96 DPI.

I never managed to get a working setup in X before (one was always sharp, the other one blurry due to scaling). With `sway` and `wayland` both look sharp by default. Applying `scale = 2` by default to the 4k would not make my world better.

Or do I overlook something here?

**Comment by emersion** [comment]
You mean "it looks sharp with fractional scaling, why isn't this the default?"

This is definitely not happening. We've already discussed this countless times, fractional scaling has performance issues and is a big lie (no matter how it's implemented). Here's an article that explains the issue: https://medium.com/elementaryos/what-is-hidpi-and-why-does-it-matter-b024eabea20d

**Comment by pat-s** [comment]
No. I mean the sway default without any scaling looks good and sharp in my mixed DPI setup. So I wonder why the default should be changed. 

Maybe things changed since this issue was opened?

**Comment by emersion** [comment]
The way auto-scaling is implemented hasn't been decided yet. Some have mentioned setting scale=2 for 200+ DPI screens, which wouldn't affect you. More research is required.

**Comment by rtsisyk** [comment]
Is it possible to don't scale XWayland?

**Comment by ddevault** [comment]
We don't respond well to being pestered.
