### ISSUE TITLE
zxdg_toplevel_v6_set_fullscreen output argument not respected

### ISSUE THREAD

**Issue by atomnuker** [swaywm/sway#1813]
If a program wants to go fullscreen on a specific output it can set it explicitly via an argument of zxdg_toplevel_v6_set_fullscreen. This currently does nothing under sway.
Can be replicated with 2 outputs and mpv: mpv <file> --fs --fs-screen=X --gpu-context=wayland

**Comment by emersion** [comment]
Fullscreen isn't implemented yet.

**Comment by RyanDwyer** [comment]
I had a look at this but I couldn't see how I'm supposed to retrieve the output from mpv. It looks like we're supposed to receive a `request_fullscreen` event which has the output in the event data, but this event is not fired when I run the above mpv command. Instead it runs the map handler without having called `request_fullscreen`, and we apply fullscreen when mapping because it's marked as such in the pending state.

For anyone looking into this, note that it uses `xdg_shell_v6` and not `xdg_shell` when using `--gpu-context=wayland`.

**Comment by emersion** [comment]
Yeah, this is most likely because the `new_surface` event is emitted after the `set_fullscreen` request.

**Comment by RedSoxFan** [comment]
So the requested output can be stored in the pending state by wlroots, which can be retrieved by sway when mapping. What I'm not sure about is how to handle the view being fullscreened on a specific output.
1. If it is not already mapped, should the view be mapped to the visible workspace on the output (ignoring focus, assigns, etc)? 
2. If it is mapped, should the view be automatically moved to the visible workspace on the output? If yes, does this need to be moved back when exiting fullscreen?
