### ISSUE TITLE
Epiphany right click menu not working in fullscreen

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#1922]
Input is messed up

**Comment by aperezdc** [comment]
This might be related to [WebKitGTK+ bug #170553](https://bugs.webkit.org/show_bug.cgi?id=170553), which I tried to fix a while ago but broke things and the patch was reverted. I'll try to at least get the part for the right click menu (context menu) fixed, which fortunately is the easiest one.

**Comment by aperezdc** [comment]
I have submitted a [new patch](https://bugs.webkit.org/attachment.cgi?id=341451&action=diff) for merging into WebKitGTK+ which makes the context menus **appear** correctly over the MiniBrowser window when running under Sway/wlroots, **but mouse input goes to the window** instead of to the context menu. If one uses right-click to open the context menu, and *then* the arrow keys in the keyboard, the menu items can be selected and activated with `Enter`.

I suspect that there may be something that needs being fixed in Sway or wlroots to make input go to the context menu.

(JFTR: MiniBrowser is included in the WebKit sources, we use it for testing).

**Comment by SirCmpwn** [comment]
Can no longer reproduce this
