### ISSUE TITLE
swaybar: use wl_pointer.axis_discrete when available

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#1930]
Scrolling on a touchpad is not possible because it's way too fast. Using `wl_pointer.axis_discrete` should fix the issue.

Depends on https://github.com/swaywm/wlroots/issues/905

**Comment by c-edw** [comment]
Just found a bug that I think might be related to this. If you scroll on the bar using a mouse, it will reach a 'boundary' and stop. However, if you use a touchpad to scroll, it will wrap back around (though you have to scroll quite fast). @emersion Please confirm whether this would be fixed with this change.

**Comment by emersion** [comment]
Yeah, I think it's related. I haven't tested if libinput correctly sends correct discrete events, but I hope so.

**Comment by emersion** [comment]
Closed by https://github.com/swaywm/sway/pull/5067
