### ISSUE TITLE
Swaybar not displayed if its output not present

### ISSUE THREAD

**Issue by tardypad** [swaywm/sway#1938]
Sway 0.15.2 on Arch Linux

Example pseudo config
```
# Defines outputs
output O1 # laptop screen
output O2 # external monitor

# Assign workspaces per output
workspace W1 output O1
workspace W2 output O2

# define bar on external monitor
bar {
output O2
}
```

If I don't connect my external monitor, the workspace W2 get displayed properly nevertheless in the laptop screen on output O1
However, the bar behaves differently and is not displayed at all

Would it be possible to have the bar displayed anyway?

**Comment by RyanDwyer** [comment]
I don't think this will be changed, because you might already have a bar defined for the laptop screen, and moving the external output's bar to the laptop would cause a double up.

What I do is use a wrapper script around sway which checks if a monitor is plugged in, and applies a different configuration if so:

    if grep -qs E2441 /sys/class/drm/card0-HDMI-A-1/edid; then
        sway -c ~/.config/sway/desk.conf
    else
        sway -c ~/.config/sway/solo.conf
    fi

Here, E2441 is the model number of one of my monitors. Both of these configuration files set the outputs and bars as desired, then `include ~/.config/sway/common.conf` which contains all my common configuration.

**Comment by emersion** [comment]
Instead of grepping `/sys/class/…`, you can grep `swaymsg -t get_outputs`

**Comment by RyanDwyer** [comment]
Not if sway isn't running ;-) I run that from a TTY.

**Comment by emersion** [comment]
Oh, you can just change the bar config via IPC instead of doing this weird config file switching.

**Comment by tardypad** [comment]
I understand the problem with the double bar
In any case, thanks for the config tip, that wrapper is gonna be good enough for me I think

I'm not sure I understand the IPC version though
I don't see any such command to change the bar config afterwards
