### ISSUE TITLE
border toggle gives focus to first child on workspace

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1951]
It should leave focus on whatever it was toggling the border of.

**Comment by RedSoxFan** [comment]
It appears that this is due to the following in `sway/commands/border.c`:
```c
struct sway_seat *seat = input_manager_current_seat(input_manager);
if (seat->cursor) {
    cursor_send_pointer_motion(seat->cursor, 0);
}
```

This affects all arguments of the border command, not just toggle, and only with `focus_follows_mouse yes`. Additionally, it isn't necessarily the first child, it will switch focus to whatever is under the cursor.

I'm not sure what the snippet is trying to accomplish in relation to changing the border style, otherwise I would create a PR to remove it.

**Comment by SirCmpwn** [comment]
The commit that was added in was by @RyanDwyer with the proported goal of updating the cursor when the border style changes.
