### ISSUE TITLE
Semi-transparent borders look ugly

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#1984]
Try e.g. `client.focused #4c7899 #28557733 #ffffff #2e9ef4 #285577`

**Comment by RyanDwyer** [comment]
The majority of issues this issue is referring to are already resolved, however there's still one issue with the title and marks textures that are unresolved, which is obvious when using the above config.

* We set the cairo texture background to the colour and alpha supplied in the config.
* We render this right next to a `wlr_render_rect` which uses the same colour and alpha.
* The colours are different.

**Comment by emersion** [comment]
Will probably break again because of https://github.com/swaywm/wlroots/pull/986
