### ISSUE TITLE
Wayland key repeat issues

### ISSUE THREAD

**Issue by natesymer** [swaywm/sway#2073]
Keyboard hold-to-repeat-key doesn't work on Wayland - but it works fine in XWayland.

Oddly enough, a GUI program (that uses a UI framework with both X11 and Wayland backends) that displays the bug in Wayland will work fine in X11.

**Comment by emersion** [comment]
What program are you using?

On Wayland the client is in charge to implement key repeat - so some programs may have that unimplemented.

**Comment by martinetd** [comment]
It might not be what was reported but for what it's worth sway itself has the problem for keybindings.
For example, enter resize mode and hold some movement key; in i3 that would repeat the command at repeat-key rate, in this version of sway it would only do one step and you'd need to manually mash the key if the resize step is small instead of holding it down.

(I'm not sure I can argue than holding logo+enter to spawn many terminals is something most people do, but that has the same behaviour obviously :P)

**Comment by Hello71** [comment]
keybind repeat still doesn't work in wlroots. useful commands to repeat include resizing and brightness or volume adjustments.

**Comment by Hello71** [comment]
This seems to have been resolved at some point.

**Comment by emersion** [comment]
Yeah, this has been fixed.
