### ISSUE TITLE
missing debugging instruction

### ISSUE THREAD

**Issue by ael-code** [swaywm/sway#2151]
I couldn't find any relevant info in the [HACKING guide](https://github.com/swaywm/sway/blob/master/HACKING.md) about how to debug sway.

I compiled a debug build, run it and tried to attach with gdb using --pid. The whole interface froze and I needed to restart the system.

In issue #489 I found some this command:
```
 gdb -batch -ex "run -d" -ex "continue" -ex "generate-core-file" ./bin/sway
```
But it doesn't allow you to have a live instance of gdb attached to the sway process.

I really would like to contribute, but I'm missing some basic hacking instruction

**Comment by emersion** [comment]
Hi,

If you want to debug, the easiest thing to do would be to start `gdb sway` inside of sway - there you can pause the inner sway without freezing the outer one. Note that you can debug Sway like this inside any Wayland or X11 compositor.

If you need to debug the DRM backend, you'll need to either use coredumps or SSH into your machine from another one.

Hope this helps!

**Comment by ascent12** [comment]
I'd like to note that starting an interactive debugger on the DRM backend is just going to cause issues. Due to the way the DRM rendering loop inherently works, pausing it can really mess it up, and if you're unlucky, it can completely break your session.
As @emersion says, it's generally better to rely on coredumps.
