### ISSUE TITLE
pinentry-gtk-2 doesn't get frame events

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2181]
I figured out why I had issues with the split layout here: https://github.com/swaywm/sway/issues/2161

I was using pinentry-gtk-2, not pinentry-gnome3.

**Comment by emersion** [comment]
For those wondering, a simple way to reproduce is:

```
echo getpin | pinentry-gtk-2
```

**Comment by RyanDwyer** [comment]
This appears to be a bug in pinentry-gtk-2 (or gtk-2) which occurs when the compositor requests a size outside of the view's min/max size hints. This happens when it's tiling.

The issue does not occur when the view is floating because it would be at the desired size. And it would be floating by default, except that we don't recognise the `NET_WM_STATE` property yet. The client sets it to `MODAL`.

I tested it by removing this call to `gtk_window_set_geometry_hints`: https://github.com/gpg/pinentry/blob/master/gtk%2B-2/pinentry-gtk-2.c#L112-L113

**Comment by RyanDwyer** [comment]
Correction: pinentry-gtk-2 doesn't set the `NET_WM_STATE` to `MODAL`. It looks like it does in the code though.

You can't xprop it easily because it does a cursor grab - so I had to comment out the grabbing part of pinentry in order to xprop it. And yeah, the state is set to normal.
