### ISSUE TITLE
Firefox leaves tooltip behind

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#2529]
1. Open Firefox
2. Open a tooltip by e.g. leaving the cursor over a tab for a few seconds
3. Switch to another workspace
4. Tooltip remains

Doesn't happen in GNOME, we're probably missing something.

**Comment by tsloughter** [comment]
I just noticed that they also will display when I'm on another workspace and put my mouse cursor in a place that were I on the workspace with firefox a tooltip would show.

**Comment by dvejmz** [comment]
Is this a 1.0 issue or a 0.15 issue? I've tried to reproduce this on 0.15.2 and I got a different (but also wrong) behaviour. If I make a tooltip appear on Firefox, I cannot switch workspaces as long as the tooltip is on display. As soon as I hover my mouse out and the tooltip disappears, I can switch workspaces again.

This doesn't happen in Chrome.

**Comment by tsloughter** [comment]
It is a 1.0 issue. And the issue you mention with not being able to switch workspaces is fixed in 1.0.

But it also seems this issue is now fixed. I realized I hadn't noticed it in a bit so just tried again and wasn't able to produce it anymore.

**Comment by emersion** [comment]
Can reproduce 100%.

**Comment by Limero** [comment]
I can reproduce this with Firefox on xorg. It does not occur when running Firefox with Wayland nor on Chromium.

**Comment by dnfm** [comment]
This appears to be all gtk apps, as I came here to report the same issue I'm experiencing, however it does it to me in the 'claws-mail' app as well.  I am running the latest trunk from git as of 2018-12-23.

**Comment by trobjo** [comment]
The issue seems to be solved now. At least I don't experience the behavior. I'm running the latest sway + latest firefox nightly and gtk 3.24.1-1.

**Comment by emersion** [comment]
Ate you using Firefox as an X11 app or as a Wayland app?

**Comment by ascent12** [comment]
I'm using X11 firefox and I still get it.

**Comment by trobjo** [comment]
Ah okay, sorry about that. I use the Firefox with Wayland.

**Comment by mxmilkb** [comment]
It happens for me when using workspace next/prev and the cursor goes from being over the xwayland firefox window to an inactive xwayland window. If instead the cursor lands on an active xwayland window or a wayland window, it disappears.

After the tooltip has started to remain on screen, it will continue remaining on screen until I move my mouse, so even if it subsequently lands on an active xwayland window or a wayland window through use of workspace prev/next, it remains on scren.

Argh; so, a counter example - my window setup is thus; by workspace, 1) soulseekqt (wayland) 2) a small floating urxvt 3) two urxvt side by side 4) firefox 5) quassel (wayland). If I  start with the cursor over firefox and get a tooltip, then hit workspace prev and it lands on the inactive urxvt, I can hold down my workspace prev hotkey and it cycles endlessly in that direction with the tooltip on. If I then, without moving the mouse, do workspace next, the tooltip disappears once the cursor lands on quassel.

But(!); the tooltip remaining bug also happens when I click on the workspace names in the bar to change workspace. If I change workspace then move the cursor down to a position over a non-active window and the same coordinates of FF element that would give me a tooltip if I were on the FF workspace, I get a tooltip popping up. I can get multiple different tooltips this way.

**Comment by emersion** [comment]
Continuing to track in https://github.com/swaywm/wlroots/issues/1595, because it's a wlroots issue, not a sway issue.
