### ISSUE TITLE
Proposal: exec --secure [...] and IPC_EXEC

### ISSUE THREAD

**Issue by ddevault** [swaywm/sway#2608]
Ref #2375 

The problem is that sway's `exec` command uses the shell. If our security config looks like, for example:

    permit /usr/bin/swaylock layer_shell input_inhibit

Then we have to compare, for example, `swaylock -i ~/wallpaper.png -s fill` against `/usr/bin/swaylock`. Note that we only secured `/usr/bin/swaylock`, and if it appears anywhere else in the path we should not permit its use of secure features. We also need to consider that an attacker could try to execute `swaylock && keylogger`, and for that we need to understand how the shell will plan and execute the command - and for that we literally need a shell parser.

One solution *is* to add a shell parser to sway, probably via @emersion's [mrsh](https://git.sr.ht/~emersion/mrsh), which can be used as a library and contains a general purpose shell parser. However, I'm worried that if /bin/sh is bash or an even more exotic shell, then mrsh's sh parser might miss some bash-specific features which again open us up to malicious use.

Instead, I propose `exec --secure [...]`, which would execute the command *without* the shell. If a shell is necessary, the user can write a script and `exec --secure that-script`. We can then know for sure which binary is being executed and confidently apply security policies. Anything executed without `--secure` would be executed with the default policy.

One use-case this poses a problem for is running, for example, [grim](https://github.com/emersion/grim) in a terminal. If you did `swaymsg exec --secure grim screenshot.png`, it will write `screenshot.png` in sway's working directory, not swaymsg's working directory. It will also be non-blocking, so if you attempt to immediately use screenshot.png you could get a ENOENT or read a partial file. Also, if grim fails, the exit code of swaymsg will still be zero.

To address this problem, I propose adding the `IPC_EXEC` IPC command and a corresponding `sway-exec` tool to use it. If you do `sway-exec grim screenshot.png`, it will send an `IPC_EXEC` command to sway with the command, working directory, environment, and transfer any open file descriptors (e.g. stdin/stdout) for sway to dup2 into the new process. Then sway will execute the command and notify sway-exec when it completes and the exit code, and sway-exec will block until then.

RFC.

**Comment by emersion** [comment]
PID is not always reliable, because it's racy and on Xwayland it's provided by the client. It's also not available on BSDs. But yeah, this solution could be better anyway.

**Comment by SirCmpwn** [comment]
We can't wait for a view to map, because not all secured protocols use views (e.g. dmabuf export). We'd have to add bind listeners to everything and disconnect clients that aren't authorized. Instead I want us to create the wayland connection for the client (by passing `WAYLAND_SOCKET`, something I already implemented in my PR) and then we can just set up a global filter that checks the list of authorized wl_clients before showing secure globals. I also only want to transfer grants to children explicitly, not implicity. On top of that, PIDs are not reliable, as @emersion mentioned.

**Comment by emersion** [comment]
Note that we don't need to wait for the view to map for Wayland clients, we can just get the connection credentials.

**Comment by Snaipe** [comment]
Can't we actually use socket credentials (Linux and FreeBSD have SO_PASSCRED, OS X has LOCAL_PEERCRED, and OpenBSD has SO_PEERCRED) to retrieve the pid of the other side of the socket connection, and then check that the process is authorized? If the connection closes before you're able to do security checks on the PID, you can assume that whatever check you did on /proc or whatever is no longer valid.

**Comment by emersion** [comment]
>PID is not always reliable, because it's racy and on Xwayland it's provided by the client. It's also not available on BSDs. But yeah, this solution could be better anyway.

I want to correct myself:

* For this use-case PIDs are reliable
* We don't need to support Xwayland
* It's available on OpenBSD, but I don't think it's available on FreeBSD

However:

* It requires procfs
* Doesn't work well when the client uses an interpreter like Python

**Comment by Snaipe** [comment]
> It's available on OpenBSD, but I don't think it's available on FreeBSD

AFAIK pretty much all unices have some form of socket credentials for AF_UNIX, because you can't do secure IPC without that.

> It requires procfs

That's only true if you only implement your checks to use /proc -- systems that don't have a procfs have other APIs to check, for instance, the path of an executable executable by PID through sysctl.

Another benefit of using socket credentials is that no other mechanism would let you check that the program connecting has the right uid/gid, which in turn would allow you to e.g. deny any program not running as the same uid as the sway process, or whitelist gids that you'd reserve for IPC with sway.

**Comment by Snaipe** [comment]
> Doesn't work well when the client uses an interpreter like Python

Also, small addendum regarding scripts:

You pretty much can't reliably check a script's path anyway. As you implied, the executable name for a script is the interpreter itself, and APIs to retrieve the cmdline of a process are usually unreliable, because it reads the process's argv, which can be mutated.

Thankfully, there are many solutions for embedding scripts in actual executables (shc, py2exe+cython), which is precisely why I would encourage using slightly permissive settings by default, because security-conscious people know what they can and can't do.

**Comment by emersion** [comment]
I still don't find anything for FreeBSD. `SO_PEERCRED` is supported but doesn't include the PID. See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=215202

Side note: it may be possible to ptrace an executable that has privileges? Using `WAYLAND_SOCKET` instead doesn't fix this issue. See https://lists.freebsd.org/pipermail/freebsd-current/2017-July/066541.html

**Comment by Snaipe** [comment]
Actually, since PIDs are an issue, you can entirely enforce group credentials for processes rather than checking if they're the right executable. For instance with grim & screenshots, you could define a `wl-screenshot` group in your sway config, run `chown :wl-screenshot /usr/bin/grim; chmod g+s /usr/bin/grim`, and check the group credentials. You'd have to have distro maintainers and other wayland compositors to agree on the groups to use, but this would be more practical than checking executable paths.

**Comment by bl33pbl0p** [comment]
There's a c-shquote library if you want to look into it. https://github.com/c-util/c-shquote

**Comment by emersion** [comment]
Yeah, groups could be used, but fine-grained control of security features is annoying. You cannot do one group per Wayland protocol you need to lock down because some clients might need multiple privileged protocols. So you need one group per client, with a security file that defines which group can have access to which protocols.

Yet another idea would be to use per-client tokens. This only works if each client has a safe place to store tokens so that they cannot be read by other clients (e.g. containers).

**Comment by mvdan** [comment]
> Instead, I propose `exec --secure [...]`, which would execute the command _without_ the shell.

Another advantage of this is the overhead for daemons. Right now I use sway's config to start some sway-related daemons, like `exec kanshi >/tmp/kanshi.log 2>&1`. That ends up being one `sh` process and one `kanshi` process, which is unfortunate - the shell actually ends up using more memory than kanshi :) I get that redirects are shell, but I guess writing stdout/stderr to a file wouldn't be hard to implement.

**Comment by emersion** [comment]
You can use the (awkward) `exec exec …` notation to avoid the extra process.

**Comment by mvdan** [comment]
I imagined so, though it's a bit awkward as you say.

**Comment by emersion** [comment]
Closing, I don't think this is a good way forward.
