### ISSUE TITLE
X11 windows are not configured when workspace is moved

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#2673]
1. Have two outputs
2. Open Firefox on the right one
3. `move workspace to output left`
4. Type something in the URL bar
5. The popup shows up on the right output

To "fix" it force Firefox to be re-configured, e.g. open another client on the same workspace.

**Comment by RyanDwyer** [comment]
A similar thing happens when you do the following:

* Have Firefox in a workspace by itself
* Open another view so it appears to the right of Firefox
* Swap the views using `move left` or `move right`
* Open a popup in Firefox or make a tooltip appear - it'll be on the left half of the screen rather than the right.
