### ISSUE TITLE
Fix or remove edge_gaps

### ISSUE THREAD

**Issue by RyanDwyer** [swaywm/sway#2727]
Sway 0.15 introduced a command/syntax `gaps edge_gaps on|off|toggle`. It has the following documentation:

    **gaps** edge_gaps <on|off|toggle>::
        Whether or not to add gaps between views and workspace edges if amount of
        inner gap is not zero. When _off_, no gap is added where the view is aligned to
        the workspace edge, effectively creating gaps only between views. The toggle
        argument cannot be used in the configuration file.

The feature does not exist in i3-gaps.

In the 1.0 alpha, the command exists but doesn't work correctly.

The options I see are:

1. Remove the command.
2. Remove the command and allow setting negative values for `gaps_outer` which allows the user to achieve the same effect.
3. Implement the command.

My preference is 1.

**Comment by DawidLoubser** [comment]
Sway's seamless per-display scaling offers a heavenly solution to my HiDpi 14-inch laptop screen (where I set scale to `1.4`) and my standard DPi, external 4k screen (scale `1.0`).

Literally my only complaint is the ugly gaps between windows, and between a window and its decoration, while on my 1.4-scale laptop screen.

So my vote goes for #3 - implement the command, or at least build default behaviour to collapse sub-pixel gaps to 0, instead of rendering an ugly 1-pixel gap.

**Comment by RyanDwyer** [comment]
What you're describing is not related to `edge_gaps`. That sounds like a bug which should be fixed regardless.

**Comment by DawidLoubser** [comment]
Ah, apologies - I'll open a new thread sometime with screenshots etc.
Thanks for the clarification!

**Comment by tarmack** [comment]
I went the easy route, and don't allow the negative value to move windows outside the container.

The token value of -1 in the `workspace_config` seems to not pose issues but I may not fully understand the reason and working of that piece of the sway code anyway.
