### ISSUE TITLE
Switching workspaces with focus_follows_mouse focuses the wrong window

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2815]
It focuses the one underneath the mouse, not the focus_inactive window.

**Comment by tarmack** [comment]
Would this be as easy as just setting the `allow_refocusing` to false in the `workspace_switch()` function in `commands/workspace.c`? It does at least fix it somewhat.

I'll be looking for strange side effects from this change..

**Comment by SirCmpwn** [comment]
Probably

**Comment by tarmack** [comment]
Yeah no, it is not that easy. It seems that this issue is one in a long line of mouse focus issues (such as: [2401](https://github.com/swaywm/sway/issues/2401) and [2558](https://github.com/swaywm/sway/issues/2558)). I noticed that if you move a tiling window away from under the pointer, scrolling events keep going to the focused window (now no longer under the cursor). But as soon as the cursor moves a bit the focus jumps to the window now under the mouse.

I get the feeling that the easiest way to make the mouse focus issues go away completely is to move the mouse pointer over to the (center of) a newly focused window if it is not over that window already. This is not ideal however because users might get confused about the location of the cursor.
Another option is to make focus changes from the mouse movement only trigger when a window/container is actually entered (pointer is actually moving from outside the container across the border). But this may get hard to reliably implement.

I'm not sure what would be the best way forward but I'm confident that some discussion here can point us in the right direction.

**Comment by SirCmpwn** [comment]
>Another option is to make focus changes from the mouse movement only trigger when a window/container is actually entered (pointer is actually moving from outside the container across the border). But this may get hard to reliably implement.

This might be a good idea
