### ISSUE TITLE
exec --xwayland-lazy [...]

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2830]
I like to start up some x clients like xrdb and autocutsel, but it would be cool to postpone these until xwayland is started lazily.

**Comment by RyanDwyer** [comment]
I implemented this locally but then discovered that Xwayland is started when launching most Wayland programs. Terminator, termite and gedit all start Xwayland before launching a Wayland window.

Given the above, and the fact that the end goal is to move away from Xwayland, I don't see much of a benefit in implementing this. Let me know if you think otherwise and I'll submit the PR.

**Comment by SirCmpwn** [comment]
Aight
