### ISSUE TITLE
[Question]: Moving focus between tiled windows focuses unexpected window

### ISSUE THREAD

**Issue by skaldesh** [swaywm/sway#2860]
Hey everyone, I have a short question:  
On a workspace, if have 4 tiled terminals open, arranged like this:  
```
---------- ----------
|    T1   ||    T2   |
---------- ----------
|    T3   ||    T4   |
---------- ----------
```
Now, when T4 has the focus and I move the focus to the left via my hotkey configured like this `bindsym $mod+$left focus left`, then T1 gets the focus. I expected T3 to get focus.  

Can this be configured otherwise? Is this the intended behaviour? 

EDIT: I just found out that it depends on whether T1 or T3 had focus, when moving to the right. If T1 had focus, then you will move from T4 -> T1 and T2 -> T1. If T3 had focus, then you will move from T4 -> T3 and T2 -> T3

**Comment by RyanDwyer** [comment]
It's intended. T1 and T3 are in a container, and when you `focus left` into that container we don't automatically set a new focus because you're moving into it from a perpendicular angle. It's how i3 works as well. You can tell in advance which container will be focused because it has `focus_inactive` styling.

It's not configurable within sway. It might be possible via a script that uses IPC, but would be somewhat complicated.

**Comment by skaldesh** [comment]
Ok, thanks for quick answer!
