### ISSUE TITLE
Window will be unkillable while it shows an autocompletion dropdown

### ISSUE THREAD

**Issue by nagisa** [swaywm/sway#2917]
In my sway config I have

```
    bindsym $mod+q kill
```

Now, when firefox window is displaying the autocompletion dropdown for entry into omnibar, as shown in the screenshot (actually scratch that, no idea how to take a screenshot), clicking `$mod+q` will do nothing.

The same happens with Entry/Entry Autocompletion demo from `gtk3-demo`.

---

sway version 1.0-beta.1-2-ga4d68358 (Oct 21 2018, branch 'master')

**Comment by RyanDwyer** [comment]
I actually think this is expected behaviour. When you open the autocomplete menu, we render focused styling on Firefox, and any key bindings (like `move right`) apply to Firefox as a whole. When you run `kill`, we ask the main Firefox window to close, which it rejects because the autocomplete surface is open. If the autocomplete surface was a floating view then it'd be a different story.

**Comment by SirCmpwn** [comment]
We might want to add a kill -f which sigterms, or kill -9 which sigkills

**Comment by SirCmpwn** [comment]
But that should be done separately.

**Comment by nagisa** [comment]
> we ask the main Firefox window to close, which it rejects because the autocomplete surface is open.

Ah, I suspected sway not sending a request to close at all (or sending it to a wrong window/surface. If it’s application-specific behaviour then it is all fine.
