### ISSUE TITLE
wayland compatible terminals don't start without xwayland

### ISSUE THREAD

**Issue by praetorian55** [swaywm/sway#2965]
Both gnome-terminal and terminator do not start without xwayland installed when called via exec in the config.  Interestingly enough, executing them from an ssh session after sway was already started does cause them to open on the display.  Both open as expected when xwayland is installed

I have also tried setting GDK_BACKEND=wayland via script, and when executing the terminal directly (GDK_BACKEND=wayland gnome-terminal)

_sway version 1.0-beta.1-31-ge33671fd (Oct 23 2018, branch 'master')_

[config.txt](https://github.com/swaywm/sway/files/2510957/config.txt)
[sway.log](https://github.com/swaywm/sway/files/2510954/sway.log)

**Comment by mteyssier** [comment]
It might actually explain why I couldn't start termite on the first try, just after installing sway.
Thanks for the report!

I uninstalled xwayland to run some tests (using termite instead of gnome-terminal or terminator):

Using sway:
- indeed termite doesn't start if called via exec in the config
- weston-terminal starts fine in sway!
- lauching termite from a weston-terminal: termite doesn't return and doesn't display any window.
- strace on termite: it is stuck on `connect(... "/tmp/.X11-unix/X0")`.

Using weston:
- both weston-terminal and termite are running fine.

The key is the `DISPLAY` environment variable.
It is not set by weston. (And is not set in your ssh session, right?)

You can try to unset the `DISPLAY` variable (via script?) and your terminal should run fine, something like:
`env -u DISPLAY termite` or just `unset DISPLAY` before.

Anyway the `DISPLAY` variable shouldn't be set, should it?

I just skimmed through the code but it looks like a wlroots issue, not  handling the error producing `[xwayland/xwayland.c:144] failed to exec Xwayland: No such file or directory` and thus not  unsetting `DISPLAY`.

After a quick glance at sway/server.c, currently sway would not properly handle this kind of error anyway (if compiled with `HAVE_XWAYLAND`).

**Comment by emersion** [comment]
We start Xwayland lazyly, which means we create the socket and set `DISPLAY` before starting Xwayland and start it only when an app connects.

Two things can be done:

* We should add a runtime config option to disable Xwayland
* Maybe we should check for Xwayland before starting lazily? (This would require handling `PATH`, not sure it's actually a good idea)

**Comment by praetorian55** [comment]
mteyssier - Thanks for the info.  I was able to start weston as well, which matches your findings.  Everything works fine with XWayland installed, I just thought wayland capable programs wouldn't/shouldn't need it

**Comment by emersion** [comment]
>I just thought wayland capable programs wouldn't/shouldn't need it

That's true. However GTK connects to X11 even if it uses Wayland for some reason =.=

**Comment by praetorian55** [comment]
> > I just thought wayland capable programs wouldn't/shouldn't need it
> 
> That's true. However GTK connects to X11 even if it uses Wayland for some reason =.=

Interesting - One thing I thought was weird is that when I had xwayland installed and started the terminals, graphical applications (like retroarch which is wayland compatible) run from the terminal would cause CPU usage on both xwayland and sway. 

if the GTK application connects to X11 and is successful, does that mean it uses X11 and not wayland?

**Comment by emersion** [comment]
>if the GTK application connects to X11 and is successful, does that mean it uses X11 and not wayland?

It uses Wayland, but still opens a connection to the X11 server ¯\_(ツ)_/¯

**Comment by mteyssier** [comment]
Thanks to both of you for the quick answers.

> We start Xwayland lazyly, which means we create the socket and set `DISPLAY` before starting Xwayland and start it only when an app connects.

Of course the lazy start. It all makes sense now. Hard to do anything at this stage if starting Xwayland fails.

> Two things can be done:
>     * We should add a runtime config option to disable Xwayland
>     * Maybe we should check for Xwayland before starting lazily? (This would require handling `PATH`, not sure it's actually a good idea)

I can't tell if something has to be done, but:
* Yes, I wondered at some point if there were a Xwayland option I should disable.
* Indeed checking for Xwayland before starting lazily might be clumsy.

> mteyssier - Thanks for the info. I was able to start weston as well, which matches your findings. Everything works fine with XWayland installed, I just thought wayland capable programs wouldn't/shouldn't need it

Thanks for testing it.

I thought the same, that's why I first installed sway without Xwayland and wasn't able to launch a Wayland capable terminal. I ended up installing Xwayland anyway.
And as you said everything works fine with Xwayland installed, it solved my issue without me noticing.

Moreover xwayland is in the dependency list of the Readme, isn't it?

**Comment by praetorian55** [comment]
> I thought the same, that's why I first installed sway without Xwayland and wasn't able to launch a Wayland capable terminal. I ended up installing Xwayland anyway.
> And as you said everything works fine with Xwayland installed, it solved my issue without me noticing.
> 
> Moreover xwayland is in the dependency list of the Readme, isn't it?

It definitely is - and things work when its installed.  I started experimenting with it when I saw xwayland using significant CPU (as much as sway) when running wayland capable apps, which I thought was odd - I did not see that when running the .15 branch - so I interpreted that as maybe the applications were using X instead of wayland.
