### ISSUE TITLE
Touchpad scrolling doesn't work

### ISSUE THREAD

**Issue by yory8** [swaywm/sway#2977]
- swaymsg version 1.0-beta.1-58-g2507a5e4 (Oct 25 2018, branch 'master')

(EDITED)
Scrolling in zathura doesn't work, but it's their bug (@mwenzkowski). In firefox and geany, actually it works, but doesn't honor settings: i set "edge", but it behaves as "two_finger".

```
input "2:14:ETPS/2_Elantech_TouchPad" {
    dwt enabled
    natural_scroll disabled
    scroll_method edge
}
```

Log (sway -d > log):

```
[Unhandled CSI] action='t', args=[22, 0, 0], intermediates=[]
[Unhandled CSI] action='t', args=[23, 0, 0], intermediates=[]
```

**Comment by mwenzkowski** [comment]
I think the issue with scrolling in zathura could be a bug in zathura itself and is not related to your Firefox problem. I tried zathura under sway and weston and was not able to scroll in both cases, but otherwise scrolling works for me. Moreover there is a [bug report](https://git.pwmt.org/pwmt/zathura/issues/48) for zathura mentioning the same behavior for Gnome on Wayland.

**Comment by yory8** [comment]
I edited the report to correct it.

**Comment by yory8** [comment]
I solved the issue: between the last time I used sway and now the name of the identifier has slightly changed (from TouchPad to Touchpad). It works now.
