### ISSUE TITLE
hidden statusbar remains hidden when using a "mode" keybinding

### ISSUE THREAD

**Issue by yory8** [swaywm/sway#3036]
sway version 1.0-beta.1-108-gb90af335 (Oct 30 2018, branch 'master')

Relevant config:

```
mode "resize" {
    bindsym Left resize shrink width 10 px or 10 ppt
    bindsym Down resize grow height 10 px or 10 ppt
    bindsym Up resize shrink height 10 px or 10 ppt
    bindsym Right resize grow width 10 px or 10 ppt
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+r mode "resize"

bar {
    position bottom
    mode hide
    status_command i3status
}
```

My bar is set to "hidden". 
In i3, it becomes visible when I enter into a "mode" (e.g. "resize") and remains visible until I leave the "mode". This is important because the info about the mode and about being in the mode is printed in the bar.
In sway, it remains hidden.

**Comment by ianyfan** [comment]
I originally didn't account for this because I thought it was a bug since it would disappear if you clicked the modifier, but I suppose it might in fact be a feature. However, this would change the logic for determining bar visibility a bit, though it wouldn't be too difficult. Unfortunately, I don't really have time to look into it currently.

Something else that might be worth checking is if an urgent bar is hidden after pressing the modifier too, i.e. an urgent workspace would make the bar appear, but does then pressing the modifier key cause it to hide again, or stay visible?

**Comment by yory8** [comment]
> but does then pressing the modifier key cause it to hide again, or stay visible?

Well, I'd say hide again; it shouldn't be a reason to keep it visible, if it was hidden by default?

**Comment by thibran** [comment]
I use a swaybar mode-dialog to display different options like "suspend, reboot...". When pressing the swaybar modifier key to display the options, I can no longer select them because now I'm pressing `$mod+[some-other-key]`.
