### ISSUE TITLE
Outputs in negative position space results in xwayland containers not clickable

### ISSUE THREAD

**Issue by wernerb** [swaywm/sway#3060]
Sway version:  1.0-beta.1-130-g6297b757

My case is that I don't like to switch around configs at different places when using multiple monitors. So I put each output in the config and make sure that the main display position (eDP-1 in my case (the lpatop screen)) can accommodate all the outputs.

When using the following config, the cursor moves around ok but mouse clicks don't do anything in xwayland applications (tested with firefox/albert)

```
#  Arrangement visualized:
#                                          WorkOffice(0,-1440), WorkClient(0,-1050)
#     HomeLeft(-5120,0), HomeRight(-2560,0), eDP-1(0,0)

#laptop display
output eDP-1 (3480x2160, but scaled to 1920x1080) {
  scale 2 
  position 0 0
}
#work client (crappy 1680x1050)
output 'Lenovo Group Limited LT2252p Wide 6V8ABBP1' {
  position 0 -1050
}
# work office (2560x1140)
output 'Dell Inc. DELL U2715H GH85D7B70JSS' {
  position 0 -1440
}
# home right (2560x1440)
output DP-3 {
  position -2560 0
}
# home left 
output DP-4 {
  position -5120 0
}
```

For reference this layout is effectively the same but has no negative position and works fine:

```
#  Arrangement visualized:
#                                            WorkOffice(5120,0), WorkClient(512,390)
#     HomeLeft(0,1440), HomeRight(2560,1440), eDP-1(5120,1440)

#laptop display
output eDP-1 (3480x2160, but scaled to 1920x1080) {
  scale 2 
  position 5120 1440
}
#work client (crappy 1680x1050)
output 'Lenovo Group Limited LT2252p Wide 6V8ABBP1' {
  position 5120 390
}
# work office (2560x1140)
output 'Dell Inc. DELL U2715H GH85D7B70JSS' {
  position 5120 0
}
# home right (2560x1440)
output DP-3 {
  position 2560 1440
}
# home left 
output DP-4 {
  position 0 1440
}
```

**Comment by SirCmpwn** [comment]
This is a known Xwayland bug.

**Comment by ianyfan** [comment]
https://github.com/swaywm/wlroots/issues/958

**Comment by neon64** [comment]
I understand this isn't an issue with sway or wlroots per-se. However, I just spent multiple hours trying to understand why I was experiencing this issue, thinking it was to do with buggy nouveau/intel multi-GPU support, when in fact it was just how I had positioned my screens. Somehow searching for 'xwayland missing mouse events' and similar terms in the sway and wlroots issue trackers couldn't find this issue.

Now to my question - would it be a good idea if I made a PR which displayed some sort of 'warning message' when trying to set a negative output positions, letting the user know that this Xwayland bug exists (although according to the freedesktop.org issue tracker it is soon to be fixed), so that they don't also spend multiple hours as well to find the root cause of this issue.

**Comment by TheAvidDev** [comment]
> although according to the freedesktop.org issue tracker it is soon to be fixed

Just regarding this, it doesn't look like this can ever get fixed, according to [this comment](https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/395#note_555613).
