### ISSUE TITLE
configuration reloads twice

### ISSUE THREAD

**Issue by surrealpie** [swaywm/sway#3072]
```
swaymsg -t get_version
sway version 1.0-beta.1-110-gd3a62633 (Oct 30 2018, branch 'master')
```

`sway -d 2> ~/sway.log`
https://ptpb.pw/5DHd

configuration file:
https://ptpb.pw/zM3M

behavior:
i launched sway, and only did one reload before saving the log, and i got this:
```

cat sway.log.bak | grep "Performing configuration file reload"
2018-11-05 00:56:41 - [sway/config.c:392] Performing configuration file reload
2018-11-05 00:56:41 - [sway/config.c:392] Performing configuration file reload
```
```

cat sway.log.bak  | grep "Executing printf"
2018-11-05 00:56:27 - [sway/commands/exec_always.c:44] Executing printf '1
2018-11-05 00:56:41 - [sway/commands/exec_always.c:44] Executing printf '1
2018-11-05 00:56:41 - [sway/commands/exec_always.c:44] Executing printf '1
```

```
cat ~/test
1
1
1
```

**Comment by martinetd** [comment]
Looks like that since 82423991a8512ab97fbc41d1e190e709c58bc346, the reload is called twice:
 - once when you run the command with a "validating" flag; basically checks for syntax errors and fail the command properly if there's a problem
 - once again "for real" in an idle event a bit later.

It looks like each command have to manually check for the `config->validating` flag themselves, and `exec_always` doesn't - that'd be an easy fix, and although I don't really like the design I don't see much way around this.
Feel free to submit a PR to add the check, and you can reword the "Performing configuration file reload" message on the first pass while you're at it to be less confusing :)
