### ISSUE TITLE
Displaying pop-ups as floating windows.

### ISSUE THREAD

**Issue by fredefox** [swaywm/sway#3095]
$ lsmod | grep nvidia | wc -l
    0

I hope I am welcome :S

    $ swaymsg -t get_version
    sway version 1.0-alpha.6-335-ga41b77ef (Oct 20 2018, branch 'master')

This is a feature request so I will forego the other formalities you asked for. In `i3` some windows are opened as pop-ups. That is to say, they are openened in the "floating" mode. I am not aware how this works technically I also don't know if it works for some programs under sway. It does not work with `zenity`.

Minimal repro:

    $ zenity --question

Desired behaviour: A small floating window is opened.

Actual behaviour: A new tiled window is displayed.

Is this something that you have support for that may be a problem with my installation? I recently build this from source, so I may have messed something up. Floating windows do work for me though.

**Comment by emersion** [comment]
In i3 zenity uses X11, which sets the window as a dialog window. In sway it uses Wayland which has no "window type". So we can't do anything about it.

Note that if zenity was making the window non-resizable, we would make it floating.

**Comment by emersion** [comment]
You could probably use criteria to make zenity windows floating by default.

**Comment by fredefox** [comment]
Thanks for the clarification! So Wayland has nothing similar to "window type"? Seems like a huge design oversight to me...

**Comment by emersion** [comment]
Window types are essentially useless. It's pretty uncommon to have dialog windows without a parent. In this particular case I think zenity should make its dialog non-resizable.

**Comment by fredefox** [comment]
I see. Thank you!

**Comment by ascent12** [comment]
>So Wayland has nothing similar to "window type"?

Wayland has shells, which is "kind-of" like a window type, but not really the same thing in an X11 sense.

**Comment by b0o** [comment]
> Window types are essentially useless. It's pretty uncommon to have dialog windows without a parent. In this particular case I think zenity should make its dialog non-resizable.

So, it seems nearly impossible to float a pop-up window created by Chrome or Firefox when either app is using its Wayland backend. 

I came up with [a super hacky workaround](https://gist.github.com/b0o/f00de53aa44ff53b39f997d83b7b5585) - a userscript that tries to detect pop-up windows based on the `window.titlebar.visible` or `window.menubar.visible` properties, and if either one is `false` I prepend a well-known string to the window title. I check for this string inside my Sway config and float matching windows. But, let's be honest: :vomiting_face:. Is there really no better way?

**Comment by fuzunspm** [comment]
could you find a better way?

**Comment by celebilercem** [comment]
I installed [mako](https://github.com/emersion/mako) and it works fine with Sway and Firefox.

**Comment by jpetazzo** [comment]
Just to clarify (in case someone else stumbles upon this): after installing `mako`, you probably need to restart Firefox. There may or may not be other steps to do (I fiddled around with `makoctl`, made sure `mako` was running, upgraded `libnotify`... And it's finally when I restarted Firefox that notifications worked correctly!)

I suppose that Firefox checks if there is a notification service registered on D-BUS.
- If there is one, it will use it (and display neat little desktop notifications).
- If there is none, it will fallback to display notifications directly, but it does so in a hackish way (which is why we end up with these nasty windows that required ugly hacks).

I suppose (but your guess is as good as mine!) that Firefox checks once on start-up if there is a notification service available (and that it's why I had to restart Firefox for things to start working).

**Comment by icy-comet** [comment]
Sorry, to comment on such an old issue.

However, Zenity dialogues were indeed marked as non-resizable with [this commit](https://gitlab.gnome.org/GNOME/zenity/-/commit/782cd3abc3278ed9afa4393cd22641e56731e09b) and the windows now open in floating mode by default.

Just putting this here for google :)
