### ISSUE TITLE
Sway unable to drop root if installed to /usr/bin on Gentoo

### ISSUE THREAD

**Issue by samchelini** [swaywm/sway#3247]
Sway doesn't launch if installed to /usr/bin/sway (installed using emerge on Gentoo)
Copying /usr/bin/sway to /usr/local/bin/sway works perfectly

It appears to be unable to drop root for some reason when it's in the /usr/bin directory. I get the same behavior on beta1. 0.15.2 works fine in /usr/bin

$ swaymsg -t get_version
sway version 1.0-beta.2

Attached sway.txt is output of /usr/bin/sway -d 2> ~/sway.txt
sway2.txt is output of /usr/local/bin/sway -d 2> ~/sway2.txt
Also attached output of ls -la of both files

[sway.txt](https://github.com/swaywm/sway/files/2641492/sway.txt)
[sway2.txt](https://github.com/swaywm/sway/files/2641496/sway2.txt)
[ls.txt](https://github.com/swaywm/sway/files/2641520/ls.txt)

**Comment by jpsamaroo** [comment]
What USE flags do you have set? Is +filecaps enabled? Are you on systemd or openrc?

**Comment by samchelini** [comment]
Below are my USE flags for sway and wlroots. Both have the filecaps USE flag. I am on openrc. 
dev-libs/sway-1.0_beta2 X filecaps pam swaybar swaybg swayidle swaylock swaymsg swaynag tray wallpapers

dev-libs/wlroots-0.2 X filecaps

**Comment by samchelini** [comment]
This log file might be more helpful. Before I had set "chmod a+s /usr/bin/sway" manually after install because sway would freeze my computer and I have to reboot in order to fix it. That might be why it's unable to drop root. This log shows some permission errors just before my computer freezes, without "chmod a+s /usr/bin/sway".

[sway.txt](https://github.com/swaywm/sway/files/2642010/sway.txt)

**Comment by SpeedJack** [comment]
> Before I had set "chmod a+s /usr/bin/sway" manually after install

In Gentoo you should never have to do this. The ebuild should take care of everything.
With `filecaps` enabled, the ebuild should try to set the CAP_SYS_ADMIN capability on the binary, and if something goes wrong (eg. the system does not support capabilities) it should set the SUID bit.
If you run `getcap /usr/bin/sway` you should see the CAP_SYS_ADMIN set. This means that you don't have to set SUID or run Sway as root. If, in this case, the computer freezes, the problem is something else.
From the logfile, Sway seems unable to read input devices. Emerge, at the end of Sway installation, should have printed this message:
`You must be in the input group to allow sway to access input devices!`
So you must add your user to the input group: `gpasswd -a input <username>`.
If you use ConsoleKit2 (instead of systemd/elogind), you also have to run sway with `exec ck-launch-session sway`, as advised by emerge at the end of installation.

**Comment by samchelini** [comment]
Thanks SpeedJack, I emerged sway again and sure enough it said I need to be in the input group. Added myself to the input group and it worked
