### ISSUE TITLE
cmd_split does not flatten tree

### ISSUE THREAD

**Issue by 7415963987456321** [swaywm/sway#3259]
**Steps to reproduce:** 
I. Open two terminals
II. Tab or stack them
III. Attempt to use horizontal split ($mod+b)
IIII. Title of the tab changes to something strange.

**Picture of what happens:**
https://imgur.com/a/WrzqNvG

**Debug log:**
 https://gist.github.com/7415963987456321/859c5b76ab0c9b992be2fa1092ba0a93

**Version:**
Latest master, also happens on older versions, I meant to report this bug a while ago.

**Config:**
https://gist.github.com/7415963987456321/809f04a30aac61ab12504d8aa0e2111f

**Comment by 7415963987456321** [comment]
Doing this repeatedly and switching between tabbing and stacking I am able to make this:
https://imgur.com/a/ctRNLCT

Thats only two terminals.

**Comment by RedSoxFan** [comment]
I would recommend changing your `repeat_rate` (or `repeat_delay`). In your original debug log, `splith` is being executed from binding 8 times within 2 seconds (probably shorter, but we don't log fractions of a second).

```
2018-12-05 17:12:13 - [sway/sway/commands/bind.c:293] running command for binding: splith
2018-12-05 17:12:13 - [sway/sway/commands/bind.c:293] running command for binding: splith
2018-12-05 17:12:13 - [sway/sway/commands/bind.c:293] running command for binding: splith
2018-12-05 17:12:14 - [sway/sway/commands/bind.c:293] running command for binding: splith
2018-12-05 17:12:14 - [sway/sway/commands/bind.c:293] running command for binding: splith
2018-12-05 17:12:14 - [sway/sway/commands/bind.c:293] running command for binding: splith
2018-12-05 17:12:14 - [sway/sway/commands/bind.c:293] running command for binding: splith
2018-12-05 17:12:14 - [sway/sway/commands/bind.c:293] running command for binding: splith
```

**Comment by RedSoxFan** [comment]
In that case, it appears to be working as intended. For tabs and stacks, the title is a representation of the contents. `H[` is a horizontal split, `V[` is a vertical split, `T[` is a tabbed container, and `S[` is a stacked container.

As for the `(null)`, that is where the application is identified. For native wayland views, `app_id` is used and for xwayland views, `instance` is used. However, alacritty does not set its `app_id` so `(null)` is shown.

The lag is probably just sway generating the representation string, which will take longer as the tree gets larger.

**Comment by 7415963987456321** [comment]
Hmm, so you're supposed to be able to do this indefinitely? Don't really understand how a container can be H[H[H[H[H[H[H[H... and so forth. Doesn't really make sense that it opens a bunch of 'tabs' that contain nothing.

**Comment by RedSoxFan** [comment]
A single container does not have multiple layouts, but it can have unlimited (in theory anyway; restricted by memory) descendants. Containers are not directly shown on the screen (aside from the tab and stack user interfaces). Only views (application windows) are shown.

Basically what happens when you run `splith` is the selected view or container gets wrapped in a container with a horizontal layout with a single child. Doing it repeatively will generate a horizontal split with one child that itself is a horizontal split with one child (and repeat) until you get to the application window.

Whether this is useful or not depends on the situation, but it is possible. When a user manually splits a container, it is expected they know what they are doing and will not be flattened.

**Comment by progandy** [comment]
Just to note, as far as I can see i3 does flatten split containers.

**Comment by RedSoxFan** [comment]
> Just to note, as far as I can see i3 does flatten split containers.

Actually, I just confirmed that you are correct. So there is no issue with the name being malformed, but the layout should be flattened. For some reason, I thought that was intentional. Sorry about that.
