### ISSUE TITLE
DP MST hot-plugging needs work

### ISSUE THREAD

**Issue by jeremejevs** [swaywm/sway#3269]
Sway: `1.0-beta.2-22-g0c3f0dfd (Dec  8 2018, branch 'master')`
Linux: `4.19.4`

[Logs](https://gist.github.com/jeremejevs/71f0137d938774dbc0f10321c76774ae), [backtrace](https://gist.github.com/jeremejevs/618f0a5c643a7a884b762658f6b434ec), [config](https://gist.github.com/jeremejevs/67563d29cc35ff080f8b62997ee3c2e9).

Hardware arrangement: a laptop with a TB3 port, UHD 620 GPU, USB-C-to-DP adapter, Dell U2717D plugged into the adapter, another Dell U2717D plugged into the first U2717D, MST enabled on both.

This setup works somewhat fine if I boot with the monitors connected and never unplug or turn them off, but all bets are off if I want to grab my laptop for a meeting or suspend at home and resume elsewhere.

If I have Kanshi or `output * bg ...`, a segfault is basically guaranteed within 2-3 plugs/unplugs. However, even with a default barebones config, with `output * bg ...` and Swaybar disabled, as seen in the gists I've linked, Sway crashes after 10-20 plugs/unplugs (and the monitors, including laptop's display, remain disabled sometimes randomly). Reproducible by just connecting and disconnecting the PC-to-first-monitor DP cable every 10 or so seconds.

I'm unable to get Sway to crash in non-MST mode, even with Kanshi chaos monkey in the background.

Admittedly, X and i3 were no better (i3, as I remember, wouldn't crash, but would just stop displaying anything), but they get a pass for being of old age.

Could be that hot-plugging two monitors at once is the problem, not MST. This could also be a Linux/driver thing. Need help in narrowing this down either way.

Just in case, I'll have this setup only for another few weeks, won't be able to do any tests afterwards.

**Edit:** Got Sway to crash/hang without MST. [Coredump](https://gist.github.com/jeremejevs/9cd22250eb1e942817a7c2ff7f60c330), [logs](https://gist.github.com/jeremejevs/7ab3892b2f931679c7b9ee24e4e23888), same config, running Chromium. But looks like that's something else, maybe XWayland-related.

**Comment by RedSoxFan** [comment]
The issue lies in wlroots. `DP-6` is found and disappears within a single execution of `scan_drm_connectors`. At the end of the function, wlroots is requesting a modeset for the output despite it no longer existing. When sway attempts to modeset the output, it causes a segfault.  Can you please open the issue in the wlroots repo?

There are also a lot of occurrences of a connector name (usually `DP-5` or `DP-6`) appearing twice in the list of connectors. This looks like it could be another issue, but may be fine. Hopefully, someone more knowledgeable on the topic can chime in on that.

As for the crash without MST, that looks like a different issue. Could you provide the full backtrace?

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/wlroots/pull/1426?

**Comment by jeremejevs** [comment]
Sorry, never got a chance to test, and I don't have my old setup anymore, unfortunately. I'll close this, since this appears to be an edge case that hasn't affected anybody but me in a whole month.
