### ISSUE TITLE
Click ignored while holding other mouse button

### ISSUE THREAD

**Issue by junglerobba** [swaywm/sway#3539]
sway version: 1.0-beta.2-291-g5cb3d476 (Jan 30 2019, branch 'master')

I noticed this while testing Warframe with pointer-constraints and relative-pointer merged (which works great by the way) since you hold right click to aim and then cannot shoot with left click. But this is an issue anywhere even without this merged. Easiest way to test is to hold right click anywhere you can get a dropdown menu and then try to click an option with right click still held down. In other environments (i3 / GNOME Wayland) this would work, whereas in sway it doesn't.

**Comment by RyanDwyer** [comment]
This is happening because the `down` seat operation overrides most of the behaviour in `dispatch_cursor_button`. If the seat operation is active, the routine returns fairly early and doesn't send button events to the surface.

I'm not sure what the best course of action is yet. Removing the `down` operation entirely might be best, but we'd have to track which node was active when any button presses started so that we can continue to send motion events to it, even if the cursor is no longer over that surface (eg. for when you operate a scrollbar and move the cursor off the surface while scrolling).

Another option would involve making `dispatch_cursor_button` not return early for the `down` seat operation, but this is a hacky solution.

Yet another option is to add a `handle_button` callback to seat operations, then make the `down` operation use this handler to send the button events to the surface. I'm not a fan of this idea.

At this stage I suspect removing the `down` operation is best.

**Comment by emersion** [comment]
Related to https://github.com/swaywm/wlroots/issues/1506

**Comment by Laaas** [comment]
@emersion how would you implement this with cursor grabs?

**Comment by emersion** [comment]
Let `button` events through, until the button that started the grab is released?
