### ISSUE TITLE
Segfaults via include command.

### ISSUE THREAD

**Issue by c-edw** [swaywm/sway#3565]
I am fuzzing various config commands and found some strings that can cause segfaults:

```
include '() { 0; }; touch /tmp/blns.shellshock1.fail;''
include '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }'
include '<<< %s(un='%s') = %u'
```

Backtrace is [here](https://gist.github.com/c-edw/4d19ff0c20a0c2007fae546b9ceb60d9).

**Comment by c-edw** [comment]
@emersion Would it be better to open a new issue for more segfaults like this, or reopen this issue and report them here? I don't want to spam too many issues.

**Comment by emersion** [comment]
One issue per stack trace would be okay. Since each stack trace indicates a different bug, I think it makes more sense.

One meta issue with a checklist of crashes would be fine as well, but would make it more difficult to add new crashes as you find them (PRs will be sent with "Fixes #XXX" in their description, but may not fully fix the meta-issue when merged).

**Comment by c-edw** [comment]
Agreed. Alright, thanks.
