### ISSUE TITLE
I've a broken middle mouse button, how i can remap it on another mouse button?

### ISSUE THREAD

**Issue by RorraVox** [swaywm/sway#3611]
sway version 1.0-rc1-8-ga1a99421 (Feb  4 2019, branch 'master')
I've a broken middle mouse button, how i can remap it on another mouse button?
i've to use libinput or udev? or there is a way to do such thing using bindsym in config file?
I've a mouse with other 2 secondary button and i get pressed button with:
libinput list-devices
libinput debug-events

**Comment by RedSoxFan** [comment]
You should be able to bind the command `seat seat0 cursor press BTN_MIDDLE; seat seat0 cursor release BTN_MIDDLE` (if you are attaching the device to a different seat, use that instead of seat0) to whatever button you want. If you are using a mouse button, you will want to use the `--whole-window` flag for the bindsym

**Comment by RorraVox** [comment]
as you said IT WORKS:
```
bindsym --whole-window BTN_SIDE seat seat0 cursor press BTN_MIDDLE; seat seat0 cursor release BTN_MIDDLE
```

**Comment by xhalo32** [comment]
I had no success using this workaround. Please see [issue 4201](https://github.com/swaywm/sway/issues/4201) for the details.
