### ISSUE TITLE
Add `hide_lone_tabs` to hide titlebar when there is only one tab

### ISSUE THREAD

**Issue by avrelaun** [swaywm/sway#3663]
This is a duplicate of https://github.com/swaywm/sway/issues/2987, which was closed even though the problem is still here on latest sway (RC2).

This one is a bug and a regression from i3 behaviour.

**Required config:**

new_window pixel 2
new_float pixel 2
workspace_layout default
hide_edge_borders smart (this one is probably not be related)

**Current behaviour:**

    * Open a window on an empty workspace (titlebar is hidden)

    * Open a second window on the same workspace (titlebars are visible)

    * Put them into stack or tabbed (titlebars are visible)

    * Close one window, leaving only one -> **titlebar is visible but should be hidden**

When there is only one window in a workspace, it should have only one container (previous parents should be removed) and title bar should be hidden if configured so.

**Comment by RedSoxFan** [comment]
It looks like it was decided to diverge from i3's behavior on this due to popular demand. See https://github.com/swaywm/sway/pull/3031

There is mention in that thread about adding an `hide_lone_tabs` config option though, which does not appear to be followed up upon so I'll turn this issue into the tracker for it.

**Comment by avrelaun** [comment]
Sure, an option would be great, for those of us wanting the old i3 behaviour.
