### ISSUE TITLE
Build path in binary makes it unreproducible

### ISSUE THREAD

**Issue by bschacht** [swaywm/sway#3680]
Since 1211a81aad18bbc4d9e8fb9973238ad8e7e1f688 the _sway_strip_path function uses SWAY_SRC_DIR to strip the build path from the filename. This makes the build unreproducible. There is a note about this in https://github.com/swaywm/sway/blob/d168d65f2c0297bf5662c0f48f5f53705e54a376/include/log.h#L36 but i didn't find an issue for that and TODOs in the code tend to get forgotten.

**Comment by mstoeckl** [comment]
I wrote that TODO. A workaround with very recent GCC (and, [possibly in the future](https://reviews.llvm.org/D49466), clang) is to use `-fmacro-prefix-map` to perform the path stripping. This makes for reasonably simple patches ([repro_sway.patch.txt](https://github.com/swaywm/sway/files/2866567/repro_sway.patch.txt), [repro_wlroots.patch.txt](https://github.com/swaywm/sway/files/2866568/repro_wlroots.patch.txt)), but, since I sometimes use computers with gcc 4.5.x, does not solve the problem as cleanly as would a build system passing in canonical names to the preprocessor.

**Comment by ddevault** [comment]
-1, I'd prefer to find a solution which isn't as reliant on compiler-specific behavior

**Comment by progandy** [comment]
It is possible to strip __FILE__ to the basename during compilation with long and ugly macros like this:
```
#define STRIPPATH(s)\
    (sizeof(s) > 2 && (s)[sizeof(s)-2] == '/' ? (s) + sizeof(s) - 1 : \
    sizeof(s) > 3 && (s)[sizeof(s)-3] == '/' ? (s) + sizeof(s) - 2 : \
...
    sizeof(s) > 20 && (s)[sizeof(s)-20] == '/' ? (s) + sizeof(s) - 19 : \
    sizeof(s) > 21 && (s)[sizeof(s)-21] == '/' ? (s) + sizeof(s) - 20 : (s))

#define __JUSTFILE__ STRIPPATH(__FILE__)
```
https://stackoverflow.com/a/41367919

**Comment by ddevault** [comment]
>Or if all occurences of `__FILE__` are below the source path, then it is possible to determine the path length in meson and set a definition like `LENGTH_OF_SOURCE_PATH` for the compiler. In the code, then use

This seems reasonable to me

**Comment by progandy** [comment]
By the way, to get the length of a string in bytes you need to do this in meson:
```run_command('sh', '-c', 'printf "%s" "$1" | wc -c', 'bytes', string_to_test)```

**Comment by mstoeckl** [comment]
I tried: 

    // strip prefix from __FILE__, leaving the path relative to the project root
    #define _SWAY_FILENAME (__FILE__ + SWAY_SRC_DIR_LENGTH)

    #define sway_log(verb, fmt, ...) \
    	_sway_log(verb, "[%s:%d] " fmt, _SWAY_FILENAME, __LINE__, ##__VA_ARGS__)

    #define sway_vlog(verb, fmt, args) \
    	_sway_vlog(verb, "[%s:%d] " fmt, _SWAY_FILENAME, __LINE__, args)

    #define sway_log_errno(verb, fmt, ...) \
    	sway_log(verb, fmt ": %s", ##__VA_ARGS__, strerror(errno))

    #define sway_abort(FMT, ...) \
    	_sway_abort("[%s:%d] " FMT, _SWAY_FILENAME, __LINE__, ##__VA_ARGS__)

    #define sway_assert(COND, FMT, ...) \
    	_sway_assert(COND, "[%s:%d] %s:" FMT, _SWAY_FILENAME, __LINE__, __PRETTY_FUNCTION__, ##__VA_ARGS__)

in `include/log.h`, and 

    length_finder = 'import os.path; print(len(os.path.join(os.path.relpath(\'@0@\', \'@1@\'),\'\')))'
    rel_src_dir_length = run_command('python3', '-c',
	    length_finder.format(meson.source_root(), meson.build_root())).stdout().strip()

followed by

    		'-DSWAY_SRC_DIR_LENGTH=@0@'.format(rel_src_dir_length),

in `meson.build`. 

Testing with `strings`, the above trick doesn't work: GCC doesn't optimize the string constants away. The change still improves over the current situation, as it lets us drop `_sway_strip_path` and its expensive call to `strstr`.

**Comment by progandy** [comment]
Then the only way I know to get rid of the build path will be compiler extensions or not using ```__FILE__``` at all. In that case each file would have to set their own name to a standardized macro name or all log functions need a manual filename parameter.

**Comment by ascent12** [comment]
I'm not opposed to `-fmacro-prefix-map`, since it's a compile option that can be tested for and doesn't affect the validity of our code. It'll still be standard uses of `__FILE__` in the source code itself, which itself is rife with implementation-defined behaviour. I wouldn't consider it any worse than `-Wno-unused-parameter`.
Worst case is that someone is using a weird/old compiler, and their log statements will be longer.

**Comment by emersion** [comment]
Yeah, we can always fallback to something else if a flag isn't available. BTW, we should use `cc.get_supported_arguments` for things like `-Wno-unused-parameter`.

**Comment by ddevault** [comment]
Okay, +1 to `-fmacro-prefix-map` so long as it doesn't break on a compiler which doesn't support it.
