### ISSUE TITLE
strange behavior of focus right

### ISSUE THREAD

**Issue by ya-isakov** [swaywm/sway#3684]
Hello! On sway 1.0-rc1-45-gfb4f2928, 'focus right' doesn't loop, but 'focus left' loops as it should. After last tab on output, 'focus right' moves to another output, but doesn't moves again to first output. 'focus left' properly loops over tabs of one output.
Probably a dup of #3030, but it is not fixed, and I cannot reopen old bug, so here is a new one

**Comment by RedSoxFan** [comment]
> Probably a dup of #3030 

That was for `focus output right` not `focus right` so this is not a duplicate.

However, the currently implemented behavior matches i3's behavior. Instead of wrapping over the outputs, `focus left/right` will wrap the other side of the current output (when there is no output in that direction), which has no effect when the workspace is empty or there is only one descendant.

**Comment by ya-isakov** [comment]
Actually, it has an effect, it deactivates current workspace, even if there is no workspaces on "right" output

**Comment by RedSoxFan** [comment]
> even if there are no workspaces on "right" output

An output always has at least one workspace

**Comment by RedSoxFan** [comment]
> Actually, it has an effect, it deactivates current workspace, even if there are no workspaces on "right" output

Can you give a more detailed explanation on what the issue is? In my testing, sway's behavior appears to be identical to i3's

**Comment by ya-isakov** [comment]
I've checked with i3, and yes, it's the same behaviour, so I'm closing this bug. It is not quite intuitive for me, but at least it's a not a bug, definitely.
