### ISSUE TITLE
Background is gray, not wallpaper (regression)

### ISSUE THREAD

**Issue by harrisonthorne** [swaywm/sway#3776]
* Sway Version: `sway version 1.0-rc1-118-g9032be4f (Feb 25 2019, branch 'master')`

This bug is a regression from `sway version 1.0-beta.2-279-g783fadab (Jan 27 2019, branch 'master')`

* Debug Log: [here](https://gist.github.com/harrisonthorne/1feccd9a18c7d6b16e9c6e4a7245ab44)
* I restart sway using the following script, which uses wpgtk to set the wallpaper. Wallpaper was working with the aforementioned version of sway above.

```
#!/usr/bin/env bash

wpg -m # generate new colors
cat ~/.config/wpg/sequences # apply new colors

# ...other irrelevant stuff...

swaymsg reload # restart sway
```

**Comment by ddevault** [comment]
I think this is the source of the error:

```
2019-02-25 19:43:41 - [sway/sway/config/output.c:128] Adding output * config
2019-02-25 19:43:41 - [sway/sway/config/output.c:136] Config stored for output * (enabled: -1) (-1x-1@-1.000000Hz position -1,-1 scale -1.000000 transform -1) (bg (null) (null)) (dpms 0)
```

I guess your script is applying the wallpaper via IPC, rather than having it specified in your config - but you have `output *` in your config. When you run `reload`, it's going to re-apply `output *`, overwriting all of your output configs. You need to re-run `output <id> bg <path> <mode>` after this happens.

**Comment by harrisonthorne** [comment]
Solved!
