### ISSUE TITLE
Most key bindings do not work with default configuration

### ISSUE THREAD

**Issue by paulmenzel** [swaywm/sway#3846]
With sway 1.0-rc3 from Debian Sid/unstable and the default configuration, I am unable to open a terminal. The only working key combinations are Alt + number to switch the tags(?), and windows key (Mod4) + r, which lets the button(?) *resize* appear in the top bar.

First I thought it’s related to Debian bug report [924063][1], but installing urxvt or changing the binding to x-terminal-emulator did not change anything. Additionally, suckless-tools were already installed on my system.

Can you see something in the [sway.log](https://github.com/swaywm/sway/files/2948838/sway.log), shedding light into the problem?

[1]: https://bugs.debian.org/924063
    "sway: Configure x-terminal-emulator as $term or add urxvt (and suckless-tools) to recommends and fix keyboard layout."

**Comment by RedSoxFan** [comment]
> button(?) resize

It's just an indicator to tell you want binding mode you are in and is not a button. Also, that doesn't appear to be included in the attached log.

> Alt + number to switch

The default modifier is Mod4. There are no bindings in the default config (which that log does appear to be using) with Mod1 (Alt). Were you trying to use Alt/Mod1 when trying to use the bindings and just happened to fat finger Mod4 for the successful ones? If so, use Mod4 or create a user config with Mod1 as your modifier

If you are trying to use Mod4 and they aren't working, was Mod4+Return pressed during that log? It doesn't appear to be registering and since you said Mod4+r is working and isn't in the log, I'm wondering if that is an incomplete log. If it is incomplete and Mod4+Return wasn't presssed, do you have xwayland installed? Can you try a terminal with wayland support such as termite or gnome-terminal?

**Comment by paulmenzel** [comment]
> > Alt + number to switch
> 
> The default modifier is Mod4. There are no bindings in the default config (which that log does appear to be using) with Mod1 (Alt). Were you trying to use Alt/Mod1 when trying to use the bindings and just happened to fat finger Mod4 for the successful ones? If so, use Mod4 or create a user config with Mod1 as your modifier
> 
> If you are trying to use Mod4 and they aren't working, was Mod4+Return pressed during that log? It doesn't appear to be registering and since you said Mod4+r is working and isn't in the log, I'm wondering if that is an incomplete log. If it is incomplete and Mod4+Return wasn't presssed, do you have xwayland installed? Can you try a terminal with wayland support such as termite or gnome-terminal?

Sorry for the confusion. Here is an updated [sway.log](https://github.com/swaywm/sway/files/2949365/sway.log).

I created this issue on a different computer, and misremembered. It was indeed the Mod4 key, and *not* Alt.

You were right, that the package *xwayland* was not installed. So in hindsight, it makes sense, that it did not work. So, with `weston-terminal` configured as the terminal, Mod4 + Return works now, and Mod4 + Shift + e also worked before, I just did not know about it.

Thank you very much for your help.
