### ISSUE TITLE
multiple swaynag exit calls stacks multiple displays

### ISSUE THREAD

**Issue by CaptainBloodz** [swaywm/sway#3901]
Multiple calls to exit scenari, e.g. via multiple $mod+Shift+E, generate one different display, one for each call, stacked vertically.
When exit is confirmed, it is not a big deal, but if deciding to cancel, all displays must be manually closed.

Wouldn't it be nice to avoid these multiple stacked displays?

Thks 4 ur attention.

**Comment by RedSoxFan** [comment]
It is possible to run multiple swaynag instances that have nothing to do with each other. Furthermore, sway does not care what you are executing via bindings and will not kill something you spawn with a binding because you chose to execute it again.

If you want it to be single instance, wrap the swaynag command in a script that creates a lock file on creation, removes the lock file on exit, and doesn't spawn another instance if the lock file exists.
