### ISSUE TITLE
New auto raise window behavior?

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#3925]
When I hover over the titlebar the window/container is automatically raised. Is this an intentional change? Is there a way to disable?

`sway version 1.0-rc1-187-g0327c999 (Mar 17 2019, branch 'master')`

**Comment by RyanDwyer** [comment]
There was a commit recently (7b9ae42331e49fea0f566fa7592855dee5da1991) which probably affected this. It's not intentional.

However, I'm struggling to find any functional difference between master and 73605dac2ae18e2ca84a74da895c4098a1bee6f8 which is a couple of commits prior to 7b9ae42331e49fea0f566fa7592855dee5da1991. In both commits, hovering a tab title with `focus_follows_mouse` brings focus to that window. Can you please write steps to reproduce and confirm which commit it works properly in?

**Comment by JonnyMako** [comment]
@RyanDwyer That is exactly it. Bad commit: 7b9ae42331e49fea0f566fa7592855dee5da1991. Good commit: fb3475e291ea6be94131c19fdc006e9ad873ea5f

**Comment by RyanDwyer** [comment]
I'm doing the following:

* Using commit fb3475e
* Have `focus_follows_mouse yes` in config
* Open two views
* `layout tabbed`
* Move the cursor over the unfocused tab

When I do that, the unfocused view is focused. From what you're saying, I should have to click to focus it. And this is the commit you said was good.

Can you please clarify the steps to reproduce?

**Comment by JonnyMako** [comment]
1, Config does not have `focus_follows_mouse` line.
2, Open layout T[ViewA, ViewB]
3, With fb3475e291ea6be94131c19fdc006e9ad873ea5f moving the cursor over the container only focuses window that is in front. Even if I hover over the title bars of the two windows only the one on top remains focused. I have to click the title bar of the window that is behind to raise it.
4, With 7b9ae42331e49fea0f566fa7592855dee5da1991, hovering over the title bars of the two windows raises the window corresponding to the title bar over which the cursor is placed.

Note setting `focus_follows_mouse no` is not desirable since with this setting, the the window on top remains unfocused when the mouse is moved from container to container.
