### ISSUE TITLE
double swaybar when using colors

### ISSUE THREAD

**Issue by matthewhague** [swaywm/sway#3946]
Sway version: 1.0 (more precisely 1.0-4 in Arch Linux).
Debug log: https://pastebin.com/w6xdn50E
Config file: https://pastebin.com/zVYEp3XS

With the attached config file, bar has a `colors { }` section after the `position top` setting. This results in two sway bars: one at the bottom with the correct colors, and one at the top with default colors.

Note: /etc/sway/config.d is an empty directory, so another bar configuration is not being loaded.

When i move the `position` setting to after the `colors` section, only one bar is shown, in the correct position and the correct colors.

Many thanks for all your work.

**Comment by c-edw** [comment]
Appears to be caused by the `font` line. I believe that's supposed to be outside of the `colors` block if specified. Shouldn't cause a second bar to appear in any case.

**Comment by matthewhague** [comment]
Aha, sorry -- didn't spot that had gone wayward. Thanks for the fast response.

**Comment by schauveau** [comment]
Interestingly, the second bar is called 'color' according to swaymsg -t get_bar_config. 
I also noticed that if an explicit name is given after the bar command then sway is producing a proper error when it finds the misplaced font command.  
So the bug is obviously related to the handling of the default bar name.

**Comment by RedSoxFan** [comment]
This is actually the intended behavior and gets parsed as:
```
# current bar: NULL
bar position top
# current bar: bar-0
bar colors font Inconsolata
# current bar: colors
bar colors statusline $black
bar colors background $grey
bar colors inactive_workspace $grey $grey $black
bar colors focused_workspace $olive $olive $white
bar colors focused_workspace $olive $olive $white
# bar block closed - current bar: NULL
```

As part of #2070, which allows any config option to be given in block or expanded form, the syntax `bar <bar-id> <bar-subcommand>` was introduced. This allows for bars to be given in a similar fashion to other commands such as `output`, `input`, `seat`, and `mode`:
```
bar <bar-id> {
    # bar subcommands
}
```

Since `font` is a valid subcommand for `bar`, `colors` is parsed as the bar-id and `font` as the subcommand. As part of #2808, it was decided that all bar subcommands are allowed to be bar-ids, with the exception of `id`. The rationale for this is that any new bar subcommands should not break an existing config due to the bar-id becoming a subcommand. So basically the config is equivalent to:
```
bar bar-0 {
    position top
}
bar colors {
    font Inconsolata
    colors {
        statusline $black
        background $grey
        inactive_workspace $grey $grey $black
        focused_workspace $olive $olive $white
        focused_workspace $olive $olive $white
    }
}
# Or if you want an i3 compatible equivalent, replace:
#   bar <id> {
# with
#   bar {
#    id <id>
```

Hopefully, that helps clear things up.

**Comment by schauveau** [comment]
I'll keep that in mind for my future book "How not to design a parser".

**Comment by ascent12** [comment]
>I'll keep that in mind for my future book "How not to design a parser".

Yeah, keeping i3 compatibility yet trying to extend it lead to some pretty weird edge cases.
I personally hate that `#rrggbb` is used for colours, which completely removes the possibility for comments to exist at the end of a line.

**Comment by RedSoxFan** [comment]
Honestly, this is a very minor issue anyway. The config would throw an error in i3 since `font` is not valid in the `colors` block and in sway just has some undesired behavior (for what would otherwise also result in an config error). Keeping i3 compatibility is much higher on the list. If i3 compatibility was not a priority, all bar commands would require an id to be explicitly given, like all the other "blocks", which would remove the ambiguity. This was the best compromise that allows extending the functionality and still keeping i3 compatibility.

**Comment by schauveau** [comment]
@ascent12 The real issue in the language is really that is no consistent logic in the way quotes, spaces and variables are handled.
