### ISSUE TITLE
[bug] scroll_button <event-code-or-name> gives error

### ISSUE THREAD

**Issue by piu130** [swaywm/sway#4016]
`$ sway -v` sway version 1.0

I'm trying to configure my touchscreen to scroll with one finger in Firefox and other applications with `input` configurations.

When I track events with `sudo libinput debug-events` I get the output for my touches on the touchscreen:

```
event10  TOUCH_DOWN        +1.22s
event10  TOUCH_FRAME       +1.22s
event10  TOUCH_UP          +1.25s
event10  TOUCH_FRAME       +1.25s
event10  TOUCH_DOWN        +1.57s
event10  TOUCH_FRAME       +1.57s
event10  TOUCH_MOTION      +1.59s
```

I tried to configure `scroll_button` for the touchscreen along with `scroll_method on_button_down`.
I set `input <id> scroll_button TOUCH_DOWN`, `input <id> scroll_button event10` and other configurations in sway config but none of them worked.

The error from `swaynag`:
```
Button event code must be a positive integer.
```

Is the man page (`man 5 sway-input`) not up to date? Or did I use the wrong event-code/name?

**Comment by RedSoxFan** [comment]
`TOUCH_DOWN` is the libinput event and event10 denotes the device. Neither is relevant here. The event codes would show up on the other side of the timestamp such as the following:

```
event5   POINTER_BUTTON   +31.63s	BTN_LEFT (272) pressed, seat count: 1
event5   POINTER_BUTTON   +31.75s	BTN_LEFT (272) released, seat count: 0
event5   POINTER_BUTTON   +32.45s	BTN_SIDE (275) pressed, seat count: 1
event5   POINTER_BUTTON   +32.56s	BTN_SIDE (275) released, seat count: 0
```

Only button events (`BTN_<event>`) will work since it is looking for a button. `scroll_method` is mainly for touchpads, although it could be used for mice as well.

For touchscreens, I think you'll have to wait for #3428.
