### ISSUE TITLE
Exec script not working in startup

### ISSUE THREAD

**Issue by guyfedwards** [swaywm/sway#4017]
* Sway Version: 1.0  
* Debug Log: https://gist.github.com/guyfedwards/24a6647bfcfeb8180ab5ade1358d96d2  
* Configuration File:  https://gist.github.com/guyfedwards/1fc1c2db871994f31ad618539f7ff77b

I have the contrib transparency script in my sway config like so:
```
exec python $HOME/dotfiles/scripts/inactive_window_transparency.py
```
However this doesn't work when starting sway, I can only get the script to work but running it manually:
```
$ $HOME/dotfiles/scripts/inactive_window_transparency.py &
```

I suspect this has something to do with permissions as the logs show the file not being found when it is there as verified by running the command not through sway.

```
2019-04-05 00:17:09 - [sway-1.0/sway/ipc-server.c:498] Client 55 writable
python: can't open file '/home/guy/dotfiles/scripts/inactive_window_transparency.py': [Errno 2] No such file or directory
```

I can also get the script to work by running with `swaymsg` after sway is loaded.
```
$ swaymsg exec python $HOME/dotfiles/scripts/inactive_windows_transparency.py
```

**Comment by emersion** [comment]
Not sure what we can do here. Python seems to be started with the correct arguments.

**Comment by schauveau** [comment]
Could that be related to the encryption or automount of the home directory (or ~/dotfiles/scripts)? That seems unlikely since sway has to be able to read its own config file in ~/.config but this is worth checking. 

From a practical point of view, a good way to diagnose the problem could be to add some exec commands before the problematic one to do things like `/bin/ls -la $HOME` or  `/bin/ls -la $HOME/dotfiles/scripts`

You could also install `strace` and execute `strace -o /tmp/strace.out  python $HOME/dotfiles/scripts/inactive_windows_transparency.py`. That should give out a file /tmp/strace.out showing all system calls performed by python including the faulty one. This is a often a good source of information for those strange issues.

You should also verify that your are using the right python since I noticed that you have several non-standard directories in your path. 

Finally, I noticed in your log file that XWayland is started long after the failure (when you start your first  X11 application?). This behavior is normally fully transparent but I could imagine that python might be confused if the X11 server is not yet fully started. This is only a wild guess but if this is really the problem then you could try to insert a X11 command before python to force XWayland to start: 
```exec xdpyinfo ; python $HOME/dotfiles/scripts/inactive_window_transparency.py```

**Comment by guyfedwards** [comment]
Thanks for the help guys!

@schauveau `strace` output showed:
 ```
execve("/usr/bin/python", ["python", "/home/guy/dotfiles/scripts/inact"...], 0x7ffe0ac1faa8 /* 46 vars */) = 0
```
Further in the file I could see many calls to `/usr/lib/python`, so tried updating config to `exec /usr/lib/python ...` which now works. 

I feel like this is possibly a botched PATH or config somewhere but my reading skills are limited when it comes to strace output. Any idea what the cause is, any help would be much appreciated as I suspect this is related to some other issues I am having with python scripts in waybar?

[`strace.out`](https://gist.github.com/guyfedwards/f68cd12d6464f0d461af06eac0125490)

**Comment by schauveau** [comment]
I assume that you mean `/usr/bin/python` and not `/usr/lib/python`. 

What I am expecting is a suspicious system call returning -1 (ENOENT = No such file or directory)  near the end of the trace. I do not see anything suspicious here. A few stat and openat calls are failing with ENOENT but this expected while python is searching for config and module files.
  
However, the multiple calls to recvfrom and sendto near the end are telling me that the python script is actively communicating with sway. Also, the trace ends with an unfinished recvfrom call and not by an exit call. To me this looks like a trace of a successful execution.

**Comment by guyfedwards** [comment]
Nope I mean `/usr/lib/python`¯\\_( ツ )_/¯.

As I was looking through `strace.out` I noticed a bunch of `/usr/lib/pythonxxx` calls so thinking along the lines of your comment about python version, tried using that in my sway config.

```
exec /usr/lib/python $HOME/dotfiles/scripts/inactive_window_transparency.py
```

This now works. 

Here are relevant directory listings:
[`ls -la /usr/lib | grep python`](https://gist.github.com/guyfedwards/28b3c8701f3a005000447c970f5579cf) 
[`ls -la /usr/bin | grep python`](https://gist.github.com/guyfedwards/3f9e627f42ff778501a950fae165cda3)

**Comment by schauveau** [comment]
Hummm... there is no `python` in your `/usr/lib` listing so I have a hard time understanding how you can execute `/usr/lib/python`

**Comment by emersion** [comment]
Closing because this isn't a sway issue

**Comment by guyfedwards** [comment]
@schauveau Yep sorry thats my bad, I got thrown off because it was working. the `/usr/lib/python` doesn't work, but the interesting thing is is that running the transparency script through `strace` works, but doesn't just using normal `exec python ...`.

Works:
```
 exec strace -o /tmp/strace.out python $HOME/dotfiles/scripts/inactive_windows_transparency.py
```
Doesn't work:
```
 exec $HOME/dotfiles/scripts/inactive_window_transparency.py 2> ~/tmp/inactive-sctip.txt
```

I appreciate this isn't sway specific but any help would be greatly appreciated.

**Comment by schauveau** [comment]
I see that you have a git for your dotfiles. we can continue our chat there.
