### ISSUE TITLE
Copy/Paste to and from lxterminal doesn't work

### ISSUE THREAD

**Issue by varshitgithub** [swaywm/sway#4023]
Reproduction steps:
1. open lxterminal and other application of your choice(I used firefox).
2.Try copying/pasting to/from lxterminal.
Copy/Paste doesn't work

**Comment by KubqoA** [comment]
This is maybe due to the [wl-clipboard](https://github.com/bugaevc/wl-clipboard) and `xclip` compatibility issues. What helped me is to install [wl-clipboard-x11](https://github.com/brunelli/wl-clipboard-x11), which replaces `xclip` with a wrapper for `wl-clip`. So now apps that were coded around `xclip` support wayland clipboard. Hope this helps

**Comment by varshitgithub** [comment]
Thank You. It's working...
