### ISSUE TITLE
"workspace <name> output <output>" does not work as documented

### ISSUE THREAD

**Issue by mythmon** [swaywm/sway#4108]
* Sway Version: `sway version  (2019-02-07, branch "")` (Installed from Fedora 30 repositories)

* Debug Log: https://gist.github.com/mythmon/e64a7c1344fd561b30702f1e21ba0bf2

* Configuration File: Reproduced with the default configuration file.

The command `workspace <name> output <output>` is listed in `man 5 sway` as specifying "that the workspace named name should appear on the specified output". However, when running the command, the named workspace does not move to the named output, and no error is reported.

Ultimately my goal is to create a keybinding that brings a given workspace to the currently focused output, even if that workspace is currently displayed on another output. I'm not asking for the workspace to be shown on both outputs, only the current way. If there is another way to do this, I'd like to hear about it.

**Comment by RedSoxFan** [comment]
`workspace <name> output <output>` does not move existing workspaces. It defines behavior for newly created workspaces of that name. The behavior stems from i3.

Unfortunately, I don't think there is currently a _good_ way to achieve your goal without an IPC script however.

It appears that sway is missing the `current` output for the `move` commands (as implemented for i3 in i3/i3#2483) so I'll submit a PR for that in a little bit.

As stated in i3/i3#2357, the `current` output would allow for `[workspace=<name>] move workspace to output current`. However, that only works for non-empty workspaces. The i3 issue appears to suggest that i3 would be open to adding the functionality, but it doesn't look like it was followed up on.

**Comment by mythmon** [comment]
> workspace <name> output <output> does not move existing workspaces. It defines behavior for newly created workspaces of that name. The behavior stems from i3.

For users that aren't familiar with i3 (like me), it would be good to note that in the man page then. As it stands it probably a little over-terse. Sway seems like one of the only viable tiling window managers that supports Wayland, so I imagine a lot of users that have never used i3 will try to use it. I think that is a useful set of users to take into consideration (though being part of this group, I'm biased :smile:).

I was exploring `workspace <name> output <output>` because `move workspace to output <output>` only seemed to be able to operate on the currently focused workspace. Are you saying that you can specify the workspace to move by prefixing the command with `[workspace=<name>]`? If so, the external script to do this would be reasonable to write (and I was already planning to write a similar script anyways).

**Comment by RedSoxFan** [comment]
> For users that aren't familiar with i3 (like me), it would be good to note that in the man page then.

Submitted as #4111 

> Are you saying that you can specify the workspace to move by prefixing the command with `[workspace=<name>]`?  If so, the external script to do this would be reasonable to write (and I was already planning to write a similar script anyways).

As long as the workspace exists and is non-empty, yes. See the section on `criteria` in `man 5 sway`.

If the workspace does not exist or is empty, your best option for now is to use `workspace <workspace>, move workspace to output <output>`. However, that solution will require you to determine the current output as `move workspace to output current` will be the output that the workspace is already on. Since you seem content with using a script anyway, this should be relatively trivial to determine using IPC events or piping `swaymsg -t get_tree` output to a `jq` query

Since a scripting solution seems sufficient, I'm going to close this for now

**Comment by mythmon** [comment]
The scripting solution was pretty easy. I've pasted it below, for others that might find this page in the future.

```bash
#!/usr/bin/env bash

if [ $# -lt 1 ]; then
  echo Usage: $0 WORKSPACE
  exit 1
fi

WORKSPACE=$1

FOCUSED_OUTPUT=$(swaymsg -t get_outputs --raw | jq '. | map(select(.focused == true)) | .[0].name' -r)
swaymsg "[workspace=${WORKSPACE}]" move workspace to output "${FOCUSED_OUTPUT}"
swaymsg workspace $WORKSPACE
```

**Comment by grfrederic** [comment]
i'm trying to achieve the same xmonad style switching.
@cptMikky your solution:
`[workspace="1"] move workspace to output current; workspace number 1`
_almost_ works. when workspace "1" is empty but already being displayed on a different output the move part fails, and the second one simply changes focus. and since workspace "1" it is not destroyed, you can't "workspace <name> output <output>" it to the current output (matter of fact, the "workspace <name> output <output>" command never works for me, even for not created workspaces). i think this means there is no way around scripting.

**Comment by cptMikky** [comment]
You're right, this is (so far) the only use-case where the move-switch approach doesn't work but only when the "target" workspace is empty. That feels like a bug though.

It works (for me) in all other use-cases, i.e any (non-empty) workspace is moved to the current output, regardless whether it is displayed on another output or not.

**Comment by grfrederic** [comment]
i feel like the most natural solution is to allow moving an empty workspace that is being displayed since it is already created, and "workspace \<name\> output \<output\>" is not supposed to move existing workspaces. however my understanding is sway team says they don't want to change/add window management features currently, so the question is whether this counts as a changing behaviour or as fixing a bug.

**Comment by cptMikky** [comment]
not sure I understand this
> and "workspace <name> output <output>" is not supposed to move existing workspaces.

For me it only makes sense to _move_ existing workspaces because, well, they exist. Moving a non-existent workspace basically means creating it. `move` command by definition doesn't create anything, it just takes something that already exists and moves it somewhere else.

As for bug-or-not-bug, imo it is a bug because the behavior is inconsistent - empty workspace doesn't move, nonempty does. I feel that the content of the workspace is irrelevant when working with the workspace as a unit.

**Comment by grfrederic** [comment]
i meant that out of the two potential fixes:
1) allow the move command to move empty-but-displayed workspaces
2) allow the "workspace \<name\> output \<output\>" command to show it
the first one is more natural, since the latter (as discussed in this thread already) "does not move existing workspaces. It defines behavior for newly created workspaces of that name. The behavior stems from i3." and the workspace in question already exists.

**Comment by grfrederic** [comment]
i had a moment to try the scripted solution. it works, but with two caveats:

1. any time the workspace we're switching to was already displayed somewhere, it is grabbed and moved to the current display (good) but then replaced with a *new* workspace rather than swapped like xmonad would (sad)
2. when an empty but displayed workspace is moved to the current display, the pointer is reset to the center of the screen

the first one can be fixed by more scripting, but then the cursor is reset every time.

i realize that these are (very) minor issues, but the scripting also not being elegant bugged me enough to try getting used to the swaywm way of doing things. funny how stubborn you can get about those things once you get used to them. well, i guess its time for a mental exercise in doing things (slightly) different
