### ISSUE TITLE
Gaps settings in config file inconsistent.

### ISSUE THREAD

**Issue by jparsert** [swaywm/sway#4144]
So as the title says it seems that the gaps inner/outer are inconsistent.
I previously had gaps inner 5 and outer 10. I now changed it to 5/5 and restarted but the gaps are still 10/5 rather than 5/5. (I did save the config file)
Additional inconsistency: If I set them to  0/0 and restart it work and they really are 0/0. If I set them back to 5/5 then they suddenly are on 5/10 again.

**Comment by RedSoxFan** [comment]
Seems to work fine for me on master. What version of sway are you using? How are you setting the gaps in your config? By "restarting", you are referring to exiting sway and relaunching sway, correct? Or are you just doing a `swaymsg reload`?

**Comment by jparsert** [comment]
I am referring to rebooting. Version 1.0.8

**Comment by jparsert** [comment]
I set them with: 
gaps outer 5
gaps inner 5

**Comment by RedSoxFan** [comment]
Can you post a debug log when the the gaps are not matching the config?

**Comment by tarmack** [comment]
Could it be that the way the gaps are applied is confusing you? The outer gaps are essentially added to the inner gaps since each container will have the gaps applied all around and then the outer gaps gets applied from the screen perimeter in. You may find that setting inner gaps to 5 and outer gaps to 0 is what you are looking for.

**Comment by RedSoxFan** [comment]
Are you still having issues with gaps?

**Comment by Xyene** [comment]
Going to close this issue due to inactivity, feel free to reopen if the issue persists.
