### ISSUE TITLE
Fix IPC compatibility issue with symbol

### ISSUE THREAD

**Issue by lasers** [swaywm/sway#4170]
Hi there. I'm not using `sway`. I'm opening an issue because there might be IPC compatibility issue with ~~symbols~~ symbol that ought to be fixed. See https://github.com/acrisci/i3ipc-python/pull/105#issuecomment-490256282

>i3 is still using symbol not symbols. Open an issue on sway to fix compatibility with i3.

Thank you!

**Comment by RedSoxFan** [comment]
Sway includes both `symbol` and `symbols` in the binding reply so there should not be any compatibility issues. Either i3ipc should include support for both (for full compatibility with sway and i3) or that line should be reverted (for just i3 compatibility).

**Comment by lasers** [comment]
@RedSoxFan Sorry to bother you again. What about ~~mods~~ event_state_mask?

**Comment by RedSoxFan** [comment]
> @RedSoxFan Sorry to bother you again. What about ~mods~ event_state_mask?

Sway provides `event_state_mask`, which matches the current i3 documentation. `mods` is not provided in Sway's reply. I don't think it makes any sense for Sway to add `mods` to the reply since `event_state_mask` was introduced in [i3 back in 2015](https://github.com/i3/i3/commit/bf3cd41b5ddf1e757515ab5fbf811be56e5f69cc) and the [i3 code states that new programs should use `event_state_mask` instead](https://github.com/i3/i3/blob/bf3cd41b5ddf1e757515ab5fbf811be56e5f69cc/src/ipc.c#L203)
