### ISSUE TITLE
dpms and font issues

### ISSUE THREAD

**Issue by swalladge** [swaywm/sway#4198]
* Sway Version:  1.0
* Debug Log: TODO
* Configuration File:  https://github.com/swalladge/dotfiles/blob/master/host-archdesk/config/sway/config

When dpms turns the monitor off (whether I do it manually, or swayidle calls it after swaylock is running), _and_ the monitors have completely turned themselves off, and then I dpms on/log back in, I often get font issues. 

Specifically, most text in x11 windows is missing. See screenshot of keepassxc:

![screenshot of keepassxc ](https://i.imgur.com/l4nlqaJ.png)

Additionally, fonts in wayland windows sometimes become fuzzy. Eg. this instance of termite:

![screenshot of termite](https://i.imgur.com/HemqGJq.png)

Actually, I'm not sure if it's just fonts that become fuzzy, or the entire window - icons and such look fuzzy in firefox, but hard to tell because firefox has several related wayland issues anyway. I'll check some other gui apps.

I'll keep this issue updated as I do more debugging.

**Comment by RedSoxFan** [comment]
A debug log would definitely help. Can you also post the output of `swaymsg -t get_outputs` when it is in the issue state?

**Comment by swalladge** [comment]
Strangely I haven't been able to reproduce the issue since reporting it. :/

**Comment by junglerobba** [comment]
I'm not sure this is directly related, but I have a similar issue with dpms, only for me it affects window titles after turning the screen back on.

![screenshot](https://user-images.githubusercontent.com/18437660/59017880-eb661400-8844-11e9-91b7-a2f158264677.png)

I used the default config for this, but I had to configure my outputs (1x 4k at scale 2.25, 1x 1440p, 1x 1080p) in order to reproduce it.

sway version 1.1-rc1-29-gb4b274cd (Jun  6 2019, branch 'master')
[sway.log](https://github.com/swaywm/sway/files/3260661/sway.log)
[get_outputs.txt](https://github.com/swaywm/sway/files/3260675/get_outputs.txt)

**Comment by ecocode** [comment]
@junglerobba I have exactly the same issue.
It happens when you have two monitors with different scale.  My laptop is hidpi and has scale set to 2.  The external monitor is scale 1.  When coming back from dpms off, the titles on the EXTernal monitor (DP-1 in my case) are scaled x2 which gives same as your screenshot.  Scale setting for the output of the external monitor is still 1 though (checked with get_outputs).

I use following workaround:
<pre>
exec swayidle -w 
         timeout 300 'swaylock -f -c 000000'
         timeout 500 'swaymsg "output * dpms off"'
              resume 'swaymsg "output * dpms on" && swaymsg output DP-1 scale 1'
         before-sleep 'swaylock -f -c 000000'
</pre>

So resetting the scale to what it actually already is seems to solve the issue.
