### ISSUE TITLE
can't set inhibit_idle without bindsym

### ISSUE THREAD

**Issue by chenjie199234** [swaywm/sway#4219]
version 1.1.1
can't write this in config
`
inhibit_idle fullscreen
`
![2019-06-05-22:11:51](https://user-images.githubusercontent.com/29348971/58962830-942d5880-87de-11e9-88a0-1edb85ea7ef5.png)

have to write like this
`
bindsym $mod+anykeyyouwant inhibit_idle fullscreen
`

**Comment by RedSoxFan** [comment]
`inhibit_idle` applies to the focused view or a view specified by criteria, neither of which make sense in the config since there are no views yet. If you are using `inhibit_idle fullscreen` in your  config, you will want to use it with `for_window`. For example, to apply it to every view, use `for_window [shell=".*"] inhibit_idle fullscreen`.
