### ISSUE TITLE
Feature request: Double border

### ISSUE THREAD

**Issue by ndgnuh** [swaywm/sway#4243]
Sometime it's hard to see the border due to the wallpaper color. I think adding double border will help with border visibility.

**Comment by ascent12** [comment]
You can already change the border width: https://i3wm.org/docs/userguide.html#_changing_border_style

**Comment by Biont** [comment]
@ascent12 I think what @ndgnuh was suggesting is the option to add a second border with individual styles. So for example if you have a white border on a very bright section of the wallpaper, it would be harder to see. Changing the border width of the white border would not help make it more visible. But a second 1px black border around the white one would make sure the border is always 100% visible.

Personally I'd prefer to see this solved by #1065, I just wanted to clear up what I felt this issue is about.

**Comment by ndgnuh** [comment]
> @ascent12 I think what @ndgnuh was suggesting is the option to add a second border with individual styles. So for example if you have a white border on a very bright section of the wallpaper, it would be harder to see. Changing the border width of the white border would not help make it more visible. But a second 1px black border around the white one would make sure the border is always 100% visible.
> 
> Personally I'd prefer to see this solved by #1065, I just wanted to clear up what I felt this issue is about.

Yes, thank you!

**Comment by Inc0ns1st3nt** [comment]
Hi, currently I am setting the border of a window with: `bindsym $mod+b border pixel 4`
is there a way to set the border to 4 pixel for for all window instead of only one on the keys binded?
