### ISSUE TITLE
Firefox with wayland backend fails to start

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#4281]
`sway version 1.1-rc1-48-ga18d1c55 (Jun 23 2019, branch 'master')`

After updating sway and firefox-nightly, `GDK_BACKEND=wayland firefox` refuses to start with error `Error: cannot open display: :0`

Log says:

```
[subprojects/wlroots/xwayland/xwm.c:830] XCB_CREATE_NOTIFY (14680066)
[sway/desktop/xwayland.c:589] New xwayland surface title='(null)' class='(null)'
[subprojects/wlroots/xwayland/xwm.c:844] XCB_DESTROY_NOTIFY (14680066)
```

Is this a Firefox issue or a Sway one?

**Comment by emersion** [comment]
Firefox Nightly is broken.

**Comment by colemickens** [comment]
Just posting in case it helps someone else in the future. I was actually looking for this particular bug in my email and noticed this sway issue...

Sway + Firefox Nightly users would be well served by subscribing to the tracking meta issue on Mozilla's bug tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=635134

For reference, this bug was noticed and filed within hours of the build going live. This is the exact issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1560545
