### ISSUE TITLE
Sway hangs for a few seconds before first window opens

### ISSUE THREAD

**Issue by leafpile** [swaywm/sway#4359]
version: 1.0

I installed sway on two laptops, and one of them has the problem.  I was trying to nail down the cause but didn't come up with anything.

What I did was to launch sway, wait for 10 seconds, and then launch termite.  There would be a 2-8 seconds lag between the command and response.  After that, further commands work without any lags.

[Gist](https://gist.github.com/leafpile/99b40033b1742fea7b96040bbd36f645)

(Line 1141 was when I launched termite)

**Comment by ascent12** [comment]
If it only affects termite, it's likely not a sway problem.

I have a superficially similar "issue" (not really), where I have a secondary hard drive which will automount. If I try to use anything on that drive (including opening several programs), it would take quite awhile the first time, because it's waiting for the drive to mount. Do you have a similar setup?

But I can also see that xwayland is lazily being started at the line you pointed out. Perhaps X being slow to start is related?

**Comment by leafpile** [comment]
Ah sorry!  I forgot to mention that it doesn't just affect termite, also anything I throw at it (dmenu, emacs, etc.)

And yes I also suspect it has something to do with X being slow to start.  

Is there a way to start xwayland when sway starts?
