### ISSUE TITLE
Is there any way to get Cap Lock state?

### ISSUE THREAD

**Issue by asahaf** [swaywm/sway#4512]
Hi,
Is there any way to get Cap Lock state? also if it is possible to get Cap state change updates using IPC with subscribe?

**Comment by emersion** [comment]
No, there's no way to get this information.

**Comment by asahaf** [comment]
No plan to add this information to IPC get input command?

**Comment by cafehaine** [comment]
If you want to get this information in C code, you can probably check out how it is done in swaylock https://github.com/swaywm/swaylock/commit/52e2575d19b641728cc4e33ca76442bd86620f74#diff-e68bb6d329601eef5e8c55bae5920fc5

Otherwise if you don't plan on distributing the program*, you can check the brightness of the capslock led at `/sys/class/leds/*::capslock/brightness`. This will work with anything, even bash. 

\* note that it won't work if the role of the capslock led is changed by the xkb config.

**Comment by asahaf** [comment]
I'll give it a try, thanks!

**Comment by Xyene** [comment]
Going to close this issue since a solution was proposed.
