### ISSUE TITLE
Sway no longer starts after arch update to "1:1.2-1"

### ISSUE THREAD

**Issue by Kommynct** [swaywm/sway#4514]
* Sway Version: sway -v gives me: sway version 1.1 (odd considering the repo says 1.2-1)

* Debug Log: https://gist.github.com/Kommynct/dade2d8352b26bdd55ebcbddf02fd7fe

* Configuration File: I tried it without one and it gave me the same errors.

I ran sway in a tty window. Nothing else was open.

* Here's the coredump https://gist.github.com/Kommynct/29120b2edbc35f243a66155f9f54b330

i tried sway-git and got the same result (yes i installed wlroots-git)

and a friend of mine with a completely different HW setup got the same error.

**Comment by duffydack** [comment]
I can confirm the issue.  I have found the issue is with the wlroots 0.7.0 package, as I had sway 1.2-1 upgraded and working previously before the wlroots pkg got updated.

**Comment by duffydack** [comment]
wlroots pkg has been updated "rebuild sway due to wlroots soname bump".  sway now loads.

**Comment by Kommynct** [comment]
Uh, after trying a pacman -Syu I see no changes as of yet, and I also don't see any activity in the wlroots github about this.

**Comment by duffydack** [comment]
sway 1:1.2-2 (rebuilt with wlroots 0.7.0) will hit your repo soon.  I have it, it works.

**Comment by agboom** [comment]
Can confirm, I'm in the same situation with Sway 1.2-2 and wlroots 0.7.0-1 on Arch.

You can temporarily downgrade to resolve this until the rebuild is available:

`sudo pacman -U /var/cache/pacman/pkg/sway-1.1.1-3-x86_64.pkg.tar.xz`
`sudo pacman -U /var/cache/pacman/pkg/wlroots-0.6.0-2-x86_64.pkg.tar.xz`

**Comment by duffydack** [comment]
That's odd @agboom, I had the issue which turned out to be the sway pkg needed to be rebuilt with wlroots 0.7.0, which has since been rebuilt and released (1.2-2), and I can confirm it has fixed the issue.

**Comment by emersion** [comment]
Seems like a package issue, closing.

**Comment by Kommynct** [comment]
so, i'm running sway 1.1.2-2 and it's still doing the exact same thing?

**Comment by turlando** [comment]
Works for me with the following packages.

```
% pacman -Qi sway wlroots
Name            : sway
Version         : 1:1.2-2
Description     : Tiling Wayland compositor and replacement for the i3 window manager
Architecture    : x86_64
URL             : https://swaywm.org/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : cairo  gdk-pixbuf2  json-c  pango  pcre  swaybg  ttf-font  wlroots>=0.6
Optional Deps   : dmenu: Application launcher [installed]
                  i3status: Status line [installed]
                  grim: Screenshot utility [installed]
                  mako: Lightweight notification daemon [installed]
                  rxvt-unicode: Terminal emulator
                  slurp: Select a region [installed]
                  swayidle: Idle management daemon [installed]
                  swaylock: Screen locker [installed]
                  wallutils: Timed wallpapers
                  waybar: Highly customizable bar
                  xorg-server-xwayland: X11 support [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 5,52 MiB
Packager        : Brett Cornwall <brett@i--b.com>
Build Date      : gio 29 ago 2019, 19:22:19
Install Date    : lun 9 set 2019, 14:10:20
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

Name            : wlroots
Version         : 0.7.0-1
Description     : Modular Wayland compositor library
Architecture    : x86_64
URL             : https://github.com/swaywm/wlroots
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : libinput  libxkbcommon  opengl-driver  pixman  xcb-util-errors  xcb-util-image  xcb-util-wm
Optional Deps   : None
Required By     : sway
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 924,00 KiB
Packager        : Brett Cornwall <brett@i--b.com>
Build Date      : gio 29 ago 2019, 17:24:28
Install Date    : lun 9 set 2019, 14:10:20
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by Kommynct** [comment]
I just spent some time trying to work it out based on previous issues that have been closed.

I triple checked sway-git and wlroots-git, as well as swaybg-git, nothing.

I can't seem to find anything relevant to the error log. When I run sway 2> error.log

i'm getting

     2019-09-10 01:25:36 - [EGL] eglSwapBuffers: dri2_swap_buffers
     2019-09-10 01:25:36 - [render/egl.c:400] eglSwapBuffers failed
     2019-09-10 01:25:36 - [EGL] eglSwapBuffers: no front buffer

I've tried googling each of these individually to no avail, in a previous thing I saw "coredumpctl gdb sway" run

that gives me: 

       Message: Process 13139 (sway) of user 1000 dumped core.

                Stack trace of thread 13139:
                #0  0x00007f07040ad093 wl_list_insert (libwayland-server.so.0)
                #1  0x00007f070406e60b wlr_signal_emit_safe (libwlroots.so.0)
                #2  0x00007f070404e0ea wlr_seat_destroy (libwlroots.so.0)
                #3  0x00007f07040a8bef n/a (libwayland-server.so.0)
                #4  0x00007f07040a9377 wl_display_destroy (libwayland-server.so.0)
                #5  0x000055862da067ae server_fini (sway)
                #6  0x000055862da06019 main (sway)
                #7  0x00007f0703bf4223 __libc_start_main (libc.so.6)
                #8  0x000055862d9f9b2e _start (sway)

Which is meaningless to me, i'm really stuck here... sway used to work absolutely fine, but now, absolutely nothing, I think its an issue with the modesetting?

**Comment by ascent12** [comment]
Looking at the mesa source code, I can see two places where the message "dri2_swap_buffers" can be generated with the DRM backend.
Unfortunately I was an idiot and didn't include the necessary information the distinguish between the two in our log messages. Can you try with wlroots compiled with https://github.com/swaywm/wlroots/pull/1822?

Both cases seem to be rather weird, though, and would possibly imply that we aren't using the API correctly. I don't believe that is the case, because that code hasn't changed in quite a while and has been working correctly for years, and still currently works for me at least.

I'd look at seeing if your mesa installation is correct and you don't have any weird kernel configuration that may be messing with your GPU driver.

**Comment by eujean** [comment]
I had the exact same issue on arch getting the same dri2_swap_buffers error. I fixed it by doing a clean-build of both wlroots-git and sway-git.

**Comment by Kommynct** [comment]
just clean-built them both, 


     2019-09-16 12:13:49 - [EGL] command: eglSwapBuffers, error: 0x3003, message: "dri2_swap_buffers"
     2019-09-16 12:13:49 - [render/egl.c:402] eglSwapBuffers failed
     2019-09-16 12:13:49 - [EGL] command: eglSwapBuffers, error: 0x300d, message: "no front buffer"
     2019-09-16 12:13:50 - [swaybg/main.c:521] Missing a required Wayland interface

here's the output now... i've been doing a clean build every time.

**Comment by ascent12** [comment]
The error 0x3003 (EGL_BAD_SURFACE) followed by "no front buffer" seems to be what happens if we're not releasing our buffers properly. Here is the minimal testing code I was using to try and reproduce that error for anybody who's interested: https://gist.github.com/ascent12/cea52d023c646b40a4375b7a58089329

It's plausible that this broke between wlroots 0.6 and 0.7, because that was when @emersion's direct scan out work was merged, which is related to this. Although I still have no idea why it's affecting you, but not most other people, including myself.

I did notice you had WLR_DRM_NO_ATOMIC set in your original log, which isn't something you should be setting without a good reason to, but even when I use that on amdgpu, it still runs fine.

This is something I'll need to look more into.

**Comment by Kommynct** [comment]
I actually set that setting because I was trying everything to fix the issue and forgot to remove it before making the log, my bad.

**Comment by agarciamontoro** [comment]
I started experiencing this in my laptop, too. I haven't used my external monitor for a few days, and today I connected it again and got the exact same error that @Kommynct is reporting. Although the error is only triggered when I connect my external monitor.

I tried with the current Arch package `sway` instead of `sway-git` and it works fine.

Did you find any workaround?

**Comment by Kommynct** [comment]
I finally figured it out. 

A previous version of sway-git from the aur put files in /usr/local/bin/ called sway

Those stayed there but weren't the new exe files, meaning wlroots was mismatching with an old sway being called. Deleting those files and then reinstalling sway totally resolved the issue.
