### ISSUE TITLE
i3blocks Spawning duplicates

### ISSUE THREAD

**Issue by panaman67** [swaywm/sway#4533]
* Sway Version: sway version 1.2

After config reload, i3blocks spawns another process every time. Not sure if Sway issue or i3blocks
Before reload:
![before](https://user-images.githubusercontent.com/16823053/64126620-11cc1a80-cd74-11e9-849a-9e53c719615d.png)
After reloading a few times:
![aftermany](https://user-images.githubusercontent.com/16823053/64126628-17c1fb80-cd74-11e9-822b-e0190c935c2e.png)

**Comment by yory8** [comment]
Also swaybar and i3status

**Comment by RedSoxFan** [comment]
Related #4500

I'm going to be submitting a PR that will complete support for the barconfig update ipc event and clean up the bar command handlers tonight when I get back to my laptop. It will address this case, but it will still be possible to have stray status command instances when swaybar segfaults or aborts so that will need an additional change

**Comment by asahaf** [comment]
I noticed it with waybar too. [https://github.com/Alexays/Waybar/issues/448](url)

**Comment by treeshateorcs** [comment]
how do I reload config? (sway? or i3blocks?)
