### ISSUE TITLE
xwayland's SIGUSR1 kills sway on platforms where the OpenGL DSO uses threads

### ISSUE THREAD

**Issue by a-m-joseph** [swaywm/sway#4538]
Sway needs to mask out SIGUSR1 before loading any DSOs such as OpenGL drivers -- like Weston does.  Otherwise if the GPU driver DSO spawns its own threads (ARM Mali does) those threads won't have SIGUSR1 blocked and xwayland will kill sway.

Pull request to implement the fix: https://github.com/swaywm/sway/pull/4537

**Comment by a-m-joseph** [comment]
New pull to do this in wlroots instead: https://github.com/swaywm/wlroots/pull/1815

**Comment by a-m-joseph** [comment]
Reopening as requested in https://github.com/swaywm/wlroots/pull/1815#issuecomment-527903621

**Comment by travankor** [comment]
I think the Sway people are only interested in supporting Panfrost, not Mali.

**Comment by jamadazi** [comment]
@travankor AFAIK the attitude is against drivers that do not implement the standard APIs (supporting such drivers would require writing special code just for them), rather than against proprietary drivers in general. If a proprietary driver properly implements all the needed functionality (without needing workarounds that hinder open-source code), why not have it work? 

Of course, open-source drivers are much more likely to be of high quality (and can be fixed if they are not), unlike proprietary drivers, so users should prefer them.

**Comment by Xyene** [comment]
As of https://github.com/swaywm/wlroots/pull/2504, wlroots no longer uses SIGUSR1 to signal Xwayland readiness.
