### ISSUE TITLE
[Question] Sway on 2-in-1s

### ISSUE THREAD

**Issue by JonnyMako** [swaywm/sway#4635]
I'm thinking of installing and testing sway on a 2-in-1. I suspect there won't be any problems using with keyboard attached. What should my expectation be in terms of it working in "tablet mode"?
Does anybody think it is worth testing? Has anybody already tried it? Any pointers? A couple of questions that spring to mind about basic features.
o Will onscreen keyboard work?
o Is there pen/finger support?
 What extra packages do I need to get these basic features working? I'll be using Arch Linux.

**Comment by ronchaine** [comment]
I am using Sway on Thinkpad X1 tablet, and it works pretty well, I needed to use https://github.com/jakeday/linux-surface kernel though to get hardware working, but that's not Sway's fault. (It's available on AUR if you don't want to compile it yourself)

Only extra package I needed was libinput-gestures to get support for trackpad gestures, onscreen keyboard, pen, fngers, all that jazz worked from the start with no extra stuff after the new kernel.

Only problem I have is that pen pressure doesn't work on wine for me, but I have no idea if Sway, xwayland or wine is to blame, and I haven't bothered looking into it too much, since I don't really need it with windows programs.

**Comment by JonnyMako** [comment]
@ronchaine thanks for the input. That sounds encouraging. I'm looking into getting Acer Switch Alpha, which seems to have good (Arch) Linux support. Hopefully I can get things working with the standard kernel. Just out of curiosity, how do you launch programs in when hardware keyboard is detached?

**Comment by emersion** [comment]
_(Closing since this isn't a Sway bug)_
