### ISSUE TITLE
window title does not update when in a sub-container

### ISSUE THREAD

**Issue by SairesArt** [swaywm/sway#4652]
In my GLFW Application I show FPS in the window title. This works, unless the window is in a sub-container. For instance I subdivide my text editor's container vertically, so my app is below my text editor, then only the inital window title is shown.
I can float my window or start it in a seperate container and the window title refreshes correctly, showing fps. However, when I move it back into the subcontainer, the window title is reverted to the inital window title, not updating anymore.

**Comment by RedSoxFan** [comment]
I can't replicate. What version of sway are you using? Can you please provide your config and a debug log?

**Comment by SairesArt** [comment]
In this example I have split a tabbed window vertically and the window title of my application is "Initial Window Title". The Window title in this screenshot however, never updates. I update the window title every frame.
![screen](https://user-images.githubusercontent.com/10562480/67136996-e4a5cf80-f22e-11e9-8d03-433a2b2169aa.png)
I use "default_border pixel", so I don't have a window title bar when it is split like this. I show my window titles in waybar. If I disable default_border normal, then I see the title updating in the titlebar of the window, but not up top, where it still says "Initial Window Title"
![screen2](https://user-images.githubusercontent.com/10562480/67137119-7bbf5700-f230-11e9-98d5-1c35fa638785.png)

sway version 1.2. Also for the future, where can I find sway's debug logs?

**Comment by RedSoxFan** [comment]
> The tabbed-Window-title

This is working by design. Container titles show a representation of what is in them. The representation will use the `app id` (for `xdg-shell`) or `class` (for `xwayland`) set by the application.

If you were to focus the actual view (window) and run `border normal` on that, it will be your application title. As for why it's showing `Initial Window Title`, that must be being set as your application's app id/class somewhere.

https://github.com/swaywm/sway/blob/3ee3a9ef60c6259720564bbedb0c74d545d2ec53/sway/tree/container.c#L553-L560

> where can I find sway's debug logs?

Sway logs to `stderr` so run sway as `sway -d 2>sway.log`

**Comment by SairesArt** [comment]
Thanks for the info :]

Yeah, I set the window title to "Initial Window Title" to test this out real quick^^

**Comment by RedSoxFan** [comment]
> I set the window title to "Initial Window Title"

Run `swaymsg -t get_tree` and look at what is set for `app_id` (or `class`, if its using xwayland)? They are not the same as a window title and if GLFW is setting them when you change the window title, you should report that as a bug to GLFW
