### ISSUE TITLE
Can't configure gaps to work

### ISSUE THREAD

**Issue by boobootat** [swaywm/sway#4714]
When entering commands `swaymsg gaps inner 10`, `swaymsg gaps outer 10` nothing happens. Tried to add these lines in .config/sway/config

`gaps inner|outer|horizontal|vertical|top|right|bottom|left <px>`
`gaps outer all set 20`
`gaps inner all set 20`

After reloading config and/or exiting sway session I have this:
![2019-11-09-164453_grim](https://user-images.githubusercontent.com/45947948/68531219-61006f80-0310-11ea-9ae9-468ded7691cd.png)

**Comment by rdrey** [comment]
The syntax inside the config file is much simpler than the swaymsg syntax. (There is no `all` since it will apply to all future workspaces and there is no `set` either. This works in my config file `gaps inner 8`. Good luck

**Comment by telamon** [comment]
Also worth mentioning since I had similar issue just a day ago.. 
The new  gap settings apply only to new workspaces. existing gaps are not retroactively updated.
So in order to get any kind of visual confirmation you need to reload your sway-conf and move your windows to an uninhabited workspace. (or reboot/log out)

**Comment by RedSoxFan** [comment]
`gaps inner|outer|horizontal|vertical|top|right|bottom|left <px>` changes the default gaps for future workspaces.  This can be used in the config file or at runtime, but will not effect existing workspaces

`gaps inner|outer|horizontal|vertical|top|right|bottom|left all|current set|plus|minus <px>` changes the gaps for existing workspaces, but will not effect future workspaces. Since this affects existing workspaces, it can only be used at runtime

**Comment by boobootat** [comment]
> This works in my config file: `gaps inner 8`.

Thanks a lot, it helped me.It's kinda funny that the solution was so simple. Loving sway so far

**Comment by boobootat** [comment]
Thank you so much for your help <3

**Comment by rileyrg** [comment]
Is there another resource for this as "man 5 sway" doesn't mention it?

**Comment by Ramsfield** [comment]
> Is there another resource for this as "man 5 sway" doesn't mention it?

`man 5 sway` does have it, it's under the Commands section.
Here's the excerpt:
```
gaps inner|outer|horizontal|vertical|top|right|bottom|left all|current
       set|plus|minus <amount>
           Changes the inner or outer gaps for either all workspaces or the cur-
           rent workspace. outer gaps can be altered per side with top, right,
           bottom, and left or per direction with horizontal and vertical.
```
Cheers

**Comment by rileyrg** [comment]
> > Is there another resource for this as "man 5 sway" doesn't mention it?
> 
> `man 5 sway` does have it, it's under the Commands section.
> Here's the excerpt:
> 
> ```
> gaps inner|outer|horizontal|vertical|top|right|bottom|left all|current
>        set|plus|minus <amount>
>            Changes the inner or outer gaps for either all workspaces or the cur-
>            rent workspace. outer gaps can be altered per side with top, right,
>            bottom, and left or per direction with horizontal and vertical.
> ```
> 
> Cheers

Thanks, but I was referring to the difference in usage between swaymsg and direct config usage. That wasn't immediately obvious in my Q and I apologise.

**Comment by RPigott** [comment]
The man page lists both. The command section is split into config-only, client-only, and universal commands. The gaps command is listed under the client-only and universal bits, only the universal gaps commands can be used in the config. In your manpager search for the phrase "following commands" to jump to the sections.

**Comment by rileyrg** [comment]
There's a reason this thread is here.  I'm not quite sure what you're defending.
