### ISSUE TITLE
Disable compositing or vsync?

### ISSUE THREAD

**Issue by Derynect** [swaywm/sway#4715]
Is there any way to disable either compositing or vsync? I always turn that off when I run X with i3-gaps and I like the experience much better.

**Comment by ddevault** [comment]
We're working on a different approach to this for the next release.

**Comment by Derynect** [comment]
Thanks for your reply, I'll try following development - are there any keywords I should be looking for? Happy to help test.  Thanks!

**Comment by ascent12** [comment]
We cannot disable composting, because it's completely core to how Wayland actually works. We wouldn't want to anyway.

We don't really want to disable vsync either, but by being smarter about when we do our rendering, we can reduce input latency by a lot, while still being vsynced and not tearing: https://github.com/swaywm/sway/pull/4588

**Comment by Derynect** [comment]
Thanks for referencing the PR. I understand the want for vsync but I suppose I'm just too used to running with the least amount of latency while accepting tearing for too long. I found the existing sway to feel quite sluggish, kind of like Win7 with Aero or whatever it is vs Win 95 if that makes any sense. 

Also please don't treat my comment as a direct attack against sway, I think it's a great project and I'd love to finally migrate over especially considering how buggy my 5700 XT is in X. I was merely curious if things can be a bit less latent and I think the work is indeed in progress. I'll give this PR a go!

**Comment by YellowOnion** [comment]
> being smarter about when we do our rendering, we can reduce input latency by a lot

I would like to see benchmarks of this, vsync tend to add [75ms of latency](https://youtu.be/8ZRuFaFZh5M?t=478), most video games sample the input way too early without a precise frame rate limit.

If you can achieve something like RTSSs scanline sync (in terms of precise frame timings reducing latency) I would be very very happy.

**Comment by YaLTeR** [comment]
> > being smarter about when we do our rendering, we can reduce input latency by a lot
> 
> I would like to see benchmarks of this

I've got some input latency measurements here: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1762 for automatic repaint scheduling in Mutter. In sway you'd even get a few ms less because the rendering path is faster.

> If you can achieve something like RTSSs scanline sync

I'm not a DRM expert but as I understand it you need to submit a complete frame and the frame must have completed rendering by the time it starts being scanned out, so no individual scanline sync is possible.

**Comment by kennylevinsen** [comment]
> I would like to see benchmarks of this, 

You're free to make some. See `man 5 sway` and `man 5 sway-output`, and look for `max-render-time` in both for how to minimize latency during testing.

> vsync tend to add 75ms of latency, most video games sample the input way too early without a precise frame rate limit.

Double-buffered, non-tearing, vblank-synchronized presentation introduce at most slightly less than *one* monitor refresh cycle of latency, which is the delay caused by an application missing the composition deadline and thus postponing the frame till the next composition. If the Wayland compositor is *not* doing smart composition scheduling, then an additional refresh cycle of latency ends up introduced.

This is the only thing enforced by Wayland, and has nothing to do with "vsync" toggles in games. If you lack a space heater, feel free to render and submit frames at 500 fps. We'll always show the most recent one that was submitted when composition started. If you don't need a heater, but want to reduce latency further, look at the frame callback scheduling YaLTeR's work permits, which let you specify exactly when an application receives a request to render. With that, a sufficiently fast application should have sub-refresh latency from render start till composition finish.

(Tearing is a different discussion, and the long story short there is that it only adds real benefit if *every* frame has *numerous* tearlines.)

**Comment by YellowOnion** [comment]
@YaLTeR I get serve, like 2s+ latency issues in Halo on Mutter/XWayland with mailbox mode when my game is ruining at 200fps~, mutter also drops visually below 60fps as well. it's possibly related to MR 168.

**Comment by Architector4** [comment]
I'd love a feature like this. On Xorg/i3wm, if I drag a window side to side, I feel no input lag and can see the screen tearing on the window as I drag it, which I'm absolutely fine with. On Sway, there's no tearing, which is cool and all, but the vsync input lag makes things feel very sluggish on a 60Hz monitor.

The `max_render_time` hack is neat, but it doesn't ever eliminate input to image latency entirely (at least compared to what no vsync allows for), and sometimes backfires even worse if the guessed value is wrong or if system performance ever fluctuates enough to make it wrong.

I'd really love to just let applications cut through the middle of the screen with the new frame than for them to have to wait for the vsync lol

**Comment by emersion** [comment]
A tearing output command has been available for a while.

**Comment by Architector4** [comment]
> A tearing output command has been available for a while.

As far as I can tell, it only applies to cases where a program is in fullscreen mode and requests a presentation mode that allows tearing? Neither `output * allow_tearing on` nor `for_window [all] allow_tearing on` (which afaict forces a tearing presentation mode for fullscreen windows) seem to enable tearing globally on Sway itself, just fullscreen windows
