### ISSUE TITLE
key "XF86AudioPlayPause" unknown

### ISSUE THREAD

**Issue by freswa** [swaywm/sway#4783]
```
sway version 1.2
```
If I include the Button `XF86AudioPlayPause` in my sway config like so:
```
bindsym XF86AudioPlayPause      exec playerctl play-pause
```
Sway errors, with
```
Unknown key or button 'XF86AudioPlayPause'
```
Using `sudo libinput debug-events --show-keycodes` the button shows as
```
 event10  KEYBOARD_KEY      +7.23s	KEY_PLAYPAUSE (164) pressed
 event10  KEYBOARD_KEY      +7.32s	KEY_PLAYPAUSE (164) released
```

**Comment by RedSoxFan** [comment]
The keysym is `XF86AudioPlay`. You can use [`wev`](https://git.sr.ht/~sircmpwn/wev) or `xev` to get the keysyms

**Comment by thiagowfx** [comment]
Adding this note for posterity:

I hit the same bug. `XF86AudioPlayPause` is an existing key. With my keyboard (Keychron K2), there's no `XF86AudioPlay`. The only key that represents that is `XF86AudioPlayPause`. Tested with `i3` and it works fine. With `sway` I get the same error message as OP.

I investigated this a bit further and traced the root cause to the following:

Sway error: https://github.com/swaywm/sway/blob/b17cf58a4dfcb1fbcbc039bf3032119764fd82b4/sway/commands/bind.c#L200

The underlying issue is that libxkbcommon doesn't have `XF86AudioPlayPause`: https://github.com/xkbcommon/libxkbcommon/blob/f60bdb1680650a131e8e21ffa4a8a16775a35c9f/src/ks_tables.h#L2235

It's an upstream bug. I'll try to follow up there. Would you like to reopen this bug to track the upstream one once it's filed, or just leave this closed since it's not an error in sway anyway?

**Comment by Emantor** [comment]
Even if the keysym binding is not working because libxkbcommon does not know the key, a keycode binding should still work.

**Comment by thiagowfx** [comment]
@Emantor: That's fair. I investigated a bit more and realized there's a new issue though: it's harder than it seems to figure out what the keycode for `XF86AudioPlayPause` is.

I tried `xev` and `wev`, and both of them do not register the keypress - other keys like `XF86AudioLowerVolume` and `XF86AudioRaiseVolume` do get detected by them though. I also tried googling `XF86AudioPlayPause` to see if its keycode is available but anywhere but couldn't find anything.

I am not interested in support - I can work around this issue - but if you're interested to help me figure out what the correct keycode is, I'd love to land a fix upstream, however I ran out of ideas in how to figure out the keycode. Most solutions online only mention `xev` or `showkey -a` or  `libinput` commands but none of them work for that key.

**Comment by thiagowfx** [comment]
Finally got it!

```
% xmodmap -pke | grep -i xf86audioplay
keycode 172 = XF86AudioPlay XF86AudioPause XF86AudioPlay XF86AudioPause
keycode 208 = XF86AudioPlay NoSymbol XF86AudioPlay
keycode 215 = XF86AudioPlay NoSymbol XF86AudioPlay
```

Guessed `172` was the keycode for `XF86AudioPlayPause`, and indeed it was. The following config works:

```
sway.conf:

# XF86AudioPlayPause: xmodmap -pke | grep XF86AudioPlay
# https://github.com/swaywm/sway/issues/4783
bindcode 172 exec playerctl play-pause
```

**Comment by ppvnf** [comment]
For me it works like this, you need to bind both keys otherwise it doesn't get recognized half of the time, but tbh i don't get the reason why Sway doesn't have them combined as XF86AudioPlayPause

```
bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioPause exec playerctl play-pause
```
