### ISSUE TITLE
xournalpp wacom pen sensitivity does not work 

### ISSUE THREAD

**Issue by tedk0n** [swaywm/sway#4895]
OS:
    Arch Linux
    In case of linux, which desktop environment [Wayland, Gnome-Wayland, XWayland, X11]
    Sway ( sway :1.2-5, wlroots 0.8.1-1, wayland 1.17.0-1)
    Which version of libgtk do you use.
    gtk3 1:3.24.13-1
    Version of Xournal++ [e.g. 1.0.10, specific commit, specific branch]
    xournalpp 1.0.16-1
    The device on which the problem is detected
    thinkpad helix gen 1

Describe the bug
Wacom pen in Sway DE no pressure. In Gnome3 under wayland pressure works fine.

    libinput list-devices
```

    Device: Wacom ISDv4 EC Pen
    Kernel: /dev/input/event17
    Group: 7
    Seat: seat0, default
    Size: 257x145mm
    Capabilities: tablet
    Tap-to-click: n/a
    Tap-and-drag: n/a
    Tap drag lock: n/a
    Left-handed: n/a
    Nat.scrolling: n/a
    Middle emulation: n/a
    Calibration: identity matrix
    Scroll methods: none
    Click methods: none
    Disable-w-typing: n/a
    Accel profiles: none
    Rotation: n/a

```
    libinput debug-events

 ```
   event17 TABLET_TOOL_AXIS +2.17s 212.25/120.94 pressure: 0.93*
    event17 TABLET_TOOL_AXIS +2.19s 212.25/120.94 pressure: 0.94*
    event17 TABLET_TOOL_AXIS +2.27s 212.24*/120.96* pressure: 0.94
    event17 TABLET_TOOL_AXIS +2.29s 212.15*/121.11* pressure: 0.76*
    event17 TABLET_TOOL_AXIS +2.29s 212.05*/121.23* pressure: 0.62*
    event17 TABLET_TOOL_AXIS +2.30s 211.89*/121.32* pressure: 0.46*
    event17 TABLET_TOOL_AXIS +2.31s 211.69*/121.32* pressure: 0.30*
    event17 TABLET_TOOL_AXIS +2.32s 211.47*/121.20* pressure: 0.12*
    event17 TABLET_TOOL_TIP +2.36s 211.10*/120.83* pressure: 0.00* up

```

**Comment by emersion** [comment]
Can you provide a `WAYLAND_DEBUG=1` log of your client?

```sh
WAYLAND_DEBUG=1 your-client >client.log 2>&1
# Then reproduce the bug
```

**Comment by florentc** [comment]
Pen pressure is not supported in 1.2. It has been added in the master branch since then. Until 1.3 is released, you may switch to the dev version (e.g. using the [sway-git AUR package](https://aur.archlinux.org/packages/sway-git/) AUR package. I report fully functional pen pressure for my Wacom Intuos S in Xournal++, under sway 1.2-1e2a2b07 (january 6 2020).

Unfortunately, it seems a few regressions have been introduced alongside (issues not in v1.2). If you can afford the time, I would be glad to get your input on the matter in issue #4819 I opened a few weeks ago since there is only a few of us tablet users.
