### ISSUE TITLE
Starting kanshi causes failed assertion in `wlr_output_management_v1.c` [already bisected]

### ISSUE THREAD

**Issue by Ferdi265** [swaywm/sway#5014]
## Problem Description

`sway` master crashes via failed assertion when starting `kanshi` with an empty config file.

## Versions and Logs

* `sway` Version: 1.4-f5fa0c71 (Feb 13 2020, branch 'HEAD'), AUR r6219.f5fa0c71-1
* `wlroots` Version: AUR 0.10.0.r9.g273b280f-1
* `kanshi` Version: AUR r80.86d6aff-1
* Debug Log, Backtrace, and Configuration File: https://gist.github.com/Ferdi265/60c62196aa8ce518bcbd4e0d46b947d9

## Additional Information

* Failed Assertion:
```
sway: types/wlr_output_management_v1.c:689: head_send_state: Assertion `head->state.mode != NULL || wl_list_empty(&head->state.output->modes)' failed.
```
Using a debugger I confirmed, that `head->state.mode` is `NULL` and `&head->state.output->modes` is not empty.

* Triggering Commit: f5fa0c7124dde3438a22550aae017f824d20c93b "Stop calling apply_output_config from output_enable"

**Comment by wkral** [comment]
I've been getting a crash with the exact same error but under different circumstances. Wondering if the fix in #5015 would solve my issue as well.

I have a computer hooked up to a TV which has a power off feature after not receiving a signal for 15 minutes. I have `swaylock` configured to send `swaymsg "output * dpms off"`and I would get crashes after waking up the computer but seemingly at random at the time. I've since narrowed it down to the condition where if I send input input first so it sends `swaymsg "output * dpms on"` it's fine. But if I power on the TV without providing that input I get the crash:

```
sway: types/wlr_output_management_v1.c:689: head_send_state: Assertion `head->state.mode != NULL || wl_list_empty(&head->state.output->modes)' failed.
```

I am also using `kanshi`if that maybe plays a role in this situation. I hope the fix already provided does fix this situation but if you don't think so I can open another issue.

sway: 1.4
swaylock: 1.5
kanshi: 1.1.0
