### ISSUE TITLE
sway/wlr_keyboard_group: should not group virtual keyboard with real keyboards sometimes

### ISSUE THREAD

**Issue by xhebox** [swaywm/sway#5025]
Follow the third point in comment: https://github.com/swaywm/wlroots/pull/1864#issuecomment-588034878.

> I think I got why I will miss all release key events with keyboard_group. Keyboard_group is working by counting. If physical press f, IME virtual press f, physical release f is emitted, then it counts as +1 +1 -1 = 1. And release events are only sent when the count is 0.

It is a relatively, separated issue. This may happen when a client is going to grab the keyboard and relay/forward/send-back key events, whatever it is an IME or not. But currently the only protocol allow clients to grab and send back key events is input_method_v2.

**Comment by xdavidwu** [comment]
I already explained the situation and said that I will look into this here: https://github.com/swaywm/wlroots/pull/1864#issuecomment-586103504

Just don't rush.

I don't think you should open an issue here for a problem in a WIP pull request.

**Comment by xhebox** [comment]
Sorry for my rudeness :/.

But i do think it is not so releated the GRAB things in that PR. And the original PR has lots of comments now. Make a separate issue only makes thing more clear, that is my thought.

If you think this issue should be closed, leave a random emoji on the comment. I will close the issue soon after i saw it.

**Comment by xdavidwu** [comment]
It is of course related to input-method grab. It is  (and possibly will always be) the only situation that a client would grab keyboard from another client and send virtual keys back in a  "forwarding" fashion. It will be fixed in my sway side input-method grab pull request.

I think there is no need to leave issue here as it will possibly act like a heads-up to maintainers about a bug in a pull request that is not merged yet and the author is already aware of that.

**Comment by xhebox** [comment]
You are the contributor. Respect your perspective.
