### ISSUE TITLE
execmem

### ISSUE THREAD

**Issue by twoertwein** [swaywm/sway#5221]
SELinux complains that sway makes writeable memory executable. Since Xwayland does the same, I guess there is a good(?) reason for sway to do that. This is reproducible simply by starting sway.

```
$ journalctl -b | grep execmem
Apr 15 23:45:46 Arch audit[631]: AVC avc:  denied  { execmem } for  pid=631 comm="sway" scontext=user_u:user_r:user_t tcontext=user_u:user_r:user_t tclass=process permissive=1
Apr 15 23:46:19 Arch audit[696]: AVC avc:  denied  { execmem } for  pid=696 comm="Xwayland" scontext=user_u:user_r:user_t tcontext=user_u:user_r:user_t tclass=process permissive=1
```

```
$ swaymsg -t get_version
sway version 1.4
```

**Comment by ascent12** [comment]
There isn't a call to `mprotect` anywhere inside of sway or wlroots. I wonder if this is something one of our dependencies is doing, but it wouldn't be our "issue" and we can't do anything about it.
My first guess would've been Mesa, but any calls to `mprotect` there isn't using `PROT_EXEC`.

**Comment by emersion** [comment]
Closing because Sway per se doesn't do that.

**Comment by twoertwein** [comment]
disabling Xwayland solves both execmem events (`xwayland disable` in the sway config file) . I tried to follow https://unix.stackexchange.com/a/306174 to debug the source of execmem but Xwayland crashes when I start it outside of sway.

**Comment by martinetd** [comment]
Just because I can, a couple more ways to trace your "execmem" events without LD_PRELOAD:
 - strace can print backtraces (`strace -e mmap -k -f -o logfile sway` and search within log file, then search within the log file for "PROT_WRITE|PROT_EXEC"
 -  gdb can do conditional as well (`catch sys mmap` then `cond 1 ($rdx & 0x6) == 0x6` (rdx contains 3rd argument to mmap i.e. prot, and 0x6 is PROT_WRITE|PROT_EXEC)), but you need to gdb from another computer or use wayland/x11 backend as drm sway + gdb will get your computer stuck unless you're extra careful
 - (I'm sure bpftrace could do the best of both words e.g. give backtraces only for 'correct' mmaps but it looks broken for me right now, something else to look at...)

Anyway, the two write-exec mappings I can see on my laptop are:

```
347613 mmap(NULL, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f478ae20000
 > /usr/lib64/libc-2.31.so(__mmap+0x26) [0xfc5e6]
 > /usr/lib64/libglapi.so.0.0.0(u_execmem_alloc+0xc6) [0x194c6]
 > /usr/lib64/libglapi.so.0.0.0(entry_generate+0x2d) [0x18c2d]
 > /usr/lib64/libglapi.so.0.0.0(stub_find_dynamic+0xb1) [0x19141]
 > /usr/lib64/libglapi.so.0.0.0(_glapi_get_proc_address+0x44) [0x18f04]
 > /usr/lib64/libEGL_mesa.so.0.0.0(eglGetProcAddress+0x4f) [0x104df]
 > /usr/lib64/libGLdispatch.so.0.0.0(FixupDispatchTable+0x41) [0x41601]
 > /usr/lib64/libGLdispatch.so.0.0.0(__glDispatchMakeCurrent+0xb7) [0x41e07]
 > /usr/lib64/libEGL.so.1.1.0(InternalMakeCurrentDispatch+0x49) [0x3b79]
 > /opt/wayland/lib64/libwlroots.so.5(wlr_egl_init+0x6f9) [0x28646]
 > /opt/wayland/lib64/libwlroots.so.5(wlr_renderer_autocreate+0x13f) [0x2cd3c]
 > /opt/wayland/lib64/libwlroots.so.5(init_drm_renderer+0xb7) [0x35082]
 > /opt/wayland/lib64/libwlroots.so.5(wlr_drm_backend_create+0x2c5) [0x2f08b]
 > /opt/wayland/lib64/libwlroots.so.5(attempt_drm_backend+0x91) [0x2d4fd]
 > /opt/wayland/lib64/libwlroots.so.5(wlr_backend_autocreate+0x3e0) [0x2db28]
 > /opt/wayland/bin/sway(server_privileged_prepare+0x10a) [0x5338ba]
 > /opt/wayland/bin/sway(main+0x8c0) [0x532690]
 > /usr/lib64/libc-2.31.so(__libc_start_main+0xf1) [0x27041]
 > /opt/wayland/bin/sway(_start+0x2d) [0x43031d]
```

```
347661 mmap(NULL, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0063638000
 > /usr/lib64/libc-2.31.so(__mmap+0x26) [0xfc5e6]
 > /usr/lib64/libglapi.so.0.0.0(u_execmem_alloc+0xc6) [0x194c6]
 > /usr/lib64/libglapi.so.0.0.0(entry_generate+0x2d) [0x18c2d]
 > /usr/lib64/libglapi.so.0.0.0(stub_find_dynamic+0xb1) [0x19141]
 > /usr/lib64/libglapi.so.0.0.0(_glapi_get_proc_address+0x44) [0x18f04]
 > /usr/lib64/libEGL_mesa.so.0.0.0(eglGetProcAddress+0x4f) [0x104df]
 > /usr/lib64/libGLdispatch.so.0.0.0(FixupDispatchTable+0x41) [0x41601]
 > /usr/lib64/libGLdispatch.so.0.0.0(__glDispatchMakeCurrent+0xb7) [0x41e07]
 > /usr/lib64/libEGL.so.1.1.0(InternalMakeCurrentDispatch+0x49) [0x3b79]
 > /usr/bin/Xwayland(xwl_glamor_gbm_init_egl+0x105) [0x52475]
 > /usr/bin/Xwayland(xwl_glamor_init+0x35) [0x51c45]
 > /usr/bin/Xwayland(xwl_screen_init+0x6e9) [0x47409]
 > /usr/bin/Xwayland(AddScreen+0xda) [0x17a0ca]
 > /usr/bin/Xwayland(InitOutput+0xf1) [0x49f41]
 > /usr/bin/Xwayland(dix_main+0x193) [0x17dd23]
 > /usr/lib64/libc-2.31.so(__libc_start_main+0xf1) [0x27041]
 > /usr/bin/Xwayland(_start+0x2d) [0x4696d]
```

The first one doesn't have anything to do with Xwayland so I'm surprised it would go away for you, but both are the same `_glapi_get_proc_address` call in glapi, you should take it up to them if you care (but it definitely looks like it's on purpose, I mean, `u_execmem_alloc` can't really get more explicit... Now why do they need that I have no idea.)

Anyway as emersion said not-sway's-bug.

**Comment by twoertwein** [comment]
@martinetd cool, thank you very much!

I fully understand that it is not a sway bug :)
