### ISSUE TITLE
Sway 1.4 - Application launch from config file not reading all env variables

### ISSUE THREAD

**Issue by apiraino** [swaywm/sway#5330]
Sway Version: 1.4
Ubuntu 19.10

I launch Firefox from a shortcut command defined in the config file, relevant snippet:

`bindsym $mod+F5 exec "GDK_BACKEND=wayland MOZ_ENABLE_WAYLAND=1 /opt/firefox/firefox -P profile1"`

I use a WebExtension in Firefox that loads a file from the filesystem. The WebExtension looks for is config file in $ENV_VAR and - if not present - fallback to searching in `~./content-dir`. 

$ENV_VAR is set in my shell (in .bashrc) and the required content for the extension is there. When I start Firefox from the Sway shortcut $ENV_VAR seems to be not set because the extension complain about not finding its data.

If I start Firefox from the command line using exactly the command in the shortcut defined above, $ENV_VAR is found and everything works.

What could possibly be? Does it depend on how Sway is run after login?

**Comment by Xyene** [comment]
The variables set in `~/.bashrc` are local to your shell session (and its children). Sway will not read your `.bashrc` and execute it; those variables need to be present in the environment in which Sway is executed.

**Comment by apiraino** [comment]
ahh right @Xyene thanks, I forgot about that. You suggestion had me investigate a bit more on how I launch Sway after logging in from lightdm, with this file:
```
$ cat /usr/share/wayland-sessions/sway.desktop
[Desktop Entry]
Version=1.0
Name=Sway
Comment=Sway
Exec=/usr/bin/sway
Type=Application
```

Ther's no clear way I can load some env variables before starting Sway. The only suggestion that works is [here](https://github.com/canonical/lightdm/issues/63#issuecomment-497987787) but if possible I'd like to avoid duplicating settings from .bashrc into another file.

Probably my question is - how to properly launch Sway lightdm or gnomedm? Cutting out the login manager is not a viable option for me.

**Comment by Xyene** [comment]
Using the suggestion you linked, you presumably can just source the `.bashrc` in the bootstrap script. However, if the environment variables are specified at Sway's startup, they will be present for all Bash shells spawned under Sway regardless of their `.bashrc` contents (environment variables are inherited on fork), so you should be able to just specify them once in the bootstrap script.

I'm going to close this issue since this tracker is not a good place to get setup support; if you still need help I'd encourage you to join #sway on IRC (there are a lot of knowledgeable people there).
