### ISSUE TITLE
PhpStorm dropdown menu weirdness

### ISSUE THREAD

**Issue by setpill** [swaywm/sway#5347]
## Sway Version:

```
$ swaymsg -t get_version
sway version 1.4
```

## Debug Log:

https://gist.github.com/setpill/128403eee1e7ff9c85f3bfa4fe33d1a5

## Reproduce:

1. Open PhpStorm (NB: make sure to set `_JAVA_AWT_WM_NONREPARENTING=1`)
2. Open File menu
3. Open Open Recent submenu
 
Now the File menu stops working (no longer responds to mouse events). The Open Recent submenu does work.

These are some interesting complications:

* The File menu stays open and in the same position regardless of what happens to the main application window.
* When moving the main window out from "under" the File menu, the File menu starts working again.
* The File menu stays open, in the same position and visible even when switching to a different workspace.
* The File menu *does not start working* when switching workspaces. But it can keep working.

**Comment by Xyene** [comment]
Are you able to reproduce this issue in another Wayland compositor, like Weston or GNOME (Wayland, not X11)? Running Jetbrains IDEs through Xwayland is pretty finicky, so the first order of business would be to verify that the issue is in sway, rather than in Xwayland or Java's windowing stack.

**Comment by setpill** [comment]
Cannot reproduce in Weston - while the dropdown menu has other issues going on, it doesn't become inactive like in sway.

**Comment by setpill** [comment]
I have managed to create a reduced debug log that only contains the lines from right before I opened the dropdown menu to just after I closed it (while triggering the "no response" state). Hopefully that helps.

**Comment by setpill** [comment]
There seems to be a possibly related issue with dialogs and modals. Mouse interactions don't work with them as long as they overlap the main window, but moving them over another application fixes them.

**Comment by Xyene** [comment]
Could you try building wlroots with https://github.com/swaywm/wlroots/pull/2219 applied?

```
$ cd /path/to/wlroots; curl -L https://github.com/swaywm/wlroots/pull/2219.diff | patch -p1
```

It's a hack (and a bad one that shouldn't be necessary), but it does resolve the issue with Jetbrains dialogs.

**Comment by Xyene** [comment]
I had a chance to look into this yesterday, and I think I understand why it happens. https://github.com/swaywm/wlroots/pull/2219 does indeed fix dialog issues in at least PyCharm and Android Studio, but it is a separate issue from the menus becoming inactive.

The reason I was unable to reproduce this initially is that habitually, I _drag_ & release menus over the entry I want to select, rather than click multiple times. The issue does not manifest in that case; you need multiple clicks.

PhpStorm uses unmanaged Xwayland surfaces for its menus. When you click _File_, the menu that pops up is one unmanaged surface. When you hover over _Open Recent_, the second-level menu that opens is another unmanaged surface. When the _Open Recent_ surface opens, it gains input (keyboard) focus.

The problem is when the submenu closes. In particular, it's this bit of code:

https://github.com/swaywm/sway/blob/d71fed95da5af5a489d2ea68b87a306ddc4d238d/sway/desktop/xwayland.c#L97-L104

When the submenu closes, presumably the main menu should gain focus. However, `seat_get_focus_inactive` returns the `struct sway_node` of the main IDE window, rather than of the main menu. I believe this is because of this code:

https://github.com/swaywm/sway/blob/d71fed95da5af5a489d2ea68b87a306ddc4d238d/sway/desktop/xwayland.c#L78-L83

`seat_set_focus_surface` does not push the surface onto the focus stack that `seat_get_focus_inactive` peeks at, since the focus stack is a list of `struct sway_node`. As far as I understand it, unmanaged Xwayland surface are _not_ represented as nodes.

Removing that block of code makes PhpStorm menus work correctly under mouse input, but (as expected) breaks keyboard input into the main menu once the submenu closes. So it's not a fix by itself.

/cc @emersion from git blame. I'm not too familiar with this code, but from digging into this it seems like what's needed is for the focus stack to also track unmanaged Xwayland surfaces. What do you think? Is there anything simpler we could do?

**Comment by emersion** [comment]
>As far as I understand it, unmanaged Xwayland surface are not represented as nodes.

Correct.

>Removing that block of code

Do you mean the `wlr_xwayland_or_surface_wants_focus` block? "or" here means override-redirect, so this could should handle surfaces that are typically menus.

* * *

Hmm.

- Xwayland unmanaged windows are not necessarily parented. This makes it complicated to check for menus belonging to a main window.
- Should we always give focus to the top-most Xwayland unmanaged window?

**Comment by Xyene** [comment]
> Do you mean the `wlr_xwayland_or_surface_wants_focus` block?

Sorry, I should've been more clear -- I meant the `if (previous) { ... }` block from the first snippet.

> Xwayland unmanaged windows are not necessarily parented.

Right, I think the closest hierarchy information we have is the order of `root->xwayland_unmanaged`, but as I understand it that's *all* Xwayland unmanaged windows, not just the ones from the current app. I guess it doesn't really matter though, since there wouldn't be a distinction in X.

> Should we always give focus to the top-most Xwayland unmanaged window?

I can give this a try. I briefly tried it before posting the first comment and it didn't immediately work, but it 5am and I didn't try too hard. As long as `root->xwayland_unmanaged` is not empty, and the currently unmapped surface had focus, give focus to the next item in `root->xwayland_unmanaged`. Maybe it should also filter by unmanaged surfaces from the same PID so we don't make surprising focus switches.
