### ISSUE TITLE
Broken pipe with kitty terminal emulator

### ISSUE THREAD

**Issue by akvadrako** [swaywm/sway#5363]
I (and others) have a rather long standing issue with the kitty terminal emulator and sway. It was reported in https://github.com/kovidgoyal/kitty/issues/2329 but the author suspects it's a sway bug.

Sometimes kitty dies with the error
> Wayland: fatal display error: Broken pipe

It seems like sway is actually closing the socket. Around the same time I see a possible related message in sway's debug output:
>[wayland] error in client communication (pid 136663)

It looks like it's happening after kitty makes 7500 wayland calls like `wl_display@1.delete_id`.

I don't know enough about the wayland protocol to know which side is buggy. Sway doesn't give much info about what the error in client communication might be, so I thought I would ask here if it looks like a sway limitation and if it's on purpose.

* Sway Version: 1.4-dffc184a (Mar 30 2020, branch 'master')
* Debug Log: https://gist.github.com/akvadrako/c5f188579c5ea3b9ffc61a6b76904b03

**Comment by progandy** [comment]
That message comes from [libwayland-server](https://github.com/wayland-project/wayland/blob/e7d88f35eb89cf0cc77cbddd834cacc63683a9cc/src/wayland-server.c#L447). Maybe it would be useful to set up a [protocol logger](https://wayland.freedesktop.org/docs/html/apc.html#Server-structwl__display_1a4dc118c686e362aba0b3c6c8874efc3d) in sway?

**Comment by emersion** [comment]
Can you provide a `WAYLAND_DEBUG=1` log of your client?

```sh
WAYLAND_DEBUG=1 your-client >client.log 2>&1
# Then reproduce the bug
```

**Comment by martinetd** [comment]
Sway will close the socket if there is a protocol violation or something it can't cope with.

There's nowhere close to enough logs in the gist there but in the kitty issue you linked https://gist.githubusercontent.com/Ma27/4190b3fd56e664c024ab8ffe0f44192b/raw/315bbafc999f80a92651bc1510dd817f7bb234f0/log.txt looks pretty horrible -- I don't see a protocol violation but kitty really shouldn't be trying to create so many callback frames, if we're not saying frame done it's because the kitty isn't being displayed and we don't want to waste cpu cycles on it, it should keep doing whatever it want internally but not try to redraw.

Taking the last bit of the log it looks like wayland reused the same id that just got deleted, do you have the same behaviour in your full logs all the time?
```
[4153773.716] wl_display@1.delete_id(35782)
[023 22:03:04.326821] No render frame received in 0.25 seconds, re-requesting at: 3459.004271
[4153773.791]  -> wl_surface@21.frame(new id wl_callback@35782)
[4153773.801]  -> wl_surface@21.commit()
[023 22:03:04.326910] [glfw error 65544]: Wayland: fatal display error: Broken pipe
```
AFAIU this should be valid so the bug could be anywhere.. Other possibility could be we don't like getting a new frame callback when we're trying to finally answer one, but while it's not pretty I don't really see why.
Either way it wouldn't be a problem if kitty would just wait for frame callback instead of spamming us, I've just tried and couldn't reproduce but it's pretty horrible with the kitty window freezing for a while when I switch back during the time it takes to catch up on the cleanup for all these frames...

**Comment by emersion** [comment]
Ah, missed the (stripped) WAYLAND_DEBUG=1 logs. Please never strip logs.

**Comment by emersion** [comment]
Maybe kitty fills the wayland socket buffer with requests.

**Comment by akvadrako** [comment]
Above I have the snippet of the output from WAYLAND_DEBUG=1. From the other bug's original reporter there is a longer log here: https://gist.githubusercontent.com/Ma27/4190b3fd56e664c024ab8ffe0f44192b/raw/315bbafc999f80a92651bc1510dd817f7bb234f0/log.txt

I have uploaded my full log here: https://gist.github.com/akvadrako/c5f188579c5ea3b9ffc61a6b76904b03/raw/a8dca60c50465e21588b29368779231809469cb9/kitty-wayland-debug-full-log.txt

**Comment by emersion** [comment]
Well, this is clearly a kitty bug. It shouldn't request that many callbacks. Good thing we disconnect the client.

**Comment by akvadrako** [comment]
Thanks. It might be helpful if sway's error message was a little more complete, like "too many callbacks" if there is a hardcoded callback limit.

**Comment by emersion** [comment]
Closing the connection is libwayland's doing here.
