### ISSUE TITLE
contrib/inactive-window-transparency.py keeps last active window on other monitor active

### ISSUE THREAD

**Issue by evils** [swaywm/sway#5372]
* Sway Version: `1.4`

contrib/inactive-window-transparency.py (as included in tag `1.4` and currently on master)
does not make inactive windows on other monitors transparent if they were previously active

**Comment by Xyene** [comment]
This appears to be intentional behavior rather than a bug, which was introduced in https://github.com/swaywm/sway/commit/6235423544b7e3feab5a6775cd4d06a3b171dd54.

https://github.com/swaywm/sway/blob/848a6fdb21473bfaec32de4a546b79ab53843771/contrib/inactive-windows-transparency.py#L22-L24

The utilities under `contrib/` are extra-zero-warranty community-maintained, so if you'd like to change the behavior, feel free to send in a pull request. Preferably, I'd say changing this behavior should be behind a flag, since it seems (by the existence of this issue) that the correct behavior here is subjective.

I'm going to go ahead and close this issue (due to the extra-zero-warranty part), but I'd be happy to review a pull request.
