### ISSUE TITLE
Maximising windows

### ISSUE THREAD

**Issue by WhyNotHugo** [swaywm/sway#5397]
GTK behaves weird when full-screened: the main controls for windows are hidden (e.g.: the "Save" button in save dialog and other critical elements, like the "Confirm" button in some UIs).

[I brought this up](https://gitlab.gnome.org/GNOME/gtk/-/issues/2795) at the GTK3 issue tracker, but apparently, dialogs behave this way by design since they're intended to be used on floating window managers only and not tiling ones (and the users of these know to maximise this window and not full-screen them, I guess?).

The conclusion is that windows have two properties: full-screen and maximised. While they seem to mean the exact same thing, the difference is very specific and mostly a technical one. The important distinction is that full-screen windows hide their controls by default (again, like the "Open" button in a file chooser dialog, which I think is extremely stupid, since that's the main CTA).

I'm wondering if it's possible to "maximise" a window in sway. Potentially, I'd like to bind a hotkey to maximise windows, so I can have them "fullscreen", but with them not hiding important UI elements.

I don't see any mentions of maximisation on the docs; is such a thing possible, or merely not implemented on swaywm? (I guess it would seem redundant, since both concepts _seem_ to be the same unless you look at how GTK behaves)

**Comment by Xyene** [comment]
[Here's](https://gist.github.com/Xyene/c4f2034a138a96f3aef2cb34de1d4792) a small patch you can apply locally that switches Sway's `fullscreen` command to maximize rather than fullscreen. For my *personal* usage I like this hack since any applications I *really* want the fullscreen mode of, I can tap F11 for.

I think what, if anything, to do about this in Sway proper warrants further discussion, though.

---

Related:

* [i3's proposal for a `maximize` command](https://github.com/i3/i3/issues/2107)
* [Extended Window Manager Hints spec](https://developer.gnome.org/wm-spec/), specifically the section on `_NET_WM_STATE_FULLSCREEN`

The i3 issue is marked as `accepted` and seems popular (sometimes heated), but has not been implemented since it was filed (2015).

The EWMH guidelines are for X, but I think application behavior is analogous on Wayland. It states:

> `_NET_WM_STATE_FULLSCREEN` indicates that the window should fill the entire screen and have no window decorations. Additionally the Window Manager is responsible for restoring the original geometry after a switch from fullscreen back to normal window. For example, a presentation program would use this hint. 

Sway only sends fullscreen notifications through [xdg-shell](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/master/stable/xdg-shell/xdg-shell.xml#L785). The GTK3 file open dialog _does_ have its "Open" button in its window decoration, and GTK3 _is_ hiding its window decorations as requested by Sway, so everything sounds like its working correctly to me here &mdash; even if the resulting user experience is suboptimal.

Visually, a `maximize` command should act as if the selected window was in a brand new workspace (that is, the bar should still show). So, it's not quite what you want here because as you state in the linked thread, since keeping mental track of two similar-but-not-quite keybindings is a bit icky.

Apart from a `maximize` command (which may be useful in its own right), one proposal here would be to add a `fullscreen_mode [fullscreen|maximize|smart]` option to control this behavior. `fullscreen` would be the current behavior, `maximize` would be the behavior as with my linked patch, and `smart` could be something in-between like maximizing only dialogs. i3 does not have such an option; I'm unsure about whether that's a prerequisite to having it in Sway.

**Comment by WhyNotHugo** [comment]
> Apart from a `maximize` command (which may be useful in its own right), one proposal here would be to add a `fullscreen_mode [fullscreen|maximize|smart]` option to control this behavior. `fullscreen` would be the current behavior, `maximize` would be the behavior as with my linked patch, and `smart` could be something in-between like maximizing only dialogs. i3 does not have such an option; I'm unsure about whether that's a prerequisite to having it in Sway.

`smart` is basically what my end goal with be: fullscreen regular windows, but maximise dialogs. Though I wouldn't mind having some local glue code that does some of the work at first.

This patch seems like a magnificent starting point, so I'll experiment with that patch when I get a free day or two :)

**Comment by emersion** [comment]
Maybe related https://github.com/swaywm/sway/pull/4255

**Comment by sprnza** [comment]
Hi there! Any update on this? Is there any chanses to have the patch adopted?

**Comment by tlestach** [comment]
Not sure, why this request cannot be granted. Even in a different way if this one does not fit the sway concept.

I personally wrote a script as a workaround https://gist.github.com/tlestach/6b46a777b36280b15e6e5da0e9b8c4db that (instead of maximizing a window) moves it to a separate workspace (that I do not use for anything else) and thus behaves as being maximized. To unmaximize the script moves the window back to its original workspace. Easy to use, feel free to tweak.

**Comment by sprnza** [comment]
Thanks @tlestach !

**Comment by nadir-yttrium** [comment]
Thank you for you script, @tlestach.

I really hope this will become default behaviour. It's so much less disorienting. Bspw is doing it that way as well.

**Comment by emersion** [comment]
i3 doesn't have this, so we won't be implementing it.

**Comment by WhyNotHugo** [comment]
How does GTK3 + i3 deal with this scenario though?  
Does GTK also misbehave the same way?

**Comment by pschmitt** [comment]
Here's another shell ipc script that "maximizes" a window by making it floating and resizing it to the size of the current output minus the height of waybar:

https://gist.github.com/pschmitt/909f880e8c7924fab056d42a3d30f9a5

**Comment by yenda** [comment]
> i3 doesn't have this, so we won't be implementing it.

i3 doesn't have this because i3 does the optimal thing in terms of user experience. One can already press F11 to get the app to fullscreen, i3 fullscreen is "maximize"

**Comment by emersion** [comment]
Sway has the same behavior as i3. Sway fullscreen is the same as i3 fullscreen.

We never promised anything.

**Comment by yenda** [comment]
> We never promised anything.

sorry I read it a few times but you are right it doesn't mean that was a promise from the developers/maintainer. Thank you for doing that btw it's very much appreciated!

> Sway has the same behavior as i3. Sway fullscreen is the same as i3 fullscreen.

I stand corrected, reading this thread and based on my experience so far with Chromium going fullscreen I was under the impression that it wasn't the case, but after further testing following your comment I think it's really Chromium and not sway that doesn't behave the same way.

**Comment by mkalinski** [comment]
I took a swing at another hack to implement this functionality. 😀 

It puts the focused window to a designated (hopefully empty) workspace, and returns it back after another call, just like the [first script here](https://github.com/swaywm/sway/issues/5397#issuecomment-797389841).

What it does differently, is that it spawns a placeholder window (using zenity, because that's what I have, but could be tweaked to use any window you can manipulate the title of), and uses swapping to return the "unmaximized" window not just to the previous workspace, but to exactly the place in the layout that it started in.

Because it must detect new windows being spawned, it's actually two scripts that must work together:
- [One for binding to a keymap](https://gist.github.com/mkalinski/400e0aec4eb7fcfc64cdb0b459995daa#file-sway-pseudo-maximize-toggle-sh)
- [One to put in an `exec` in sway config](https://gist.github.com/mkalinski/ec112091dc9aa1e9f5e039ed7dd4b1fe#file-sway-track-pseudo-maximize-placeholder-sh)

**Comment by closetruth** [comment]
This worked for me.
1. `swaymsg floating toggle, resize set width 100ppt height 97ppt` ,you can add to hotkey
2. `swaymsg layout tabbed` or `swaymsg layout stacking ` ,you also can add to hotkey

**Comment by w9n** [comment]
I ran into the same Sway mod+f issue with Chromium/Electron: the window becomes fullscreen-sized, but the app also enters fullscreen UI and hides tabs/address bar.

I made a small user-space workaround for this: wl-app-fullscreen strips only compositor-initiated FULLSCREEN state from xdg_toplevel.configure, while preserving real app fullscreen from F11 / DOM fullscreen.

Repo: https://github.com/w9n/wl-app-fullscreen

It is intentionally narrow: native Wayland apps, one launched program per proxy. If your goal is “Sway fullscreen size, but browser chrome stays visible,” this should match that workflow. Feedback or edge cases welcome.
