### ISSUE TITLE
Input devices with e.g. \r in its name are unconfigurable

### ISSUE THREAD

**Issue by wb9688** [swaywm/sway#5441]
I have a touchscreen that had a `\r` in its name when I got it, which caused it to not be configurable in Sway. Yes, that name shouldn't even contain a `\r` and meanwhile the Chinese manufacturer has made a custom firmware (that was only flashable using some Windows-only program that's still using Qt4…) for me that doesn't have a `\r` in its name. I still think it's a good idea for Sway to ignore characters like `\r`, which could be done with the following diff:

```diff
diff --git a/sway/input/input-manager.c b/sway/input/input-manager.c
index b900f666..912a2678 100644
--- a/sway/input/input-manager.c
+++ b/sway/input/input-manager.c
@@ -70,7 +70,7 @@ char *input_device_get_identifier(struct wlr_input_device *device) {
 
        char *p = name;
        for (; *p; ++p) {
-               if (*p == ' ') {
+               if (*p == ' ' || !isprint(*p)) {
                        *p = '_';
                }
        }
```

**Comment by Xyene** [comment]
Yes, I think this patch is a good idea, we shouldn't make devices unconfigurable just because the manufacturer messed up.

Could you please submit it as a pull request? Might be worth annotating that bit of code to state for future readers that there _are_, in fact, scary devices with non-printable characters in their name.
