### ISSUE TITLE
Blank grey screen where only mouse works after launch -- 

### ISSUE THREAD

**Issue by jlevers** [swaywm/sway#5449]
* Sway Version: `sway version 1.4-f9361ae3 (Jun 13 2020, branch 'master')`

* Debug Log: https://gist.github.com/jlevers/8fec1173129ab0632de1defd43228fe7#file-sway-log

* Configuration File: my config is identical to the default, except that I replaced `alacritty` with `gnome-terminal`. Just to be thorough, it's visible here: https://gist.github.com/jlevers/8fec1173129ab0632de1defd43228fe7#file-config

Steps I took to reproduce:
* Log out of my current user session with `pkill -u <username>`.
* Switch to a fresh TTY.
* Launch sway with `sway -d 2> ~/sway.log
* Reach a blank grey screen, where mouse can move
* Press `mod+Enter` to launch a terminal, and nothing happens.
* Switch to another TTY and kill sway with `htop` (because `mod+Shift+q` doesn't do anything)

I read the entry in the FAQ about this issue, but I'm confident that my config is correct enough that launching the terminal should work.

When I hit `mod+Enter`, some info about creating a `gnome-terminal` process appears in the logs, but I can't see the `gnome-terminal` process in `htop` and I can't see the terminal itself in `sway`. The lines related to launching `gnome-terminal` begin here: https://gist.github.com/jlevers/8fec1173129ab0632de1defd43228fe7#file-sway-log-L730

**Comment by Xyene** [comment]
Sorry for not getting around to this ticket sooner, but I'm going to go ahead and close this issue since a lot has changed on the wlroots side (where the error `eDP-1: Atomic commit failed (modeset): Permission denied` occurs) since Sway 1.4.

If you find that the issue persists in Sway/wlroots master, please file a ticket against https://github.com/swaywm/wlroots, with fresh logs.
