### ISSUE TITLE
Lack of vertical alignment for swaybar

### ISSUE THREAD

**Issue by beanaroo** [swaywm/sway#554]
I noticed bar elements aren't vertically centered:
![sway](https://cloud.githubusercontent.com/assets/1748909/14128269/e95707d6-f67b-11e5-9828-432667ae9cdc.png)

i3 version for reference:
![i3](https://cloud.githubusercontent.com/assets/1748909/14128271/ef47755e-f67b-11e5-9886-9ba648c5e41d.png)

**Comment by ke7ofi** [comment]
By the way (maybe this should be a separate issue), @SirCmpwn, would it be possible to add a "true center" (and maybe left) alignment so that swaybar sections wouldn't all have to be right-aligned? This is distinct from the current align-within-maximum-width option.

**Comment by SirCmpwn** [comment]
I'm not entirely open to that idea right now, but if you make a seperate issue maybe it'll happen in the future.

**Comment by mikkeloscar** [comment]
@beanaroo can you post your configs so I can try to replicate the issue?

**Comment by beanaroo** [comment]
I have my i3 configuration up on github [over here.](https://github.com/beanaroo/dotfiles/tree/master/.config/i3).

I did not make a backup of the sway config, but will post as soon as I can.

**Comment by mikkeloscar** [comment]
Strange, it looks pretty much aligned here:

![swaybar](https://cloud.githubusercontent.com/assets/128566/14899317/bc89d914-0d8b-11e6-9b52-422c149d2c95.png)

**Comment by beanaroo** [comment]
interesting, I'll try again today.

**Comment by beanaroo** [comment]
@mikkeloscar After reinstalling Arch and sway, the status line is now vertically centered. The workspace indicators, however, are not. Unlike the screenshot you posted. This is obvious when a binding mode indicator is present, which is centered.

I tested multiple fonts, sizes and heights just to be sure.

**Comment by sullome** [comment]
Well, checked this, because It looks like it was not centered for me.
Actually it IS vertically centered, but: it is centered for your swaybar font. And it is not possible to use pango in workspace icons, so your swaybar font is font with icons. I think that you use another font for text on your swaybar (for the date, for example), using pango, just as I am. Second, normal font is not vertically centered — because it is aligned in the other way, it's baseline is equal to the baseline of default swaybar font (which is font with icons).
Checked with one font for all bar — and yes, everything is vertically centered.
So it is not a swaybar bug.
