### ISSUE TITLE
layer-shell surfaces aren't capable of constraining the pointer.

### ISSUE THREAD

**Issue by dmorilha** [swaywm/sway#5634]
Hello there, let me start by saying this is a very exciting time to be getting aware of sway! I went through the code and is very well written! nice!

I am an experienced Linux user and I am finally trying to move away from X11 on all my devices after realizing how better things are with wayland/sway.

While trying to mush wlroots examples together, I realized the layer-shell example doesn't go well with the pointer-constraint protocol. What I would like to do is to be able to lock the cursor if it goes beyond the viewport, and subsequently release it.

I tried various approaches on how to circumvent the problem but I was finally able to make the both nonstandard protocols work together when I removed this `if` statement on `sway/input/cursor.c` : https://github.com/swaywm/sway/blob/master/sway/input/cursor.c#L1294

I looks like overlays never have the "proper focus"... Is this a bug, or intentionally designed? Would I be able to constrain the cursor into an overlay in a different way?

**Comment by emersion** [comment]
We could extend the check in `handle_pointer_constraint` to lookup `seat->focused_layer` in addition to `seat_get_focus`.

**Comment by emersion** [comment]
Or introduce a new `seat_get_focus_surface` that returns a `wlr_surface` to simplify our logic.

**Comment by Jaakkonen** [comment]
I came across this behavior when trying to implement a virtual KVM using `wlr-virtual-pointer-unstable-v1` and `virtual-keyboard-unstable` to do input on controlled device and using `wlr-layer-shell-unstable-v1` and `pointer-constraints-unstable-v1` to detect when mouse moves to 1px wide window on edge of screen and to stop pointer there and use its relative events to move pointer on controlled device.
I'll try make a PR adding support for this case so that this topic can be discussed about with concrete runnable code and possibly even merged :)
