### ISSUE TITLE
Right border renders incorrectly when left border is offscreen

### ISSUE THREAD

**Issue by FreeFull** [swaywm/sway#5643]
- **Sway Version:** 1.5-6991ac8c (Aug 16 2020, branch 'master')

- **Debug Log:** https://gist.github.com/FreeFull/dacb4be28e01048b87b35a19fb878edb

- **Configuration File:** Default sway config.

- **Description:**
When a floating window's left border overlaps with the left edge of the screen or is entirely off the left edge, the right border's rendering will be off by one pixel to the left. I have only tested this with a single monitor. Dragging the top, right or bottom border of the window offscreen doesn't seem to make any of the other borders misrender.

**Comment by dimitris-triantafyllidis** [comment]
Hi, I just made a pull request for this. It is due to negative floating point expressions being rounded towards zero. The right border is actually correctly rendered, while all the other borders are one pixel to the right! The same type of problem exists when the container is partially over the top edge of the screen.
