### ISSUE TITLE
feature request: alternative to `swaymsg -t get_config` that is a parsed JSON structure

### ISSUE THREAD

**Issue by jokeyrhyme** [swaywm/sway#5671]
Howdie, I hope you are well

From `man swaymsg`:

>        get_config
>           Gets a JSON-encoded copy of the current configuration.

But, for me at least, it just returns `{"config":"..."}` with the full text content of ~/.config/sway/config without any useful parsing

It would be very useful to have a `swaymsg -t get_config_json` or something with a parsed data structure, hopefully as close to how `sway` understands the content as possible

My immediate use case is to quickly list current keybindings, but I imagine this could make other tasks easier, too, such as scripting style changes that take the current styles as inputs, highlighting windows that match assignment rules, etc

**Comment by Geo25rey** [comment]
I think I have a good idea how to implement this. I don't think it's necessary to add a new command since there is already the idea of raw and pretty printing of the IPC JSON responses. Pretty printing can print out the literal config file line by line, and the raw printing can print out the JSON representation.

I would like some input on some things I'm unsure of below.

1. Should comments be part of the JSON response from the IPC server?

2. Should comments be ignored in pretty printing, if they are in the response?

3. Should the JSON representation of the config just be a list of each line's interpretation? (Ex. [ { type: "bindsym", keys: [ "Mod4" ], command: {...} } ] ) An alternative is to make a list for each command type, like this: { bindsym: [ { keys: [ "Mod4" ], command: {...} } ] }.

**Comment by jokeyrhyme** [comment]
For my use case, I'm not terribly interested in comments, but that's just me, would we dangle a "comment" property from any node that we thought the comment related to?

For my use case, either representation could work, although if `swaymsg` gives us an array of parsed lines, then we can derive the command-grouped map format from that, however we cannot do this in reverse
So, I think the array of parsed lines is more flexible

I have some bindsym lines and some bindsym blocks (with `{}`) in my config, so a bindsym block could either turn into multiple bindsym lines (the easiest for my use case) or a bindsymblock entry that has child entries (also workable)

**Comment by Geo25rey** [comment]
I just looked in the i3 IPC protocol documentation and the current implementation in Sway is how i3 does it. This feature might get NACKed because of this. @RedSoxFan your thoughts?

**Comment by jokeyrhyme** [comment]
Well, I didn't bring my own PR, and this is not my project, so completely up to you :)

I can figure out my use case with some scripts, was just pondering out loud in case we came up with something that worked for more than just me :)

**Comment by RedSoxFan** [comment]
> @RedSoxFan your thoughts?

For bindings specifically, I would prefer #5561, which is not likely to be merged due to ddevault's NACK.

As for the config in general, I don't forsee that being accepted either. I think the bindings has a stronger use case and that already has a NACK.

Since the primary focus of this appears to be bindings, I'm going to close this and direct you towards #5561.  You are also welcome to maintain any forks or local patches.
