### ISSUE TITLE
adaptive sync does not work on Thinkpad T14s Ryzen 4750U

### ISSUE THREAD

**Issue by bernharl** [swaywm/sway#5706]
Before you ask: Yes, this laptop does for some reason have Freesync support. It works on Windows. 
- **Sway Version:** v1.5
- **Debug Log:**
  - https://gist.github.com/bernharl/9f72db7016ca2d610b7f49c35cc331fc
- **Description:**
  - Put `output * adaptive_sync on' in the config file `
  - Run `swaymsg -t get_outputs`
  - This returns  
```Output eDP-1 'Chimei Innolux Corporation 0x14F2 0x00000000'
  Current mode: 1920x1080 @ 60.000999 Hz
  Position: 320,1440
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    640x480 @ 60.000999 Hz
    800x600 @ 60.000999 Hz
    1024x768 @ 60.000999 Hz
    1280x720 @ 60.000999 Hz
    1280x800 @ 60.000999 Hz
    1440x900 @ 60.000999 Hz
    1280x1024 @ 60.000999 Hz
    1680x1050 @ 60.000999 Hz
    1920x1080 @ 60.000999 Hz

**Comment by Emantor** [comment]
From the logfile:
```
00:00:00.273 [DEBUG] [backend/drm/drm.c:524] Failed to enable adaptive sync: connector 'eDP-1' doesn't support VRR
```
This is the kernel DRM driver telling us that VRR is not supported for the connector, nothing we can do within sway to change this.
I suspect that the kernel driver currently still only supports DisplayPort and neither embedded DisplayPort nor HDMI are supported.

**Comment by bernharl** [comment]
So in this case that would be the AMDGPU driver?

**Comment by bernharl** [comment]
It seems the driver should support eDP VRR, as seen here:
https://lists.freedesktop.org/archives/amd-gfx/2019-February/031251.html

I should probably file a bug report over there then.

**Comment by Emantor** [comment]
> So in this case that would be the AMDGPU driver?

Yes.


> It seems the driver should support eDP VRR, as seen here:
> https://lists.freedesktop.org/archives/amd-gfx/2019-February/031251.html
> 
> I should probably file a bug report over there then.

Looks like the current issue tracker is on the [freedesktop gitlab](https://gitlab.freedesktop.org/drm/amd/-/issues).

**Comment by bernharl** [comment]
Great, thanks!

**Comment by IDDT** [comment]
Since this is one of the top search results for this problem, I'll leave the solution here.

The screen EDID doesn't specify VRR configuration, therefore AMDGPU doesn't pick it up. Lenovo injects its own EDID with configured VRR support. The idea is to dump the EDID from Windows with something like [CRU](https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU) and inject it into Linux. It worked for T14 gen 3 AMD with Arch.

The basic steps are:
- Dump EDID bin file and place it into `/usr/lib/firmware/edid/my-edid.bin`.
- Add `drm.edid_firmware=eDP-1:edid/my-edid.bin"` to kernel boot params.
- Add `/usr/lib/firmware/edid/my-edid.bin` into `FILES` inside `etc/mkinitcpio.conf`.
- Regenerate initramfs and bootloader. In my case `mkinitcpio -P` && `grub-mkconfig -o /boot/grub/grub.cfg`.
- Reboot and confirm it's working with `swaymsg -t get_outputs` or read errors with `dmesg | grep edid`.

Sources: [1](https://wiki.archlinux.org/title/Variable_refresh_rate#Sway), [2](https://wiki.archlinux.org/title/Variable_refresh_rate#Change_VRR_range_of_a_FreeSync_monitor), [3](https://wiki.archlinux.org/title/kernel_mode_setting#Forcing_modes_and_EDID), [4](https://www.reddit.com/r/Amd/comments/5iux1q/updated_tutorial_on_increasing_and_decreasing/), [5](https://wccftech.com/amd-freesync-hack-expands-refresh-rate-range/)

**Comment by boredland** [comment]
@bernharl have you ever created an upstream issue in the freedesktop repo? I have a 1st gen t14s like you and am wondering if I still should to go down the workaround route @IDDT explained.

**Comment by boredland** [comment]
> * Add `drm.edid_firmware=eDP-1:edid/my-edid.bin"` to kernel boot params.

I am getting this after following your steps. No idea what that could be: 

```
[    0.000000] Command line: BOOT_IMAGE=/@/boot/vmlinuz-6.9-x86_64 root=UUID=daf55f52-c8d8-45e7-bfb4-bad14011d24b rw rootflags=subvol=@ quiet cryptdevice=UUID=8c1e0266-ea8a-4484-815a-25eccd7ec990:luks-8c1e0266-ea8a-4484-815a-25eccd7ec990 root=/dev/mapper/luks-8c1e0266-ea8a-4484-815a-25eccd7ec990 apparmor=1 security=apparmor resume=/dev/mapper/luks-2aa0d5e1-a870-4903-b63d-018c7eb48ea0 udev.log_priority=3 drm.edid_firmware=eDP-1:edid/my-edid.bin
[    0.042854] Kernel command line: BOOT_IMAGE=/@/boot/vmlinuz-6.9-x86_64 root=UUID=daf55f52-c8d8-45e7-bfb4-bad14011d24b rw rootflags=subvol=@ quiet cryptdevice=UUID=8c1e0266-ea8a-4484-815a-25eccd7ec990:luks-8c1e0266-ea8a-4484-815a-25eccd7ec990 root=/dev/mapper/luks-8c1e0266-ea8a-4484-815a-25eccd7ec990 apparmor=1 security=apparmor resume=/dev/mapper/luks-2aa0d5e1-a870-4903-b63d-018c7eb48ea0 udev.log_priority=3 drm.edid_firmware=eDP-1:edid/my-edid.bin
[    4.253683] amdgpu 0000:06:00.0: [drm] *ERROR* Invalid firmware EDID "edid/my-edid.bin"
```
