### ISSUE TITLE
Parent container headers don't precisely track position of children

### ISSUE THREAD

**Issue by Xyene** [swaywm/sway#6012]
Continuing from https://github.com/swaywm/sway/pull/5981#issuecomment-775789768.

Video of issue:

https://user-images.githubusercontent.com/1403503/107462992-4af0e880-6b2b-11eb-8de5-58c9127124b2.mp4

There are some frames in the first half that look like this:

![image](https://user-images.githubusercontent.com/1403503/107463044-6825b700-6b2b-11eb-90ad-22c8e3e04756.png)

The issue only appears to occur if the interactive resize is triggered from the left half of the child container used in the video. The issue also occurs if the right half of the right child is used, but not the right. So, I suspect the issue only triggers if the child width changes as well as the height &mdash; if only the height changes, things work fine. (Perhaps the updates land in different transactions?)

/cc @kennylevinsen

**Comment by kennylevinsen** [comment]
It doesn't reproduce under txn-wait, or with slow-ack-configure from weird? It'll be a bit annoying to debug if it's only sporadic single frame glitches. :/

Do you mean it reproduces using *left* half of the right view?

**Comment by kennylevinsen** [comment]
Reproducing with `V[foot T[weston-simple-egl H[foot foot]]]`, I see at times in excess of 30 transactions queued, with the current transaction compression unable to take care of all of it, so active state is a few txn iterations behind.

However, it would seem that rendering the titlebars like that imply that `con->current.y` of the child container is very different from that of the parent, so it seems like a weird transaction. Or maybe the arrange logic occasionally messes up.

**Comment by kennylevinsen** [comment]
Added some debug, occasionally see this

```
00:01:00.180 [sway/tree/arrange.c:293] Arranging workspace '1' at 20.000000, 20.000000
00:01:00.180 [sway/tree/arrange.c:156] Arranging 0x7fffdebbd650 vertically
00:01:00.180 [sway/tree/arrange.c:77] Arranging 0x7fffdebbd540 horizontally
> queuring 7 instructions, 27 queued transactions
> id 4, id 6, id 11, id 7, id 8, id 9, id 10, 
00:01:00.201 [sway/tree/arrange.c:77] Arranging 0x7fffdebbd660 horizontally
> queuring 3 instructions, 28 queued transactions
> id 7, id 8, id 9, 
```

Where the structure is:
```
3: WL-1
   4: vsplit
      6: foot
      10: tab
         11: weston-simple-gl (hidden)
         9: hsplit
            7: foot
            8: foot
```

So indeed, a transaction is being committed on just the hsplit.

**Comment by kennylevinsen** [comment]
I think I found the problem - it's related to the transaction compression we do (skipping to the last transaction when these seem identical).

In `container_resize_tiled`, which is what is used to do the resize, we:
1. Find the "resize" parent (i.e. the container whose split will be modified to accommodate the request),
2. Change the split ratio, and
3. If the resize parent *also* has a parent, arrange that. Otherwise, we arrange the entire workspace.

In this setup, we hit both of the arrange branches in a single move. For the horizontal movement, we arrange_container, whereas for the vertical movement, we arrange_workspace. Resizing in vertically or in both directions leads to a transaction with 7 instructions, whereas resizing only horizontally leads to a transaction with 3 instructions.

Imagine the following transaction set:
1. Horizontal resize, subset (`H[app app]`)
2. Vertical resize, entire workspace (`V[app T[slow H[app app]]]`)
3. Horizontal resize, rubset (`H[app app]`)

When we grab the first transaction, we try to compress matching transactions. This is done by going through all transactions, and if a later transaction have the same number of instructions, and the instruction *nodes* match, then the later transaction is taken and the earlier one deleted.

This results in transaction 1 being discarded and replaced with transaction 3. However, while the first transaction only performed a horizontal resize, all transactions include the full container state. Applying transaction 3 therefore also applies the vertical resize that happened as part of transaction 2. This leads to the graphical glitch.

As we are queuing transactions on every pointer event, the timeout situation mean we end up piling up a *lot* of transactions, increasing the likelihood of the issue. It also increases the differences in resize/reposition, making it more likely to be noticed.

As for how to fix it, we can either:
1. Always re-arrange the entire workspace.
2. Remove the transaction compression, and just apply transactions in order.
3. Remake the transaction system to be a list of operations to perform rather than just snapshots of states to apply.
4. Make the transaction compression comparison aware of the operation performed so it can stop if a transaction adds more changes.
5. Stop having a queue, but instead just a single pending transaction that all instructions get added to.

Number 1 and 2 would be suboptimal. I have previously implemented 5, which seems to work well. 3 and 4 are more work.

**Comment by Xyene** [comment]
Nice sleuthing!

> 1. Always re-arrange the entire workspace.

Agreed, this sounds too slow.

> 2. Remove the transaction compression, and just apply transactions in order.

This is _definitely_ too slow. The transaction compression was pretty broken until https://github.com/swaywm/sway/pull/5744, and there was a bug report about it (https://github.com/swaywm/sway/issues/5736) because with a 1000 Hz mouse, windows just can't keep up even on a beefy rig.

> 4. Remake the transaction system to be a list of operations to perform rather than just snapshots of states to apply.
> 5. Make the transaction compression comparison aware of the operation performed so it can stop if a transaction adds more changes.

I'm don't have a clear picture in my head of what this would entail, but agreed that this sounds like a big change.

> 5. Stop having a queue, but instead just a single pending transaction that all instructions get added to.

This one seems very reasonable to me. Are there any gotchas you're aware of?

**Comment by kennylevinsen** [comment]
> I'm don't have a clear picture in my head of what this would entail, but agreed that this sounds like a big change.

Neither do I - and I'm fairly certain it would be a pain.

> This one seems very reasonable to me. Are there any gotchas you're aware of?

@emersion presented concerns, but I couldn't see any issues once it got to a more polished state.

I ended up just implementing it [here](https://github.com/swaywm/sway/pull/6018), so feel free to give it a shot. Seems to solve the issue for me, and I can't see any immediate issues.
