### ISSUE TITLE
Enable games to control VSync

### ISSUE THREAD

**Issue by pac85** [swaywm/sway#6043]
I know this has kind of been addressed before in #4715, however I don't think the problem has been actually addressed. Having any kind of vsync introduces significant input lag, this is inherent to the concept of vsync. Now different people like different settings for different games, and this is why games usually have it as an option. However, when running under sway changing that option in the game's menu makes pretty much no difference: the game is vsynced regardless and enabling it only changes wether the game uselessly waits for the vertical blank or not. OnestlyI consider this broken, if the option is there it should just work. Under  i3 I usually disable the compositor before launching any games, this way the game option works perfectly, with no tearing if VSync is enabled and with tearing present but very little input lag when the option is disabled. It works because the output of the game is sent to the screen as soon as the game swaps his buffers. I'm pretty sure that this could be done in sway too, in fact I think it should be done. I personally don't mind screen tearing, i like to enable it in first person shooters and disable it in platformers or racing games (this is actually pretty common among gamers).

**Comment by emersion** [comment]
No. A well-optimized vsync compositor has comparable latency to tearing content updates. Instead of investing efforts in tearing, invest efforts in improving vsync.

See the discussion in https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/65.

**Comment by erolm-a** [comment]
So, you're basically saying that your presentation-time vsync protocol, that is not backed up by any paper or empirical evidence that should be better or more optimized, is better than what the graphics industry has been doing for basically 20/30 years (i.e. direct memory write)? Apologies but I can't stop laughing at this. It sounds very condescending and disrespectful of what the SoTA of the graphics pipeline looks like. 

Honestly I don't see why allowing people to disable vsync, and thus the "every frame is perfect" idea in *special* circumstances is an issue. If a subset of people want a lower input lag and are happy with occasional tearing, let them tear! It seems to me Wayland users have a very poor understanding that gamers do exist and that things have changed since we had 70Hz monitors. Windows applications do direct memory write all the time when DX, OGL and Vulkan are used: *normally*  you let a compositor do the work and apply nice post-processing effects (e.g. blurring, shadowing etc.), but when one such application is on you allow the zone to perform direct write on that.

Could you please stop thinking users are all dumb? Power users exist and have plenty of reasons to hack around. Clearly no-one is happy with X11 but pretending use cases don't exist is at best short-sighted, at worst a sign of condescension...

Last point: enforcing vsync to make every frame tearless is like telling people your house is fire-proof simply because it is not linked to the grid network.

**Comment by emersion** [comment]
Judging from your tone, this isn't going to be constructive.

As a side note, remember that I don't owe you anything. If you're not happy with Sway, nobody forces you to use it.
