### ISSUE TITLE
seat command make firefox/thunderbird crash on reload

### ISSUE THREAD

**Issue by thuck** [swaywm/sway#6085]
- **Sway Version:**
  - `sway version 1.5.1`

- **Configuration File:**
  -  [config](https://github.com/swaywm/sway/blob/master/config.in)

- **Description:**
  - Include `seat * hide_cursor 8000`
  - Open firefox/thunderbird
  - Reload config
  - Firefox will crash with error: `Lost connection to Wayland compositor`

**Comment by Xyene** [comment]
This issue is tracked on Firefox's side: https://bugzilla.mozilla.org/show_bug.cgi?id=1652820

**Comment by thuck** [comment]
@Xyene I included the information on the ticket, but this doesn't happen without the seat.
Something is special on the reload of the configuration when we have the seat.
The only thing that I see is the `wl_event_loop_add_idle` in commds/reload.c and inputs/keyboard.c in both cases.

**Comment by thuck** [comment]
No; looks like there is a odd behavior when handling the seats on firefox.
Removing the wl_event*; i get this error:
```Gdk-Message: 17:00:39.468: Error flushing display: Broken pipe
Sandbox: Unexpected EOF, op 2 flags 0400000 path /sys/devices/pci0000:00/0000:00:08.1/0000:06:00.0
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Sandbox: Unexpected EOF, op 2 flags 00 path /usr/share/X11/xkb
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
 ``` 
 Maybe related with:
 https://bugzilla.mozilla.org/show_bug.cgi?id=1466015

**Comment by kennylevinsen** [comment]
As written in the firefox bug, the `wl_event_loop_add_idle` queues another function to be run - it's not of any interest on its own.

Please only update one place at a time - we end up with unnecessary notifications and having to answer multiple times otherwise. It's fairly likely (but not certain) that this is a firefox bug, so keep it there for now and come back if we conclude otherwise.

(Also, feel free to answer the request I made a few weeks back over there for sway debug logs and sway's own WAYLAND_DEBUG=server output.)
