### ISSUE TITLE
[suggestion] New type of layout

### ISSUE THREAD

**Issue by jvalrog** [swaywm/sway#622]
Previously posted on i3 issues as: https://github.com/i3/i3/issues/1977

The idea is to add a new type of stacked layout that doesn't eat the user's screen. In this mode the tabs are stacked vertically but at one side of the screen, so there is always a constant space of the screen available for the user desktop.

There is a Firefox addon that does something like this: https://addons.mozilla.org/en-us/firefox/addon/tree-style-tab/

![62ced478-69db-11e5-8c9b-6b9755fda9b9](https://cloud.githubusercontent.com/assets/456311/14936519/dbf2c1d8-0ee6-11e6-99b8-dced38ffacbe.jpg)

**Comment by SirCmpwn** [comment]
I like the idea but the concerns raised by i3 definitely need to be addressed.

**Comment by mikkeloscar** [comment]
This would be fairly easy to implement.

Have you thought about how we could decide on the width of the tabs? I'm thinking it could be calculated based on the font size, so it scales with the rest of the sway UI, but it might look weird on different resolutions.

**Comment by jvalencia80** [comment]
The width would be user defined, in pixels for example. Large text would be cropped, or just display the window class/name or something like that.

As already mentioned in the i3 thread, the stacked layout also has the problem of running out of space, but that issue hasn't been solved yet.

One possible solution would be to scroll the tab list as the user goes up/down in the list and to show special tabs with an arrow or "..." in the top or bottom position indicating that there are more tabs in that direction. That would allow for "infinite" windows (constrained by memory).

But I don't know how difficult would be to do that.

**Comment by ke7ofi** [comment]
@SirCmpwn What do you mean by "concerns raised by i3"?

**Comment by SirCmpwn** [comment]
Regarding things like the width of the titlebar.

**Comment by ke7ofi** [comment]
@SirCmpwn How is that i3-specific?

**Comment by SirCmpwn** [comment]
What?

**Comment by ke7ofi** [comment]
I'm not sure which of us is more confused. Are you saying that there's a problem because it's a feature that i3 doesn't have?

**Comment by SirCmpwn** [comment]
1. Click this link: https://github.com/i3/i3/issues/1977
2. Read the concerns raised by i3 developers
3. Apply the same concerns to sway

**Comment by ke7ofi** [comment]
@SirCmpwn Thanks, that makes a lot more sense. Having read that, I would point out that window titles being clipped already happens in tabbed (and conceivably, though much less plausibly, other) mode(s) with long titles, particularly webpages followed by something like "- Mozilla Firefox (Private Browsing)".. My vote is to offer the following options for tab width:

- static percentage of screen

- longest title's length (dynamic)

- static number of pixels

- static number of characters

Also, what if we allowed adjustment through similar means to adjusting window width?

**Comment by MogeiWang** [comment]
This feature is so cool, please do consider to implement it. Thx

**Comment by MogeiWang** [comment]
1. The stacking layout is very different with the tabbed layout in that, title bars are listed in different directions. For stacking layout, title bars are listed vertically; while for tabbed layout, title bars are listed horizontally. This simple fact implies that, very different results will be obtained by pressing `Mod-Shift-Left/Right` or `Mod-Shift-Up/Down`.
It is true that, the stacking layout can be regarded as a transposed tabbed layout, or vv. But such a fact does not really help, since English texts is printed horizontally in most applications.

1. This layout would be very helpful.
In fact, I hoped to have such a layout even in those days of using wmii.

1. I do not really care about the width of title bars, but it would be perfect if the width can be configured. 
Additionally, it is also acceptable if texts in title bars are printed vertically in the new layout, and each character is transposed.

**Comment by SirCmpwn** [comment]
Implement it if you want it.
