### ISSUE TITLE
Nvidia support due to Beta Drivers

### ISSUE THREAD

**Issue by betstick** [swaywm/sway#6342]
### Please fill out the following:
- **Description:**
The new Nvidia Beta 470 drivers work well enough that I can launch Sway on Turing hardware and run 3D applications like Steam games and Blender without any issues. In fact, these applications specifically work better under Sway than under i3 and X. That's not to say it is 100% perfect, there's some odd stuttering when the cursor icon changes, but applications work well and video performance is very high. I also had to compile the entire Wayland and Sway stack from source to get it running.

Will Nvidia drivers be reconsidered now that Nvidia has better support for Wayland?

Included is a screenshot of Sway working with Firefox, Blender, and Stalker running via Wine in fullscreen:
EDIT: scrot doesn't seem to work.

**Comment by betstick** [comment]
![output12](https://user-images.githubusercontent.com/61669265/123230377-32afb380-d4a5-11eb-9f45-e2c8d418ce07.png)
Grimshot does work though.

**Comment by emersion** [comment]
> The new Nvidia Beta 470 drivers work well enough that I can launch Sway on Turing hardware and run 3D applications like Steam games and Blender without any issues

That's surprising. Are you sure you're using their driver? I don't think 470 is supposed to support GBM. Or does it? Maybe you can collect debug logs with `sway -d >sway.log 2>&1`?

> Will Nvidia drivers be reconsidered now that Nvidia has better support for Wayland?

If NVIDIA proprietary drivers work, that's good for you. However, we'll not officially support any proprietary driver. The reason is that proprietary drivers make it extremely more difficult to debug graphics issues (we don't have the source code for the driver) and makes it impossible to send upstream fixes (which is something we've done for i915, amdgpu and nouveau for instance).

**Comment by betstick** [comment]
[sway.log](https://github.com/swaywm/sway/files/6709198/sway.log)

Here's the log if it means anything.

**Comment by emersion** [comment]
The log ends early with an error message about NVIDIA.
