### ISSUE TITLE
Inconsistent existence of tabs for single windows

### ISSUE THREAD

**Issue by al-caveman** [swaywm/sway#6656]
- **Sway Version:** `gui-wm/sway-1.6.1-r1::gentoo  USE="man swaybar swaybg swayidle swaylock swaymsg swaynag wallpapers -X -tray"`.

  - `swaymsg -t get_version` or `sway -v`: sway version 1.6.1

- **Producing the problem:**
1. Create a window.  E.g. `mod + Enter` to open a terminal window.
2. Observe that, since the window is alone (not stacked/tabbed), it has no tab on top of it, which is the normal behaviour.
3. Create another window.  E.g. `mod + Enter` again for another terminal window.
4. Transform the 2 tiles into stacking or tabbing mode. E.g. `mod + s` for stacking.  
5. Observe that each window now has a tab, which is normal behaviour.
6. Close one of the terminal windows, so that only one is left, much like how the situation was in **step 1**.
7. Observe that now, unlike **step 2**, the window has a tab, despite being the only window.

- **How it should be:**
**Step 7** must be like **step 2**; i.e. no tabs.

**Comment by Kljunas2** [comment]
I think that is expected behaviour. When you switch to tabbed layout, you put both windows into another container with tabbed layout. But when you close a window, you don't take the other one out of the container.
You can see in the output of `swaymsg -t get_tree`:
1. Open a window: `"representation": "H[Alacritty]"`
2. Open another window: `"representation": "H[Alacritty Alacritty]"`
3. Switch to tabbed layout: `"representation": "H[T[Alacritty Alacritty]]"`
4. Close one of the windows: `"representation": "H[T[Alacritty]]"`

You can get the same result, if you open only a single window and then switch to tabbed layout. (Then you would get the same `representation`s as in step 1. and 2.)

**Comment by al-caveman** [comment]
`H[T[Alacritty]]` is indeed what the final step must be like, however it's not really related to this bug as I'll clarify:

- This is not a question of _"should we change the container type from what the user has set last time?"_
- This is rather a question of _"should a tabbed container, with only a single window in it, show its tab bar?"_

Basically, when `default_border pixel ...`, the tab bar of `H[T[Alacritty]]` must be hidden in order to match the `i3` behaviour.

The `i3` behaviour is also more _correct_ in this regard, because there is no _utility_ in seeing the tabbar in `pixel` border mode when there is only 1 window in it.  So I'm not suggesting to blindly copy `i3` in its mistakes.

**Comment by Xyene** [comment]
I think what you are looking for here is `hide_edge_borders --i3`. The i3 behavior is supported, but is not the default.
