### ISSUE TITLE
Floating in the overlay layer

### ISSUE THREAD

**Issue by tinywrkb** [swaywm/sway#6799]
One feature that I'm used to from running Chrome as a XWayland client, is that I can enter full screen mode in Chrome, and then show scratchpad without exiting fullscreen mode.  
This might be a bug, but one that I'm making good use of.  
When running Chrome as a Wayland client, bringing up a scratchpad will exit fullscreen mode.

I would like to see support to optionally set a floating window's layer as overlay.  
The workaround, running the application in a nested compositor, creates another problem, no clipboard sync between the parent and nested compositors.

**Comment by emersion** [comment]
Sorry, we're not accepting any new window management features anymore. See https://github.com/swaywm/sway/blob/master/CONTRIBUTING.md#scope-of-future-changes-to-sway

**Comment by tinywrkb** [comment]
Thanks, I hoped this doesn't fall under that category. Also, it could be implemented as global setting, enabled for all floating or all scratchpad windows, so it's not really a window management command.

**Comment by b0o** [comment]
This would be an excellent feature. I like to pop up a scratchpad to take notes while watching a video, but currently it kicks me out of full screen which is jarring and often derails my train of thought. 

A slightly less desirable but adequate solution for me is #4255, the ability to put an application into full screen mode without the container being full-screened in sway. As I understand, i3 has a similar feature, so it shouldn’t fall under the feature freeze? See also #6658

**Comment by tinywrkb** [comment]
> A slightly less desirable but adequate solution for me is https://github.com/swaywm/sway/pull/4255, the ability to put an application into full screen mode without the container being full-screened in sway.

I don't like it, it's too generic. Who would want to inhibit fullscreen changes events when the application is spanned across the workspace or all workspaces? It sounds wrong, and I'm not sure if this doesn't create new problems, like hiding XDG Portals' popup windows.  
This should only work if the application is in a child container that is not covering the whole workspace.

**Comment by tinywrkb** [comment]
Also, I'm not sure that this can solve the issue that I described. While the app will show its full screen UI, I suspect that the container will still exit the fullscreen mode and display layer shell applications (e.g. status bar).

**Comment by b0o** [comment]
> While the app will show its full screen UI, I suspect that the container will still exit the fullscreen mode and display layer shell applications (e.g. status bar).

I think that is the aim of the PR. Granted, it’s not ideal, but since we’re in workaround territory, I think it’s a reasonable solution. To go further, one could create a key binding to hide the statusbar and set `hide_edge_borders smart_no_gaps`; that gets you very close to “native” full screen while still being able to display a floating window over top.

> I'm not sure if this doesn't create new problems, like hiding XDG Portals' popup windows

I’ve not used portals, but I don’t see how this would be an issue. If I understand correctly, setting `inhibit_fullscreen` followed by fullscreening the application itself would result in a normal non-fullscreen container with the application displaying its fullscreen UI. Why would this be different than any other non-fullscreen window? Popups should still display over top.

**Comment by emdash** [comment]
The main use I have for this is so I can have a floating terminal appear even over a full-screen session. I have noticed that rofi can place itself above even my fullscreen windows. I would just like to be able to pop up a terminal in the same way, so that I could e.g. `killall -9 misbehaving_process` or other quick action, where I need to see the output of the command.
