### ISSUE TITLE
view keeps executed criteria in xwayland view even when window is closed and reopened

### ISSUE THREAD

**Issue by Hippo0o** [swaywm/sway#6905]
- **Sway Version:**
  - `v1.7`

- **Description:**
Apps in xwayland view like discord or slack will keep same xwayland view when closing to tray. When reopening them all criteria will be skipped because they were already executed when first opening the app.

- **Solution:**
adding `view->executed_criteria = create_list();` in `xwayland::handle_map()` worked for me.

**Comment by emersion** [comment]
How does i3 behave here?

**Comment by Hippo0o** [comment]
@emersion When taking discord as example.
- assign always moves discord when reopening
- for_window floating and sticky rules are always reapplied 

Without rules it doesn't save floating mode but sticky stays enabled. :thinking:

**Comment by Hippo0o** [comment]
like in sway an xwayland view seems to stay active while the container isn't even on an output anymore. When reopening e.g. discord it also always gets a new container id.

**Comment by Hippo0o** [comment]
Maybe i forgot to mention that this means that rules never get applied anymore. 
Floating rules for example will not work when opening from tray because of this, as they are already tracked as applied.

**Comment by josecastillolema** [comment]
Hi,
If I understood correctly I am hitting the same issue in Sway v1.8 with a WhatsApp xwayland app.
My sway config:
```
for_window [class="whatsapp-desktop-linux"] floating enable
```

```
swaymsg -t get tree
...
      #42: con "WhatsApp" (xwayland, pid: 10223, instance: "whatsapp-desktop-linux", class: "whatsapp-desktop-linux", X11 window: 0x1400003)
```

The first time I open the app it is indeed floating, however uppon minimizing to tray and opening again it gets stacked.

**Comment by EBADBEEF** [comment]
I'm hitting the same problem with steam. I want the window to be floating and it only gets applied the first time the window appears. Subsequent times I get "Criteria already executed". Steam stays running in the background when the window is closed.

@Hippo0o if you re-allocate the list in `sway/desktop/xwayland.c:handle_map()`, doesn't that leak memory? I think you would want to call 'list_free_items_and_destroy' before 'list_create'.

Not really sure what the correct solution is. Why do we even keep track of if the criteria has already been applied? It is mentioned in 3b0c26d149dfe5e05df338692db8255a01f0998d that it is "the same strategy used by i3". Presumably the user could have modified the criteria after they were set and don't want it to "magically" get reapplied due to some event. I guess I could try i3 and see what happens ;-) Free the criteria on unmap?

Is there an equivalent problem with wayland where a window can be unmapped but not destroyed?

**Comment by Hippo0o** [comment]
@EBADBEEF ye thats what i did back then https://github.com/Hippo0o/sway/commit/860586e5c107c68b7dc60c8a2e1fc3137fa5eb6f
