### ISSUE TITLE
Bug or not developed feature: app opening in wrong workspace

### ISSUE THREAD

**Issue by Skycader** [swaywm/sway#6909]
Hello, I do not know if it's a bug, it's rather really useful feature that is still not implemented.
Once you intend to open a new window in Sway, it might take a while for a program to start, so you go somewhere else, 
to other workspace to do some other job. However, since a few moments you get to see an opening window of a program you
intended to open in OTHER workspace. It's quite bothering, actually. So would you please make Sway remember the intended workspace for a starting app that hasn't been opened yet? Thank you.

**Comment by emersion** [comment]
Sway should already remember the workspace a program was launched in and recognize it by PID.

What is the exact program you're having trouble with? Debug logs?

**Comment by manfred3000** [comment]
I think @Skycader is describing a behavior where e.g. you are on WS-x and launch an app which starts wit a delay (due to low memory, config, whatever) and than switch to WS-y, the app will launch in the focused WS (WS-y) rather than in WS-x.
For less powerful hardware this feature (launch app in WS where the initialization happened, rather than in the focused WS) whould actually be nice to have - don't know whether it's feasible or not, though.

**Comment by emersion** [comment]
As I said above, this feature is already implemented.

**Comment by RPigott** [comment]
Sway's built in launcher (swaymsg exec) already tries to match new application windows to the workspace they were launched on by pid. #6639 extends the implementation a bit so that applications can support this in a few more cases – forking, dbus launch etc.

There's only so much sway can do here. If it's not working for some app you'll at least need to share logs. It's possible sway could use more heuristics here but most likely will require the behavior to be fixed in the application.
