### ISSUE TITLE
Firefox pip subtitle handling

### ISSUE THREAD

**Issue by Iss-in** [swaywm/sway#6981]
- **Sway Version:**
  - `sway version 1.8-dev-8fba9c04 (Apr 14 2022, branch 'master')
`

So firefox released a new feature this version , now Pip mode also show subtitles in it. But its not working well with sway. If a video is running in pip mode, with subtitles on, subtitles froze (they dont change even even if video is playing ) when

- main browser window is tiled and unfoccussed
- main browser window is in scratchpad

They only work when
- main browser window is floating ( focused or not )
- main browser window  tiling and focussed 

No such problem in gnome when window is minimized

**Comment by ArtyIF** [comment]
I'm using GNOME Shell on Wayland and I'm having the same issue. Found this issue by googling it. So it seems to be more of a Firefox/Wayland issue than sway

**Comment by Funami580** [comment]
From my tests, it depends on the website. It freezes for YouTube, but this site works: https://iandevlin.github.io/mdn/video-player-with-captions/. The reason seems to be, that different adapters are used, for example for YouTube it would be this one: https://searchfox.org/mozilla-central/source/browser/extensions/pictureinpicture/video-wrappers/youtube.js. The MutationObserver that is used in the adapter for YouTube should work in the background, so I think the reason is that YouTube detects that the browser is not in the foreground and stops updating the subtitles. Sadly, I haven't found a workaround so far. I tried an extension called "Always Active Window", but it didn't seem to do the trick.

**Comment by Iss-in** [comment]
yea, this turned out to be a firefox problem, https://bugzilla.mozilla.org/show_bug.cgi?id=1770429

**Comment by Funami580** [comment]
@Iss-in May I ask if the issue has been fixed for you? The Bugzilla Issue you sent says "verified fixed", but I still experience the issue with LibreWolf 126.0.1-1.

**Comment by Iss-in** [comment]
@Funami580 yes, no issue in firefox anymore, probably librewolf hasnt reached that version yet
