### ISSUE TITLE
Sway/wlroots git - hide_cursor doesn't hide cursor

### ISSUE THREAD

**Issue by aqxa1** [swaywm/sway#7059]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.8-dev-956b689d (Jun  9 2022, branch 'HEAD')

- **Debug Log:**
  - https://gist.github.com/aqxa1/60b26b98e81e6b9466a28f03e5e9a29a

- **Configuration File:**
  - https://gist.github.com/aqxa1/868ee9b88c8a123841a6385cbe7b25e3

- **Description:**
  - Setting hide_cursor with `seat seat0 hide_cursor 1000` in config (and with swaymsg) fails to hide cursor with inactivity since a recent git sway/wlroots update (around 1 week ago I suspect). Sway 1.7 doesn't exhibit the issue.

**Comment by brett-mahar** [comment]
I'm experiencing the same problem since updating to sway-git on the ArchLinux AUR, at around the same time. Unclutter doesn't work either, I have some vague memory that it did in the past, but I might be getting cofused with i3...

sway version 1.8-dev-1c69d0e7 (Jun 14 2022, branch 'master')

Linux RockPi4B+ 5.18.5-1-MANJARO-ARM #1 SMP PREEMPT Thu Jun 16 13:00:21 UTC 2022 aarch64 GNU/Linux

**Comment by brett-mahar** [comment]
I tried this again with today's '-current' branch, hide_cursor is working again on aarch64 :-) , sway version:

sway -v
sway version 1.8-dev-49cef51e (Jun 20 2022, branch 'master')

**Comment by aqxa1** [comment]
Still seems to be broken for me. And I don't think there's been any recent `sway` updates, just `wlroots` (which I also updated).

**Comment by Emantor** [comment]
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3625

**Comment by aqxa1** [comment]
Thanks, I can confirm current wlroots git fixes the issue.
