### ISSUE TITLE
Correct the behavior of the resize command for arbitrary sizes

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#713]
- Syntax needs to match i3
- Should work on floating views

**Comment by zandrmartin** [comment]
FWIW it's probably worth just removing all the changes from #709 and starting from scratch on this one, the way I added it was pretty janky.

**Comment by zandrmartin** [comment]
Someone mentioned on IRC that i3 has a default dimension for `resize` and after reading through the i3 docs I've found there are some other things we're missing. Here's (what I believe to be) an exhaustive list of what we need for true i3-compatibility with our resize command:

- currently our `resize` does not support floating views at all as mentioned above
- need to differentiate between "10px" and "10ppt" (or more correctly "10 px" and "10 ppt") - right now we're just using `strtol()` to get the number and assuming it's pixels no matter what. An "x ppt" dimension should adjust the size by x percentage points. If I understand the documentation correctly, i3 restricts px dimensions to floating and ppt dimensions to tiled but I don't see why we couldn't make both dimension types work with both view types.
- need default dimensions. i3 defaults to 10px for floating views and 10ppt for tiled views.
- need to support up/down/left/right directions for `resize <grow|shrink> <direction>` command
- our `resize <width|height> <amount>` syntax needs to change to `resize set <width> [dimension] <height> [dimension]`. In i3 this command only works on floating views - personally I'd like it to work on both floating and tiled views in Sway but that's a minor point.

**Comment by zandrmartin** [comment]
[i3 syntax](https://i3wm.org/docs/userguide.html#resizingconfig) for `resize set` is `resize set <width> [px] <height> [px]`, so `resize set 640 480` would set the width to 640 and the height to 480. I don't really like that syntax. What I'd prefer is `resize set width 640 height 480` so that either dimension is optional.

@SirCmpwn I'll implement the i3 syntax, but how do you feel about my syntax also being an option? Pro: can set either dimension without touching the other. Con: more syntax to maintain and document, maybe not actually that useful?

**Comment by SirCmpwn** [comment]
That sounds fine to me.

**Comment by SirCmpwn** [comment]
I'm closing issues that are resolved by the yet-unreleased sway 1.0.
