### ISSUE TITLE
NVIDIA Support

### ISSUE THREAD

**Issue by EndChapter** [swaywm/sway#7516]
I understand the criticism about NVIDIA, but I didn't even know about Open Source or FOSS while buying this computer, and I am not that rich to buy a new computer (or a new GPU). The problem is not only me, because I am sure that there are so many people like me. I am upset for wanting this, but can SWAY support NVIDIA?

**Comment by emersion** [comment]
We support nouveau. We do not support the proprietary driver. This isn't going to change.

**Comment by ilmagico** [comment]
While I understand the stance against closed-source drivers, I want to understand if sway has an issue just with closed-source drivers, or with anything coming out of NVIDIA.

In particular, while I'm fully aware how uncooperative NVIDIA has been in the past (see EGLStreams for example), recently they started being more accommodating, implementing GBM and even releasing an [open source driver](https://github.com/NVIDIA/open-gpu-kernel-modules) (dual MIT/GPL).

So, without opening a new ticket unnecessarily just to ask a question, I'll ask here: **Does sway support the nvidia open source ("nvidia-open") driver, or will it support it in the future?**

**Comment by bl4ckb0ne** [comment]
Sway's main issue is closed-source drivers. There's nothing we can do to debug issues with the NVIDIA driver, so that's why we're closing the issues. It may seems rude at first but it's the only thing we can do. 

The "open-source" driver that NVIDIA released is a kernel module. Their user-land driver (EGL/GL/VK) is still very closed source, and that's the one we're dealing with.
