### ISSUE TITLE
Allow refresh rate flexibility on output modes

### ISSUE THREAD

**Issue by AndreasBackx** [swaywm/sway#7599]
An example of various modes reported by a monitor:
- 2560x1440 @ 143.856 Hz
- 2560x1440 @ 119.881 Hz
- 2560x1440 @ 99.946 Hz
- 2560x1440 @ 59.951 Hz

Currently if you want to change the refresh rate, you have to use `swaymsg -t get_outputs` to see the exact refresh rate that is being reported and that you want. This is because "144Hz" won't be accepted, though it is what users likely know about their monitor. It would save people time and it would be more user friendly.

Secondly, different drivers/cards report different refresh rates for the same monitor. My AMD card reports "143.856 Hz", another machine with an Nvidia card reports "143.923 Hz", and a third machine reports "144.006 Hz". If I could enter "144Hz" in my config, the same config can be used for different machines connected to the same monitor.

What do you think of allowing rounded refresh rates to be inputted and let Sway automatically select the mode that, when rounded, would be said value?

**Comment by taminob** [comment]
I'd like to start contributing a bit and this looks like a good first issue to me.
Is this still considered relevant and do you accept contributions for this issue?

From my understanding (looking at `set_mode` in `sway/config/output.c`), the current behavior is as follows:

- if there is no match for the resolution, it is an error and the preferred/default mode will be used as fallback
- if there is an exact match for the refresh rate and resolution, this mode will be selected
- otherwise, the highest refresh rate matching the resolution will be chosen (ignoring the user-given refresh rate)

To address the issue mentioned here, I'd suggest adding another "rule" which will select the closest refresh rate matching the user-given refresh rate (a limit for the difference could be considered).

Additionally, I'm not sure if it is intended behavior that the user-specified refresh rate is ignored without warning/error if there is no exactly matching mode.

**Comment by emersion** [comment]
Yeah, it probably makes sense to match the nearest refresh rate up to a limit. For instance kanshi does this: https://git.sr.ht/~emersion/kanshi/commit/d83229664e9c9f8724ac5936a345fa973befefe0

And yeah definitely some more logging when no mode could be found would definitely be a good thing.

**Comment by taminob** [comment]
Thanks for the quick response and the link with the solution in kanshi.

Then I'll start implementing a proposal and will open a PR soon.

**Comment by asiantuntija** [comment]
I'm confused, I've used the resolution@rounded refresh rate in my config for years and never had a problem, am I just lucky that it has been working everywhere or has something changed very recently?

**Comment by taminob** [comment]
> I'm confused, I've used the resolution@rounded refresh rate in my config for years and never had a problem, am I just lucky that it has been working everywhere or has something changed very recently?

The current behavior does not fail if you don't specify the exact refresh rate, but will fallback to the highest refresh rate that is available for the same resolution.

A use case where simply taking the highest refresh rate is not sufficient is described in the kanshi issue linked above (no Display Stream Compression for high res displays).

**Comment by GrabbenD** [comment]
> https://git.sr.ht/~emersion/kanshi/commit/d83229664e9c9f8724ac5936a345fa973befefe0
> Pick lowest delta when fuzzy matching refreshes
> 
> If we have a refresh, try to pick something with an exact refresh first.
> Doing a fuzzy match initially here can lead us to picking a refresh
> such as 120.01 or 60.01, which is problematic for two reasons:
> - Modes such as 4K 120.01Hz is too much for link bandwidth of DP 1.4 without DSC.
> - It becomes out of phase with the majority of content being displayed.
>
> Fixes me not being able to use 4K 120Hz on my monitor with AMDGPU + Radeon VII which supports DP 1.4, but not DSC (Display Stream Compression).

I've noticed that specific refresh rates from `swaymsg -t get_outputs` breaks VRR/Freesync with my monitor (I know this is vague).  Could this be related to the issue I'm experiencing?
