### ISSUE TITLE
Automatic Power Management System

### ISSUE THREAD

**Issue by KSinghofficial** [swaywm/sway#7765]
I forgot to turn off my system last night, now the hardware is completely destroyed
also in past I have many times forgot to shutdown but at that time I used DE probably KDE/Gnome they automatically turn off my system after prelong inactivity .

##Sway do turn off screen after maybe 10 minutes of inactivity , but it still runs everything in the background.

###Suggestion 
Make a automatic power off mode users can still turn on /off this feature in ./config/sway/config by (default it is off).
There should be two options for this 
A. Power off with hybernation mode 
B. Power off 
These two options should be modificable in config file by default option B is selected.

**Comment by emersion** [comment]
Sorry, this is out-of-scope for Sway. An external daemon can implement this if desired.

**Comment by pj-connect** [comment]
Would you please explain why it is out of scope ? Because I experience a serious broken system, as my system was in hibernation and the battery ran out.

**Comment by kamlendras** [comment]
> Would you please explain why it is out of scope ? Because I experience a serious broken system, as my system was in hibernation and the battery ran out.

can you elaborate more what do you mean by serious broken system?

**Comment by pj-connect** [comment]
For some reason, on ubuntu 23.10 and sway, the initramfs got corrupted and it's trying to resume from memory, and wont go thru a normal boot sequence, even though I created a new initramfs. Also, for some reason, I can't enable cryptsetup in the initramfs busybox. It is as if, even though I update, or create, an initramfs, changes are not made. I'm actually chrooting from live usb to the broken system, and even though everything seems to be configure properly, it stubbornly want to resume from memory/swap ??? I am given the error in initramfs:  _Gave up waiting for resume/suspend_.

I'm actually describing a scenario where the system's initrd (initial ramdisk) was altered to enable resuming from suspend (hibernate), but due to a power failure, while in hibernate mode, the initrd became corrupted, as the computer lost power, leading to an inability to recognize the LUKS/LVM partition where the root file system resides, even when instructed not to resume. Additionally, the initrd failed to restore the previous state before hibernate, thereby disrupting the normal boot sequence, including the prompt for the LUKS password. Rebuilding initrd does not reinstate the default state for normal booting. So, I was unable to boot, falling into initramfs, 

There seems to be a persistent configuration somewhere, hindering the return to the previous state of normal boot sequence or the default boot sequence. It's possible that the issue lies in the construction of initrd with LUKS support and crucially, the unlocking of the LUKS container, most likely occurring in or around the premount stage to ensure readiness of the root file system for utilization. Despite configuring the modules in /etc/initramfs-tools/modules and attempting to set up the GRUB command line to acknowledge a LUKS container, along with ensuring proper configurations of crypttab and fstab, initrd remains unwilling to include and utilize cryptsetup. Nonetheless, it's worth noting that /boot/grub/grub.cfg does include the correct path, and /proc/cmdline does contain the accurate information. Yet, the crux of the matter persists: initrd simply refuses to acknowledge, and unlock (no luks prompt), the LUKS container.

All to say, UPower maybe at fault here. But it seems, that while in hibernation, power lost occured, without restoring the previous state, leaving initramfs wanting to resume from memory/swap. 

After lots of troubleshooting, I installed cryptsetup-initramfs, manually open the luks container once dropped into initramfs just after "Begin: Running /scripts/init-premount", finally booted successfully. Did a update-initramfs -c -k all. Rebooted successfully.

**Comment by pj-connect** [comment]
Understanding the full scope and capabilities of power management within Sway is crucial for effectively configuring power settings across various desktop environments such as KDE, GNOME, Xfce, or MATE. Upon closer examination, it becomes evident that sway/swayidle operates by listening to events rather than initiating system suspension or hibernation. This thus raises doubts about the existence of robust power management features within Sway.

Recently, I made the decision to remove Plasma from my device (including the login manager), and it's power manager, commonly known as  [PowerDevil](https://blogs.kde.org/2024/04/23/powerdevil-in-plasma-6.0-and-beyond/). It's worth noting that certain desktop environments come equipped with background power managers, which, in my case, have been running unnoticed, even though I am using sway.

Through this process, I've come to realize that my system was previously configured to utilize suspend-to-RAM, also known simply as suspend or sleep mode. Surprisingly, the issue I encountered was not related to UPower as initially suspected, but rather stemmed from PowerDevil running in the background and messing thing up.

I'm actualli considering [TLP](https://linrunner.de/tlp/index.html), for power management functionalities. As previously explained, Troubleshooting the issue is crucial for understanding why it occurred in the first place. I did not make any progress in pinpointing the root cause. I'm still troubleshooting.

**Comment by pj-connect** [comment]
Now I've actually configured my system to use systemd suspend (s2idle deep) , which a trigger at command line. Works totally fine with FullDiskEncryption, and ask my passphrase when resuming. I have no display manager, yet, so I get a beautifull blank screen when suspending. I'v also installed  [TLP - Optimize Linux Laptop Battery Life](https://linrunner.de/tlp/index.html).

To the benifit of [kamlendras](https://github.com/kamlendras), and as for external daemon, here is a little script example that could be daemonized :

```
#!/bin/bash

source ./libs/console_logger

# upower -i $(upower -e | grep 'BAT') | grep percentage | grep -o "[0-9]*"

# Set the battery level threshold for shutdown (in percentage)
BATTERY_THRESHOLD=20

# Function to get the current battery level
function get_battery_level() {
	
    # Check if the 'pmset' command is available (for macOS)
	if command -v pmset &>/dev/null; then
		battery_level=$(pmset -g batt | grep -Eo "\d+%" | cut -d'%' -f1)
	# Check if the 'upower' command is available (for Linux)
	elif command -v upower &>/dev/null; then
		battery_level=$(upower -i $(upower -e | grep 'BAT') | grep -E "state|to\ full|percentage" | grep -o "[0-9]*%" | head -n 1 | tr -d '%')
	else
		print_error "Error: Neither 'pmset' nor 'upower' command found. Unable to get battery level."
		exit 1
	fi
    
    # does not print to console, simply return battery level.
	echo "$battery_level"
}

# Function to initiate shutdown
function initiate_shutdown() {
	echo "Battery level is below $BATTERY_THRESHOLD%. Initiating shutdown..."
	shutdown -h now
}

# Main loop to monitor battery level
while true; do
	battery_level=$(get_battery_level)
	if [ -z "$battery_level" ]; then
		print_error "Error: Unable to get battery level."
		exit 1
	fi

	if [ "$battery_level" -le "$BATTERY_THRESHOLD" ]; then
		initiate_shutdown
		break
	fi
    
    print_msg "$battery_level"
	sleep 60 # Check battery level every minute
done

```
