### ISSUE TITLE
Allow to enable Xwayland XCSECURITY (x11 security extension)

### ISSUE THREAD

**Issue by voidastro4** [swaywm/sway#7866]
Xwayland is often built with XCSECURITY

But there is no way to enable it.

Add an option to be able to enable XCSECURITY in the sway config. 

ex.

`xwayland force security`

**Comment by kennylevinsen** [comment]
The Xsecurity extension is enabled by default. What specific configuration that is sway's responsibility is missing?

**Comment by voidastro4** [comment]
XCSECURITY would block screen sharing between x11 applications.
it doesn't do that on sway xwayland

**Comment by emersion** [comment]
It should be possible to set `WLR_XWAYLAND` to an executable which adds its own flags, e.g.

```sh
#!/bin/sh -eu
exec /usr/bin/Xwayland +extension SECURITY "$@"
```

**Comment by kennylevinsen** [comment]
> XCSECURITY would block screen sharing between x11 applications.

The X11 Security extension ("xcsecurity" is the name of the build option, not the feature) allows grouping applications into "trusted" applications allowed to do anything they want and "untrusted" applications allowed to do almost nothing at all - not just screen sharing getting blocked - using authentication cookies.
 
The default state is for clients to be trusted (i.e., allow anything), and you have to go out of your way to make an application untrusted - see https://unix.stackexchange.com/questions/648178/block-screen-sharing for an example. That's just how the extension works.  For more fine-grained control than "on/off" you need to deal with the X Access Control Extension (ACE) on top.

Closing for now, can be reopened if there is something sway is required to do as an X11 WM that we're missing, or setup that sway must do. Also, note that the real security option is `xwayland disable`.

**Comment by voidastro4** [comment]
I see. The design of this feature makes little sense.
Sway has no Xauthority file anywhere, does this mean the cookie is empty?
If an application has access to the x11 socket what is stopping it from initiating another connection to the socket with an empty cookie and gaining trusted status?

**Comment by kennylevinsen** [comment]
Sway does not itself do anything to create cookies - what we do is "just" to start an X server, telling it that we'll be the WM. I imagine this puts you in a similar state to e.g. having started a plain i3 session on bare Xorg.

"How to use X" is somewhat off-topic to sway's issue tracker - we're a Wayland compositor, and we outsource the X compatibility to xorg's Xwayland - but if there's a particular step that X11 WMs or Wayland compositors are expected to do in general that we're missing, then please do file a bug report specifically for that.

Otherwise, the general solution to X11 Security in sway is Wayland. :)
