### ISSUE TITLE
Starting Manjaro Sway after installation

### ISSUE THREAD

**Issue by eddykiss75** [swaywm/sway#7873]
- **Sway Version:**

      manjaro-sway-22.1.2-231217-linux61

- **Debug Log:**
  
     i havent

- **Configuration File:**
     
       i havent

- **Description:**

  - Sorry for my english, never learnd.
  - i installed the manjaro-sway iso to my computer.
  - after restarting, i got a this screen.

![IMG_1623](https://github.com/swaywm/sway/assets/154657126/6c04aed8-fa97-4bdc-ae6c-0e58109061dd)

And then nothing. Nothing works, just the Ctrl+Alt+Del helps.

Any idea?

**Comment by eddykiss75** [comment]
The laptop is an Acer Swift 3 314-43, brand new

**Comment by domai-tb** [comment]
Hey, this isn't related to sway. I had the exact same problem yesterday after installing a fresh new Manjaro. 

The problem is related to the configuration of `greetd` - the login manager Manjaro's Sway edition uses. To solve this you have to open a new TTY (e.g. `alt+str+f3`) and edit the configuration file under `/etc/greetd/config.toml`. The command `tuigreet` uses `--remeber-session` and `--remeber-user-session` at the same time - what isn't allowed (first line of your screenshot). So I removed the `--remeber-user-session` flag and now it is working.

**Comment by eddykiss75** [comment]
Thx, i will try it

**Comment by eddykiss75** [comment]
Thx ágain, i'm in Noé

**Comment by eddykiss75** [comment]
Now
