### ISSUE TITLE
waybar is not shown sometimes on master branch

### ISSUE THREAD

**Issue by svalaskevicius** [swaywm/sway#8075]
- **Sway Version:**
  - branch based on master commit 23389ebd

- **Configuration File:**
relevant bit:
```
bar bar1 {
    id bar1
    swaybar_command waybar -b bar1
    mode hide
    modifier $mod
}

exec waybar -b bar1
```

- **Description:**

when waybar is configured to be shown only on $mod key press, it fails to appear after a window is created in that workspace.

switching to another workspace and hitting the $mod summons waybar as expected. even if I switch back to the original workspace, waybar is still shown while I keep $mod pressed. pressing it again does not show waybar in this workspace. no logs nor errors are reported when the key is pressed.

**Comment by svalaskevicius** [comment]
forgot to add - swaybar is working ok with regards to this behaviour. so my assumption was that this is related to rendering the top shell layer. but I wasn't able to find the fault in the short time I had

**Comment by svalaskevicius** [comment]
update from commit 4d4c88f0  - waybar is showing now, but the region is not repainted after mod key is released and waybar is hidden - that region is black, until the underlying window invalidates it or parts of it (then it repaints parts)

**Comment by Nefsen402** [comment]
I cannot reproduce this issue even when 4d4c88f was reverted on my local branch. I think there might me more to your configuration file? It sounds like the new symptoms have something to do with damage tracking, which at this point is unlikely since the renderer rewrite of sway. A demo video and a list of steps to reproduce would help.

**Comment by svalaskevicius** [comment]
sure, what should I use to record the screen / what other info can I provide?

**Comment by svalaskevicius** [comment]
my cfgs are also https://github.com/svalaskevicius/dotfiles/blob/gen-2024/.config/sway/config except the hide lone titlebar flag which should be commented out on this commit


there is also waybar config in a nearby file

**Comment by svalaskevicius** [comment]
also, it doesnt happen _all_ the time - but very frequently. especially after:
1. hold mod - waybar appears
2. press number to switch workspace
3. release mod  - waybar disappears, with black background, until the underlying window invokes a repaint

**Comment by Nefsen402** [comment]
Yeah, I've switched workspaces many times in my testing and have not seen it go wrong once. I am testing on the wayland backend with a nested session, but the backend should have nothing to do with this error. What kind of hardware are you running? Maybe it's a driver problem causing the screen not to repaint correctly? What version of waybar?

**Comment by svalaskevicius** [comment]
sorry I missed the question.

hardware - amd graphics card, but no other effects like that so I doubt it could be it, also an older sway version works fine (the one from arch packages - `1.9-5`

waybar - I'm on arch - so it's gonna be 0.10.4-1 (not at that pc atm to check for sure but it's all up to date and that's the current version)

hmm I haven't tested in a nested session - can do that later in the evening, can also try recording video - if I find a screen recorder :)

**Comment by svalaskevicius** [comment]
right, I can reproduce in a nested sway too, attaching a screen recording:

https://github.com/user-attachments/assets/a93c74eb-05ba-48a4-b038-a88218052982

**Comment by svalaskevicius** [comment]
no idea why is github/firefox saying that the file is corrupt

```
wget 'https://github.com/user-attachments/assets/a93c74eb-05ba-48a4-b038-a88218052982'
mv a93c74eb-05ba-48a4-b038-a88218052982 aa.mp4    
```

vlc plays it ok.. it was recorded with `wf-recorder`

**Comment by Nefsen402** [comment]
Yeah, I don't know what going on with firefox and some video files. It's been bugged like that since forever. The video was very helpful thank you, it looks like this might be more to do with the waybar configuration than anything else. You have an opaque background, so more scene optimizations are trying to kick in.

The issue can probably be worked around with the WLR_SCENE_DISABLE_VISIBILITY=1 in the env.

**Comment by Nefsen402** [comment]
Thanks, I can reproduce.

**Comment by Nefsen402** [comment]
This is a waybar bug. When waybar is trying to show/hide when pressing the mod key, it doesn't unmap the surface, it instead commits a completely transparent buffer. However, waybar does not update the transparency status of the buffer and still claims it's opaque. `WLR_SCENE_DISABLE_VISIBILITY=1` doesn't work because that only disables one optimization. We have a second optimization that will set the blend mode to NONE if the surface is supposed to be opaque.

**Comment by Nefsen402** [comment]
Opened an issue here: https://github.com/Alexays/Waybar/issues/3492

**Comment by svalaskevicius** [comment]
Thanks for debugging this and finding the cause so quickly!
