### ISSUE TITLE
Hole in titlebar with fractional scaling

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#8233]
Configure an output with fractional scaling, open a floating window with a SSD titlebar, move it around. Depending on the position a hole around the title texture may appear. (Also happens with tiled windows, but floating windows make it more obvious that it depends on the position.)

![out](https://github.com/swaywm/sway/assets/506932/eb378159-f010-49fd-a636-c2bd1536577a)

**Comment by kennylevinsen** [comment]
Hmm, I can reproduce this nested using part of your dotfile config, and it seems quite sensitive. Config attached.

[sway_config.txt](https://github.com/user-attachments/files/16128284/sway_config.txt)

Reproduction:
1. alt+enter to open terminal, alt+space to float, alt+shift+b to toggle border to ssd
2. Move the window

If the title changes, it often resolves the issue even when changing the title back, so the issue is somewhat unstable. Running commands under a shell that updates the title like fish does the trick. Peculiar.

**Comment by kennylevinsen** [comment]
Okay, the issue is that we draw the titlebar in 5 pieces:
1. A rectangular title text scene buffer, drawn with the background color
2. 4 scene rects to pad the text buffer to the titlebar boundary, one for each side. The dimensions of these rects are calculated by making a pixman rect cover the entire titlebar, then subtracting the text buffer geometry.

This setup leads to the rounding issues discussed in the fractional scaling protocol proposal: Any two points whose position has a fractional scaling applied might in some positions on the screen round towards each other, in others away from each other.

We can fix the instability (but not the risk of holes in the first place) by having wlr_scene round positions of all nodes within the view's tree relative to the view's topmost tree (does not have to be the xdg_toplevel as long as rounding result no longer depends on the position on the screen).

Fixing the hole is done by either:
1. Using a single rect and a transparent text buffer. This might make subpixel antialiasing impossible to do right, and while subpixel antialiasing is a curse, we might not want to go this route.
2. Just extend the text buffer to the full titlebar dimensions, doing away with rects altogether.

I doubt using the rects is worth it, so let's just go with number 2.

**Comment by Nefsen402** [comment]
The scene patches used to do solution 1. but more than just sub pixel antialiasing being a concern, this would make opacity look weird. Number 2. is fine, but I don't like the idea of re-rendering a text buffer if someone resizes a window if it doesn't need to.

**Comment by kennylevinsen** [comment]
> The scene patches used to do solution 1. but more than just sub pixel antialiasing being a concern, this would make opacity look weird.

Maybe we can make opacity acceptable (not perfect) by hacking around with the foreground text color and alpha channel, but that doesn't help subpixel - especially as vulkan and gles2 renderers disagree on blending.

> Number 2. is fine, but I don't like the idea of re-rendering a text buffer if someone resizes a window if it doesn't need to.

We could keep a tightly rendered text buffer that we can memcpy to the scene buffer, but as long as it doesn't make sway judder we can make it work in one PR and make it fast in another.

Wasting cycles is annoying, but resizing isn't a hot path, and worse things are happening doing the resize anyway as the application reallocates swapchains and rerenders its surface...

**Comment by WhyNotHugo** [comment]
I frequently see the rightmost side of title texts cropped.

Here's an example:

![image](https://github.com/swaywm/sway/assets/730811/09dd448a-bda6-4841-83b2-2b8c16718bb8)

After reading the explanation for this bug, I suspect that my issue might have the same root cause.

**Comment by kennylevinsen** [comment]
Eh, my diagnosis was way off it seemed.

> I frequently see the rightmost side of title texts cropped.

This is a separate issue caused by miscalculating the text geometry. `sway_text_node` getting the text geometry for scale 1, and applying the render scale to the dimensions on its own, but this does not match the behavior of pango when actually rendering at that scale.

**Comment by emersion** [comment]
Turns out this bug was specific to black borders. See https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4745
