### ISSUE TITLE
crash after staying unused for a short time

### ISSUE THREAD

**Issue by svalaskevicius** [swaywm/sway#8328]
- **Sway Version:**
  - `swaymsg -t get_version` or `sway -v`
 sway version 1.10-dev-8eddb83f (Aug 31 2024, branch 'hiding-lone-titlebar-scenegraph')

  built using this master commit:
  ```
  * 292e7013 (HEAD -> hiding-lone-titlebar-scenegraph)  fix hiding lone titlebar (Sarunas Valaskevicius) 2024-03-08
  * 41c5ec96  fix hiding lone titlebar (Sarunas Valaskevicius) 2024-02-28
  * f38b6ad7  add --smart-titles flag to hide_edge_borders (Guilhem Saurel) 2023-12-29
  >> * 980a4e02 (upstream/master, upstream/HEAD)  use subheadings instead (Jon Wallace) 2024-08-27
  ```

stderr, stdout, and crash stacktrace: https://gist.github.com/svalaskevicius/1bb506cbbca62c20e8284f4924ac1399

- **Configuration File:**
https://github.com/svalaskevicius/dotfiles/blob/gen-2024/.config/sway/config

- **Stack Trace:**
see https://gist.github.com/svalaskevicius/1bb506cbbca62c20e8284f4924ac1399

- **Description:**
I left the PC be, could be related to any timeouts, swaylock etc

**Comment by Nefsen402** [comment]
@kennylevinsen I believe you were running into a similar assert (negative size passed to wlr_scene_rect_create)

**Comment by svalaskevicius** [comment]
hmm I suppose it _could_ be related to #8076 ...

**Comment by svalaskevicius** [comment]
> hmm I suppose it _could_ be related to #8076 ...

I take that back `arrange_output (output=0x59efd45ac140, width=0, height=0) at ../sway/desktop/transaction.c:598` - the whole output is 0x0 ??

**Comment by kennylevinsen** [comment]
So the issue is:
1. An output is alive and active with workspaces and windows on it.
2. The output is disabled.
3. The output disconnects from standby.
4. The output reconnects on its own, but is still disabled and so has no mode.
6. The output is added to the layout, but with a zero-sized box
7. Workspaces are attempted arranged on this layout, but everything is trying to calculate with the zero dimensions and things explode.

The only way I see to handle this is to ensure that:
1. When an output is not enabled, ensure that all workspace/scene nodes are disabled so they cannot spill over to neighboring outputs. I don't remember if we already do this - it's late.
2. Skip arrange for outputs that are disabled.

Attempting to fill in the output dimensions with the old values will mean that the geometry we arrange for no longer match the position of scene outputs, and just skipping arrange with nodes enabled will mean that the nodes can "spill" onto neighboring outputs that now overlap with the output's old geometry.
