### ISSUE TITLE
Mod1 not dropped when switching workspaces

### ISSUE THREAD

**Issue by tuncer** [swaywm/sway#881]
If `$mod` is set to `Mod1` and you switch from one workspace to another, and the new workspace has a fullscreen Firefox, then Firefox's menus will be activated, because `Mod1` is not fully processed+dropped yet. Doesn't happen, obviously, if `$mod` is set to `Mod4`.

**Comment by thejan2009** [comment]
Just sharing some of my findings. It might be a wlc xwayland bug.

The cause is not ```Mod1``` not being processed and dropped. When an xwayland window gets focused, it gets sent a ```modifier pressed``` event.  This doesn't occur with native wayland windows. 

Reproducing the issue with xev:
```xev | grep -A 4 "KeyPress\|KeyRelease"```
If you observe the output when changing focus to xev window with $mod+l, there will be Super_L KeyPress event (or Alt_L in your case, I guess) before KeyRelease event.

It doesn't happen with wayland clients, though:
```WAYLAND_DEBUG=1 weston-terminal 2>&1 | grep "wl_keyboard.*key("```
When this window receives focus in the same way as xev, it will only receive KeyRelease events (indiciated by the last number in line being 0).

**Comment by tuncer** [comment]
I've observed the same issue under pure X11 with a Java Swing application.

**Comment by tuncer** [comment]
Closing due to wlroots rewrite.
